### ISSUE TITLE
Unable to create Azure Cache for Redis

### ISSUE THREAD

**Issue by danielbichuetti** [pulumi/pulumi-azure-native#1637] opened 2022-04-08 19:42 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Creating Azure Cache for Redis is failing but Pulumi returns it's created. Using Azure Classic works, bug just happens on AzureNative.

### Steps to reproduce

1. Install Pulumi
2. Generate a C# project
3. Add a stack
4. Use AzureNative
5. Create AzureNative.Cache.Redis resource
6. Call pulumi up

Expected: Create Azure Cache Redis
Actual: Pulumi returns resource is created and then when trying to list the keys we see resource is not created. Going into Azure Portal resource was not created.

` +   ├─ azure-native:cache:Redis            redis-xxxxx-us       create`

`Diagnostics:
  pulumi:pulumi:Stack (Deploy.Pulumi.Azure-dev):
    error: Running program 'xxxxxxxxxxxxxxxxx\Deploy.Pulumi.Azure\bin\Debug\netcoreapp3.1\Deploy.Pulumi.Azure.dll' failed with an unhandled exception:
    Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="invocation of azure-native:cache:listRedisKeys returned an error: request failed /subscriptions/fa8647c6-1a4b-4052-9db3-fcf87349a469/resourceGroups/rg-xxxxx-usbf62490c/providers/Microsoft.Cache/redis/redis-xxxxx-usa08a8ab9/listKeys: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Cache/Redis/redis-xxxxx-usa08a8ab9' under resource group 'rg-xxxxx-usbf62490c' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"")`

**Comment by jkodroff** [comment] 2022-04-12 18:08
@danielbichuetti Thanks for submitting this issue. We'll add it to our backlog and address as soon as we can.

**Comment by mikhailshilkov** [comment] 2022-12-22 14:25
This looks like a dupe of #1031

**Closed by mikhailshilkov** 2022-12-22 14:25 UTC
Labels: kind/bug, resolution/duplicate
