### ISSUE TITLE
Deployment of an Azure Container App with secrets with a KeyVault reference fails

### ISSUE THREAD

**Issue by ehasnain** [pulumi/pulumi-azure-native#2807] opened 2023-10-05 07:24 UTC
### What happened?

When an azure container app with a secret that has a reference (key_vault_url and identity) to a KeyVault Secret is deployed, it fails with the following message:

`Code="ContainerAppSecretInvalid" Message="Invalid Request: Container app secret(s) with name(s) 'test-secret' are invalid: value or keyVaultUrl and identity should be provided."`

### Example

Here are the relevant deployments to reproduce the issue:

```python
# Create an Azure Managed Identity
identity = managedidentity.UserAssignedIdentity('identity',
                                                resource_group_name=resource_group.name,
                                                tags=resource_tags)

# Create an Azure Key Vault
key_vault = keyvault.Vault(
    'my-vault',
    resource_group_name=resource_group.name,
    properties=keyvault.VaultPropertiesArgs(
        access_policies=[keyvault.AccessPolicyEntryArgs(
            object_id=identity.principal_id,
            tenant_id=identity.tenant_id,
            permissions=keyvault.PermissionsArgs(
                secrets=[
                    keyvault.SecretPermissions.GET,
                    keyvault.SecretPermissions.LIST,
                    keyvault.SecretPermissions.DELETE,
                    ],
                ),
        )],
        tenant_id=identity.tenant_id,
        sku=keyvault.SkuArgs(
            family=keyvault.SkuFamily.A,
            name=keyvault.SkuName.STANDARD,
        )
    ),
    tags=resource_tags
)

# Create a Secret
test_secret = keyvault.Secret(
    'test-secret',
    resource_group_name=resource_group.name,
    vault_name=key_vault.name,
    properties=keyvault.SecretPropertiesArgs(
        value="SECRET",
        content_type="text/plain",
    ),
    opts=pulumi.ResourceOptions(ignore_changes=["properties.value","properties.content_type"]),
    tags=resource_tags
)

# Fetch created secret properties
test_secret_props = keyvault.get_secret(
    resource_group_name=resource_group.name,
    vault_name=key_vault.name,
    secret_name=test_secret.name,
)

# create a container app
container_app = app.ContainerApp(
    "app",
    resource_group_name=resource_group.name,
    managed_environment_id=managed_env.id,
    tags=resource_tags,
    identity=app.ManagedServiceIdentityArgs(
        type=app.ManagedServiceIdentityType.USER_ASSIGNED,
        user_assigned_identities=[identity.id]
        ),
    configuration=app.ConfigurationArgs(
        ingress=app.IngressArgs(
            external=True,
            target_port=7000,
        ),
        registries=[
            app.RegistryCredentialsArgs(
                server=registry.login_server,
                username=registry_username,
                password_secret_ref="registry-pwd")
        ],
        secrets=[
            app.SecretArgs(
                name="registry-pwd",
                value=registry_password,
            ),
            app.SecretArgs(
                name="test-token",
                key_vault_url=test_secret_props.properties.secret_uri,
                identity=identity.id,
            ),
        ],
    ),
    template=app.TemplateArgs(
        containers = [
            app.ContainerArgs(
                name=gateway_image_name,
                image=gateway_image.image_name,
            ),
            app.ContainerArgs(
                name=backend_image_name,
                image=backend_image.image_name,
                env=[
                    app.EnvironmentVarArgs(
                        name="TEST_TOKEN",
                        secret_ref='test-token'
                    ),
                ]
            ),
        ],
    ),
)


```

### Output of `pulumi about`

CLI          
Version      3.86.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  2.9.0
docker        4.4.1
python        unknown
random        4.14.0

Host     
OS       darwin
Version  14.0
Arch     arm64

This project is written in python: executable='~/anaconda3/envs/sums-ai-iac/bin/python3' version='3.10.13'

Current Stack: <replaced>

TYPE                                               URN
<replaced>                                         <replaced>

Found no pending operations associated with dev

Backend        
Name           <replaced>
URL            file://~
User           <replaced>
Organizations  
Token type     personal

Dependencies:
NAME                 VERSION
pip                  23.2.1
pulumi-azure-native  2.9.0
pulumi-docker        4.4.1
pulumi-random        4.14.0
setuptools           68.2.2
wheel                0.41.2

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by ehasnain** [comment] 2023-10-09 07:48
The issue makes more sense here. Thanks @justinvp. :)

**Comment by zhangpengchen** [comment] 2023-10-12 14:06
Same here, with the following `dependencies` in the package.json (Typescript)

```
"dependencies": {
    "@pulumi/azure": "^5.52.0",
    "@pulumi/azure-native": "^2.11.0",
    "@pulumi/azuread": "^5.42.0",
    "@pulumi/docker": "^4.4.3",
    "@pulumi/pulumi": "^3.88.0"
  }
```

Received an error

```
azure-native:app:ContainerApp (app-...:
    error: Code="ContainerAppSecretInvalid" Message="Invalid Request: Container app secret(s) with name(s) 'database-url, jwt-secret, ...' are invalid: value or keyVaultUrl and identity should be provided."
```

```
  const resourceGroup = new resources.ResourceGroup(`rg-${projectNameShort}-${environment}`, {
    tags: tags,
  });

  // Create a User Assigned Identity (Managed Identity)
  const identity = new managedidentity.UserAssignedIdentity("identity", {
    resourceGroupName: resourceGroup.name,
  });
  
  const jwtSecretValue = config.get("jwtSecret") || "";
  const jwtSecret = createSecret(vault, "jwt-secret", jwtSecretValue);

  const cookieSecretValue = config.get("cookieSecret") || "";
  const cookieSecret = createSecret(vault, "cookie-secret", cookieSecretValue);

  const databaseUrlSecretValue = config.get("databaseUrl") || "";
  const databaseUrl = createSecret(vault, "database-url", databaseUrlSecretValue);
  
  const containerApp = new app.ContainerApp(`app-${projectNameShort}-${environment}-${serviceName}`, {
    resourceGroupName: resourceGroup.name,
    managedEnvironmentId: managedEnv.id,
    identity: {
      type: "UserAssigned",
      userAssignedIdentities: [identity.id],
    },
    configuration: {
      activeRevisionsMode: "Single",
      ingress: {
        external: true,
        targetPort: 9000,
      },
      registries: [{
        server: registry.loginServer,
        username: acrUsername,
        passwordSecretRef: "container-password",
      }],
      secrets: [{
        name: "container-password",
        value: acrPassword,
      }, {
        name: "jwt-secret",
        keyVaultUrl: secretUris.jwtSecret,
        identity: identity.id,
      }, {
        name: "cookie-secret",
        keyVaultUrl: secretUris.cookieSecret,
        identity: identity.id,
      }, {
        name: "database-url",
        keyVaultUrl: secretUris.databaseUrl,
        identity: identity.id,
      }, {
```

```
function createSecret(
  vault: azure.keyvault.KeyVault,
  name: string,
  value: string,
): pulumi.Output<string> {
  const secret = new azure.keyvault.Secret(name, {
    keyVaultId: vault.id,
    name, // Prevent a maximum length error: could not make instance of 'azure:keyvault/secret:Secret': name '...' plus 7 random chars is longer than maximum length 24
    value,
  });

  const secretUri = pulumi.interpolate`${vault.vaultUri}secrets/${secret.name}/${secret.version}`;
  return secretUri
}
```

**Comment by mikhailshilkov** [comment] 2023-10-12 16:50
@zhangpengchen Have you tried using the `v20230501` version of `app`?

**Comment by zhangpengchen** [comment] 2023-10-14 13:23
> @zhangpengchen Have you tried using the `v20230501` version of `app`?

Is there an option for nodejs?

**Comment by mikhailshilkov** [comment] 2023-10-16 06:28
Yes, sure

```
import * as app from "@pulumi/azure-native/app/v20230501";
```

**Comment by zhangpengchen** [comment] 2023-10-16 14:24
> Yes, sure
> 
> ```
> import * as app from "@pulumi/azure-native/app/v20230501";
> ```

Thanks @mikhailshilkov, it works correctly with the `v20230501` version of `app`

**Comment by mikhailshilkov** [comment] 2023-10-17 19:50
Nice. Closing as a dupe of https://github.com/pulumi/pulumi-azure-native/issues/2673.

**Closed by mikhailshilkov** 2023-10-17 19:50 UTC
Labels: kind/bug, resolution/duplicate

**Comment by Fady-Benattayallah** [comment] 2025-01-16 11:49
I am still getting this error as of pulumi 3.138.0, is this still broken?
