### ISSUE TITLE
Indication, which property change triggers a recreate.

### ISSUE THREAD

**Issue by dirien** [pulumi/pulumi-azure-native#2223] opened 2023-02-03 16:30 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently we have no indication, which property change triggers a recreation of the resource. It would be nice to have a way to flag them and let the Pulumi Registry renders the `Changes to this property will trigger replacement` icon. 

### Affected area/feature

provider

**Comment by thomas11** [comment] 2023-02-03 23:34
duplicate of #2026 - please upvote :)

**Closed by thomas11** 2023-02-03 23:34 UTC
Labels: kind/enhancement, resolution/duplicate, area/providers
