### ISSUE TITLE
Unable to migrate resource between versions

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-azure-native#2397] opened 2023-04-21 17:45 UTC
### What happened?

A user attempted to switch from `Pulumi.AzureNative.Databricks` to `Pulumi.AzureNative.Databricks.V20230201`. This resulted in a replace being generated, instead of the expected no-op.

### Expected Behavior

We expect this resource to be aliased as described in https://www.pulumi.com/registry/packages/azure-native/version-guide/.

### Steps to reproduce

See https://pulumi-community.slack.com/archives/CRVK66N5U/p1682027492647039 for details.

### Output of `pulumi about`

Pulumi 3.54.1
Pulumi.AzureNative 1.100.0
Pulumi CLI: 3.63.0

### Additional context

Issue arose from [Community Slack](https://pulumi-community.slack.com/archives/CRVK66N5U/p1682027492647039).

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment] 2023-07-13 22:56
Context from Slack:

> Pulumi Azure Native Databricks resource is defined inside my component resource. The databricks resource does have the parent property set to my component resource as well.

**Comment by mikhailshilkov** [comment] 2023-07-13 22:57
It looks to be a duplicate of https://github.com/pulumi/pulumi-azure-native/issues/2505 - I'll close in favour of the other issue that has more details

**Closed by mikhailshilkov** 2023-07-13 22:57 UTC
Labels: impact/usability, kind/bug, resolution/duplicate
