### ISSUE TITLE
Unable to create Azure Api Management Operation with Policy 

### ISSUE THREAD

**Issue by KamilLach** [pulumi/pulumi-azure-native#1730] opened 2022-05-25 19:09 UTC
### What happened?

When trying to create (azure-native) Api Management operation with policy i am getting response ,

`cannot create already existing resource '/subscriptions/**/resourceGroups/**/providers/Microsoft.ApiManagement/service/**/apis/**/operations/**/policies/policy`

I didn't created that policy - everything is done through pulumi.

### Steps to reproduce

1. Create Api Management Service. (works)
2. Create Api (works)
3. Create Operation (works)
4. Try to create policy (fails)

1.

```
var apiManagementService = new ApiManagementService("apiManagementService", new ApiManagementServiceArgs
            {
                EnableClientCertificate = config.RequireBoolean("apim-client-cert-state"),
                PublisherEmail = "admin@xx.com",
                PublisherName = "xx",
                ResourceGroupName = resourceGroupName, 
                ServiceName = config.Require("apim-name"),
                Sku = new ApiManagementServiceSkuPropertiesArgs
                {
                    Capacity = 1,
                    Name = config.Require("apim-sku"),
                },
                Tags = StackTagsProvider.GetDefaultTags(Deployment.Instance),
                VirtualNetworkType = "None",
            });
```

2.
```
    var api = new Api(functionAppType, new ApiArgs
        {
            ApiId = funcNameKey,
            Description = Output.Format($"Import from `{reportApp.DefaultHostName}` Function APP"),
            DisplayName = funcName,
            Path = funcName,
            Protocols = 
            {
                Protocol.Https,
            },
            ResourceGroupName = resourceGroupApplication.Name,
            ServiceName =  config.Require("apim-name"),
            ServiceUrl = Output.Format($"https://{reportApp.DefaultHostName}/{functionAppType}.service"),
            SubscriptionRequired = false, 
        });
```

3.

```
var getTokenOperation = new ApiOperation("operationgettoken", new ApiOperationArgs
        {
            ApiId = api.Name,
            Method = "GET",
            Description = "xx",
            DisplayName = "xx",
            UrlTemplate = "token",
            ResourceGroupName = resourceGroupApplication.Name,
            ServiceName = config.Require("apim-name"),
            Responses = new[]
            {
                new ResponseContractArgs
                {
                    Representations = new[]
                    {
                        new RepresentationContractArgs
                        {
                            ContentType = "application/json"
                        }
                    },
                    StatusCode = 200
                }
            }
       });
```

4.

```
_ = new ApiOperationPolicy("apiOperationGetPolicy", new ApiOperationPolicyArgs
        {
            ApiId = api.Name,
            Format = "xml",
            OperationId = getTokenOperation.Name,
            PolicyId = "policy",
            ResourceGroupName = resourceGroupApplication.Name,
            ServiceName = config.Require("apim-name"),
            Value = policy,
        });
```

### Expected Behavior

Should not fail 

### Actual Behavior

Failing with resource already exists  - looks like policy resource is automatically created by ARM Api, and we can't control it later. 

### Additional context

Similar problem is visible when i am trying to create policy (global) on APi Management Service level.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment] 2022-05-30 10:30
Hi @KamilLach 

I am going to suggest that this is a duplicate of https://github.com/pulumi/pulumi-azure-native/issues/1729 - would you feel that is correct here?

Paul

**Comment by KamilLach** [comment] 2022-06-08 12:48
@stack72 correct, created at the same time ;)

**Comment by nathanbacon** [comment] 2022-06-30 23:13
@KamilLach 

I recently ran into a similar problem while using Terraform and ran into this issue while trying to search if somebody had encountered it before. The problem I found is that when you delete an operation policy in Azure Portal, it doesn't actually delete it. It just replaces it with an empty policy document. You can find this by exporting API Management as an ARM template and searching for the operation name. To fix this I ended up deleting the policy in Azure Powershell. Afterward, the conflict was gone.

`$apimContext = New-AzApiManagementContext -ResourceGroupName "myrg" -ServiceName "myservice"`

`Remove-AzApiManagementPolicy -Context $apimContext -ApiId "myapi" -OperationId "myoperation"`

**Comment by mikhailshilkov** [comment] 2023-03-31 10:12
Closing as a dupe of #1729 per https://github.com/pulumi/pulumi-azure-native/issues/1730#issuecomment-1149871288

**Closed by mikhailshilkov** 2023-03-31 10:12 UTC
Labels: kind/bug, resolution/duplicate, awaiting-feedback
