### ISSUE TITLE
GetSubnet API version no longer supported

### ISSUE THREAD

**Issue by ShawnNeckelmann** [pulumi/pulumi-azure-native#2011] opened 2022-10-04 20:16 UTC
### What happened?

https://www.pulumi.com/registry/packages/azure-native/api-docs/network/getsubnet/

### Steps to reproduce

```
var subnet = GetSubnet.Invoke(new GetSubnetInvokeArgs()
        {
            ResourceGroupName = "",
            VirtualNetworkName = "",
            SubnetName = ""
        });
```

### Expected Behavior

A subnet is returned.

### Actual Behavior

![image](https://user-images.githubusercontent.com/73409007/193917353-29860c0a-b8d5-4a19-9234-572334dec0cc.png)

Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="invocation of azure-native:network:getSubnet returned an error: request failed /subscriptions/cea372df-cd91-4096-b947-e18c97297f7b/resourceGroups//providers/Microsoft.Network/virtualNetworks//subnets/: autorest/azure: Service returned an error. Status=400 Code="InvalidApiVersionParameter" Message="The api-version '2020-11-01' is invalid. The supported versions are '2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."")

### Output of `pulumi about`

running 'dotnet build -nologo .'
  Determining projects to restore...

  All projects are up-to-date for restore.

  Artifacts.WorkItems -> C:\Users\shawn\Source\Datalink\Iac.Pulumi\src\Resources\Artifacts\Artifacts.WorkItems\bin\Debug\net6.0\Artifacts.WorkItems.dll

  Pulumi.Helpers -> C:\Users\shawn\Source\Datalink\Iac.Pulumi\src\Helpers\Pulumi.Helpers\bin\Debug\net6.0\Pulumi.Helpers.dll

  BuildingBlocks.Tls -> C:\Users\shawn\Source\Datalink\Iac.Pulumi\src\Resources\BuildingBlocks\BuildingBlocks.Tls\bin\Debug\net6.0\BuildingBlocks.Tls.dll

  BuildingBlocks.AzureActiveDirectory -> C:\Users\shawn\Source\Datalink\Iac.Pulumi\src\Resources\BuildingBlocks\BuildingBlocks.AzureActiveDirectory\bin\Debug\net6.0\BuildingBlocks.AzureActiveDirectory.dll

  BuildingBlocks.AzureResources -> C:\Users\shawn\Source\Datalink\Iac.Pulumi\src\Resources\BuildingBlocks\BuildingBlocks.AzureResources\bin\Debug\net6.0\BuildingBlocks.AzureResources.dll

  Artifacts.AzureResources -> C:\Users\shawn\Source\Datalink\Iac.Pulumi\src\Resources\Artifacts\Artifacts.AzureResources\bin\Debug\net6.0\Artifacts.AzureResources.dll

  Iac.Environment -> C:\Users\shawn\Source\Datalink\Iac.Pulumi\src\Stacks\Iac.Environment\bin\Debug\net6.0\Iac.Environment.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.97

'dotnet build -nologo .' completed successfully
CLI          
Version      3.40.2
Go Version   go1.19.1
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.79.2
azuread       5.28.0
dotnet        unknown
random        4.8.2
tls           4.6.1

Host     
OS       Microsoft Windows 11 Pro
Version  10.0.22621 Build 22621
Arch     x86_64

This project is written in dotnet: executable='C:\Program Files\dotnet\dotnet.exe' version='6.0.401'

Current Stack: dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/dl_sneckelmann
User           dl_sneckelmann
Organizations  dl_sneckelmann

Dependencies:
NAME                VERSION
Pulumi              3.40.2
Pulumi.AzureNative  1.79.2

Pulumi locates its logs in C:\Users\shawn\AppData\Local\Temp by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment] 2022-10-05 19:23
Hi, thanks for reporting this. This is fairly unprecidented for Microsoft to take a stable version of an API out of operation without a lot of advance communication. Have you been in contact with Azure support yet on this issue to verify if there's been a service issue their side?

As a workaround you can explicitly specify the API version by importing from the SDK e.g. in typescript:

```typescript
import * as network from "@pulumi/azure-native/network/v20210101";
```

**Comment by NNG9y1PQdXl** [comment] 2023-05-11 14:47
Is there any way to work-around it if I'm using yaml? I don't think I can define API version while importing.

**Comment by NNG9y1PQdXl** [comment] 2023-05-12 09:16
Sorry for bumping up the isssue, but just encountering it I think I found an answer. It seems to be yet another duplicate of:
https://github.com/pulumi/pulumi-azure-native/issues/1487

My error was:
My error was:
Diagnostics:
  azure-native:network:SecurityRule (myNSGRuleName):
    error: cannot check existence of resource '/subscriptions/{mysubscriptionid}/resourceGroups//providers/Microsoft.Network/networkSecurityGroups/{myNSGName}/securityRules/myNSGRuleName': status code 400, {"error":{"code":"InvalidApiVersionParameter","message":"The api-version '2020-11-01' is invalid. The supported versions are '2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."}}

The actual problem was that I didn't provide a resourcegroup name property in call for azure-native.network.SecurityRule creation. It was a dead giveway just looking at the url: /subscriptions/{mysubscriptionid}/resourceGroups//providers/Microsoft.Network/networkSecurityGroups/{myNSGName}/securityRules/myNSGRuleName - especially "/resourceGroups//" the doubled // part.

This error is returned not just if resourcegroup ID is provided instead of name, but also if resourcegroup name is not provided at all.

**Comment by danielrbradley** [comment] 2023-05-12 09:21
Great thanks for reporting back @NNG9y1PQdXl 

I'll close this issue as a duplicate of #2213

**Closed by danielrbradley** 2023-05-12 09:21 UTC
Labels: kind/bug, resolution/duplicate, upstream/service
