### ISSUE TITLE
Duplicate of "Example Usage" in Subnet Documentation

### ISSUE THREAD

**Issue by Cvaniak** [pulumi/pulumi-azure-native#2331] opened 2022-09-22 15:16 UTC
## Overview
In Subnet documentation [themes/default/content/registry/packages/azure-native/api-docs/network/subnet/_index.md](https://www.pulumi.com/registry/packages/azure-native/api-docs/network/subnet/) both _"Create subnet"_ and _"Create subnet with delegation"_ shares same example code (in all languages).
## Expected
_"Create subnet with delegation"_  should contain another code where would be implemented delegation.

**Comment by mikhailshilkov** [comment] 2023-08-06 10:35
Closing as a dupe of https://github.com/pulumi/pulumi-azure-native/issues/2490

**Closed by mikhailshilkov** 2023-08-06 10:35 UTC
Labels: kind/bug, resolution/duplicate, area/docs
