### ISSUE TITLE
Unable to retrieve API keys for a Function App using ListWebAppFunctionKeysArgs

### ISSUE THREAD

**Issue by bizmonger** [pulumi/pulumi-azure-native#2160] opened 2022-12-29 19:35 UTC
### What happened?

```
  var json = await result.Content.ReadAsStringAsync();
  var root = JsonConvert.DeserializeObject<JsonSupport.AzureFunctionItems.Root>(json);
  var items = root.value.Select(async v => {

      var data = await ListWebAppFunctionKeys.InvokeAsync(new ListWebAppFunctionKeysArgs {
          Name = appName,
          FunctionName = v.properties.name,
          ResourceGroupName = resourceGroupName
      });

      return data.Properties; // Property values are null
  });
```

![image](https://user-images.githubusercontent.com/11041788/210003233-82a56582-a472-4f7e-9b4f-1db6cadcda20.png)

### Client
```
public static Output<Dictionary<string, string>?> Get(string resourceGroupName, FunctionApp functionApp)
    {
        var output =
            Output.Tuple(functionApp.Name, functionApp.Name)
                  .Apply(async tuple => {

                      var current        = Pulumi.Azure.Core.GetClientConfig.InvokeAsync().Result;
                      var subscriptionId = current.SubscriptionId;
                      var appName        = tuple.Item1;

                      var httpClient = new HttpClient();
                      httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", AuthToken.Value);

                      var url    = $"https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/sites/{appName}/functions?api-version=2022-03-01";
                      var result = await httpClient.GetAsync(url);

                      if (!result.IsSuccessStatusCode) throw new Exception($"Error: Failed to retrive Azure function names from {appName}");

                      var json = await result.Content.ReadAsStringAsync();
                      var root = JsonConvert.DeserializeObject<JsonSupport.AzureFunctionItems.Root>(json);
                      var items = root.value.Select(async v => {

                          var data = await ListWebAppFunctionKeys.InvokeAsync(new ListWebAppFunctionKeysArgs {
                              Name = appName,
                              FunctionName = v.properties.name,
                              ResourceGroupName = resourceGroupName
                          });

                          return data.Properties;
                      });
                      
                      var data = items.SelectMany(v => v.Result).ToList();
                      return new Dictionary<string, string>(data);
                  });

        return output;
    }
```

### JSON Support
```
namespace JsonSupport.AzureFunctionItems;

// Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(myJsonResponse);
public class Binding
{
    public string type { get; set; }
    public List<string> methods { get; set; }
    public string authLevel { get; set; }
    public string name { get; set; }
}

public class Config
{
    public string generatedBy { get; set; }
    public string configurationSource { get; set; }
    public List<Binding> bindings { get; set; }
    public bool disabled { get; set; }
    public string scriptFile { get; set; }
    public string entryPoint { get; set; }
}

public class Properties
{
    public string name { get; set; }
    public object function_app_id { get; set; }
    public string script_root_path_href { get; set; }
    public string script_href { get; set; }
    public string config_href { get; set; }
    public object test_data_href { get; set; }
    public string secrets_file_href { get; set; }
    public string href { get; set; }
    public Config config { get; set; }
    public object files { get; set; }
    public string test_data { get; set; }
    public string invoke_url_template { get; set; }
    public object language { get; set; }
    public bool isDisabled { get; set; }
}

public class Root
{
    public List<Value> value { get; set; }
    public object nextLink { get; set; }
    public object id { get; set; }
}

public class Value
{
    public string id { get; set; }
    public string name { get; set; }
    public string type { get; set; }
    public string location { get; set; }
    public Properties properties { get; set; }
}
```

### Expected Behavior

I expected the property values of the result to not be null.

### Actual Behavior

The property values on the result are set to null:
![image](https://user-images.githubusercontent.com/11041788/210003723-b22288cd-d306-4625-ba59-95a60b187586.png)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment] 2023-01-05 19:06
Hi @bizmonger, thank you for the report and sorry for the delay. We'll be looking at this shortly.

**Comment by mikhailshilkov** [comment] 2023-02-15 12:43
It's a duplicate of #593, please try `ListWebAppHostKeys` as suggested in https://github.com/pulumi/pulumi-azure-native/issues/593#issuecomment-778129186

**Closed by mikhailshilkov** 2023-02-15 12:43 UTC
Labels: kind/bug, resolution/duplicate
