### ISSUE TITLE
dbforpostgresql only supports the legacy 'server' option from 2017 api

### ISSUE THREAD

**Issue by RaceFPV** [pulumi/pulumi-azure-native#1021] opened 2021-07-24 02:53 UTC
The current iteration of dbforpostgresql.Server only supports the original 'standard' server deployment option. This option is slowly being replaced by Azure in favor of 'flexibleServers' which is the more modern cloudsql configuration. Currently the resource doesn't support creating or importing this new type of Postgres server. The other critical component to this is the legacy standard server only supports up to Postgres v11, while the newer version supports upto 13 and is getting frequent version updates.

## Steps to reproduce

1. Attempt to import a flexibleServers dbforpostgresql server
2. 
```
Status=400 Code="NoRegisteredProviderFound" Message="No registered resource provider found for location 'eastus' and API version '2017-12-01' for type 'flexibleServers'.
```

Expected: 
Actual:

**Comment by mikhailshilkov** [comment] 2021-07-24 07:18
Dupe of https://github.com/pulumi/pulumi-azure-native/issues/684

Unfortunately, ARM still calls those "servers" but you need to use a specific preview API version:

```
import * as dbforpostgresqlpreview from "@pulumi/azure-native/dbforpostgresql/v20200214preview";
const flexibleServer = new dbforpostgresqlpreview.Server("main", {
//...
```

**Closed by mikhailshilkov** 2021-07-24 07:18 UTC
Labels: kind/bug, resolution/duplicate
