### ISSUE TITLE
Type aliases missing to support non-destructive switch between API versions

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi-azure-native#2135] opened 2022-12-15 15:44 UTC
### What happened?

Pulumi wants to recreate a postgresql server when switching between API versions.

### Steps to reproduce

* Create an `azure-native:dbforpostgresql:Server`.
* Switch to a preview version `azure-native:dbforpostgresql/v20220308preview:Server`

### Expected Behavior

Switching between API versions and from/to the top level version should not change the actual resource.

### Actual Behavior

Pulumi wants to recreate the PostgreSQL Server because there are type aliases missing in the (Go) SDK:

* The preview resource doesn't have the type alias for the top-level resource version
* The top level resource doesn't have the type aliases for every of the existing preview versions of `Server`

### Output of `pulumi about`

* azure-native v1.89.1

### Additional context

Aliases on top level `Server` resource:

https://github.com/pulumi/pulumi-azure-native-sdk/blob/d9cd02e4f3d2148f36430849241458db9cbedf02/dbforpostgresql/server.go#L76-L83

Aliases on the preview version of `Server`:

https://github.com/pulumi/pulumi-azure-native-sdk/blob/d9cd02e4f3d2148f36430849241458db9cbedf02/dbforpostgresql/v20220308preview/server.go#L92-L114

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment] 2022-12-15 15:49
Workaround, as discussed: customers can add the alias manually via the resource options if they need to upgrade to a new version of the resource.

Internal notes: this could point to an issue with the schema we're generating or an issue with files not being written or committed correctly when generating the SDK.

**Comment by mikhailshilkov** [comment] 2022-12-15 17:21
Believe it or not, I think this are actually _different_ resources. The preview one points to a Flexible Server with ARM URL `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DBforPostgreSQL/flexibleServers/{serverName}`:  https://github.com/Azure/azure-rest-api-specs/blob/55dd4f72d2b2769c1e02f2b952e597f806d40f9a/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/preview/2022-03-08-preview/FlexibleServers.json#L37

while the default resource is a 2017-12-01 API version with a "legacy" server of `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DBforPostgreSQL/servers/{serverName}`: https://github.com/Azure/azure-rest-api-specs/blob/55dd4f72d2b2769c1e02f2b952e597f806d40f9a/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/stable/2017-12-01/postgresql.json#L37

They are different resources in Azure portal and ARM tempates. I don't know if we should alias them.

**Comment by stefanhenseler** [comment] 2022-12-15 18:46
Mh :) That's bad. We are planning to migrate to flexible, but we are not there yet. So I would say the missing alias makes sense then. But, I think the resource name should be flexible server, to avoid confusion.

**Comment by mikhailshilkov** [comment] 2022-12-16 17:29
They call it "Server" in API definitions, e.g. [here](https://github.com/Azure/azure-rest-api-specs/blob/55dd4f72d2b2769c1e02f2b952e597f806d40f9a/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/preview/2022-03-08-preview/FlexibleServers.json#L40-L42) and that's what we use for naming. I _think_ Azure will phase out the old server and make "flexible" the default, maybe that's why they chose this name.

**Comment by stefanhenseler** [comment] 2022-12-16 18:02
Yes indeed I think that's true. We are actually planning on migrating. Just a bit confusing from an end user perspective, but i guess the pulumi behavior is correct.

**Comment by danielrbradley** [comment] 2022-12-16 22:08
Thanks @mikhailshilkov will close as by design.

**Closed** 2022-12-16 22:08 UTC
Labels: kind/bug, resolution/by-design
