### ISSUE TITLE
'Create or Update Web App Slot' failed with Virtual Network Subnet enabled 

### ISSUE THREAD

**Issue by marcin-bebenek-newday** [pulumi/pulumi-azure-native#2196] opened 2023-01-25 14:00 UTC
### What happened?

Creating web app slot with VirtualNetworkSubnetId enabled is failing with InternalServerError error. Error can be seen in activity logs of resource group under which we are creating WebAppSlot.

            

### Steps to reproduce

Crete Function app or App Service Set VirtualNetworkSubnetId. We are setting the same VNET as for WebApp
```
var app = new WebApp(args.NamingArgs.GetFunctionName(), new WebAppArgs
{
    VirtualNetworkSubnetId = args.VirtualNetworkSubnetId!,
    ...

var stagingSlot = new WebAppSlot(args.NamingArgs.GetWebAppSlotName(), new WebAppSlotArgs
{
    VirtualNetworkSubnetId = args.VirtualNetworkSubnetId!,
    ....
```

### Expected Behavior

WebAppSlot is created with VNET enabled. 

### Actual Behavior

Error can be seen in activity logs of resource group under which we are creating WebAppSlot.. Deployment is failing with error
```
"status": {
        "value": "Failed",
        "localizedValue": "Failed"
    },
    "subStatus": {
        "value": "InternalServerError",
        "localizedValue": "Internal Server Error (HTTP Status Code: 500)"
    },
```

![image](https://user-images.githubusercontent.com/113990002/214582794-b2cc914e-e999-4cf2-9226-2ad949a9dafe.png)

you can see that later deplooyemnt where we have removed VirtualNetworkSubnetId  from WebAppSlot
```
var app = new WebApp(args.NamingArgs.GetFunctionName(), new WebAppArgs
{
    VirtualNetworkSubnetId = args.VirtualNetworkSubnetId!,
    ...

var stagingSlot = new WebAppSlot(args.NamingArgs.GetWebAppSlotName(), new WebAppSlotArgs
{
   // removed this line VirtualNetworkSubnetId = args.VirtualNetworkSubnetId!,
    ....
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment] 2023-01-27 02:12
Hi @marcin-bebenek-newday , thanks for the detailed report! Unfortunately, a 500 response usually indicates an issue in Azure itself. Indeed, someone else [reported the problem on SO](https://stackoverflow.com/questions/75159668/azure-rest-api-500-internal-server-error-when-creating-a-app-service-slot-in-a-v), without using Pulumi.

Your best bet is probably to report the issue and find a workaround until it's fixed.

**Comment by mikhailshilkov** [comment] 2023-07-28 13:22
I don't feel like this issue is actionable for us. Unfortunately, Azure App Service API is infamously known for returning 500 for anything that it considers a misconfiguration without providing much details. It's likely that every such issue needs to be troubleshooted on the Azure side.

I'll go ahead and close the issue since it's been quite a while since its last activity. Please open a new issue if the problem still persists and provide the details for us to reproduce it. Thank you!

**Closed by mikhailshilkov** 2023-07-28 13:22 UTC
Labels: resolution/no-repro, kind/bug, awaiting-upstream
