### ISSUE TITLE
Function App web.WebAppFunction is not getting created

### ISSUE THREAD

**Issue by zeenmc** [pulumi/pulumi-azure-native#2128] opened 2022-12-12 23:13 UTC
### What happened?

Hello Team,

I am opening case, as I got advise from Pulumi slack channel.

I am trying to create Web App Function (ver 4, python will be used for function) in typescript, and I getting error :
`error: Code="ResourceNotFound" Message="The Resource 'Microsoft.Web/sites/fa-horizon-etl-dev-functionapp' under resource group 'rg-horizon-dev-etl' was not found. For more details please go to [https://aka.ms/ARMResourceNotFoundFix"](https://aka.ms/ARMResourceNotFoundFix%22)`

In my files I am creating:

- Resource group
- Storage account (which will be used to upload function via Azure DevOps)
- AppServicePlan for function
- AppInSights
- WebAppFunction

But only WebAppFunction is missing,and I am not able to figure out why

### Steps to reproduce

```typescript
import * as resources from "@pulumi/azure-native/resources";
import * as insights from "@pulumi/azure-native/insights";
import * as storage from "@pulumi/azure-native/storage";
import * as web from "@pulumi/azure-native/web";

export default function createETLFunction() {

    const etlResourceGroup = new resources.ResourceGroup("rg-sphere-dev-etl", {
        location: "westeurope",
        resourceGroupName: "rg-sphere-dev-etl",
    });
    const etlStorageAccount = new storage.StorageAccount("saspheredevetl", {
        accountName: "saspheredevetl",
        resourceGroupName: etlResourceGroup.name,
        sku: {
            name: storage.SkuName.Standard_LRS,
        },
        kind: storage.Kind.StorageV2,
        accessTier: "Hot",
        enableHttpsTrafficOnly: true,
        minimumTlsVersion: "TLS1_2",
    });

    const appServicePlan = new web.AppServicePlan("plan-sphere-dev-etl", {
        name: "plan-sphere-dev-etl",
        resourceGroupName: etlResourceGroup.name,
        location: etlResourceGroup.location,
        kind: "elastic",
        reserved: true,
        sku: {
            name: "EP1",
            tier: "ElasticPremium",
            size: "EP1",
            family: "EP",
            capacity: 1,
        },
    });

    const etlAppInsights = new insights.Component("ai-sphere-dev-appinsights", {
        resourceName: "ai-sphere-dev-appinsights",
        resourceGroupName: etlResourceGroup.name,
        location: etlResourceGroup.location,
        applicationType: "web",
        flowType: "Bluefield",
        kind: "web",
        requestSource: "rest",
    });

    const etlFunctionApp = new web.WebAppFunction("fa-sphere-etl-dev-functionapp", {
        name: "fa-sphere-etl-dev-functionapp",
        functionName: "data_validation",
        resourceGroupName: etlResourceGroup.name,
        scriptHref: "https://func-sphere-dev-etl.azurewebsites.net/admin/vfs/home/site/wwwroot/data_validation/__init__.py",
        configHref: "https://func-sphere-dev-etl.azurewebsites.net/admin/vfs/home/site/wwwroot/data_validation/function.json",
        testDataHref: "https://func-sphere-dev-etl.azurewebsites.net/admin/vfs/home/data/Functions/sampledata/data_validation.dat",
        href: "https://func-sphere-dev-etl.azurewebsites.net/admin/functions/data_validation",
        scriptRootPathHref: "https://func-spherea-dev-etl.azurewebsites.net/admin/vfs/home/site/wwwroot/data_validation/",
        language: "python",
        config: {
            scriptFile: "__init__.py",
            bindings: [
                {
                    name: "blob",
                    type: "blobTrigger",
                    direction: "in",
                    path: "uploaded-zone/{name}.json",
                    connection: "AzureWebJobsStorage"
                }
            ]
        },
    });
}
```

### Expected Behavior

Function with other resources needs to be created

### Actual Behavior

It is failing with error : 
`error: Code="ResourceNotFound" Message="The Resource 'Microsoft.Web/sites/fa-horizon-etl-dev-functionapp' under resource group 'rg-horizon-dev-etl' was not found. For more details please go to [https://aka.ms/ARMResourceNotFoundFix"](https://aka.ms/ARMResourceNotFoundFix%22)`

### Output of `pulumi about`

We are using pulumi 3.14 with Azure-native

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by bizmonger** [comment] 2022-12-15 03:19
I'm observing a similar issue.
I can create a single function app from a list of one item.
However, I am unable to create multiple function apps from a list of multiple items.

**Comment by squaremo** [comment] 2022-12-16 16:20
This looks like it should work, to my inexpert eye. One thing that sticks out is the `name` field of the Function object, for which the [API ref says "Site name"](https://www.pulumi.com/registry/packages/azure-native/api-docs/web/webappfunction/#name_nodejs). Does that need to refer to another object? I'm just guessing -- this really needs someone more familiar with Azure and the provider to investigate.

**Comment by squaremo** [comment] 2022-12-16 16:21
@bizmonger I'm not sure if you're seeing the same problem. Could you post example code please?

**Comment by bizmonger** [comment] 2022-12-16 17:12
You're right. It was an error on my part.
Thanks.

**Comment by zeenmc** [comment] 2022-12-17 08:12
Hello Team :).

is that mean I messed my config, for name should be fa-sphere-etl-dev-functionapp;azurewebsites.net ?

const etlFunctionApp = new web.WebAppFunction("fa-sphere-etl-dev-functionapp", {
        name: "fa-sphere-etl-dev-functionapp;azurewebsites.net",  <============= like this ?
        functionName: "data_validation",
        resourceGroupName: etlResourceGroup.name,
        scriptHref: "https://func-sphere-dev-etl.azurewebsites.net/admin/vfs/home/site/wwwroot/data_validation/__init__.py",
        configHref: "https://func-sphere-dev-etl.azurewebsites.net/admin/vfs/home/site/wwwroot/data_validation/function.json",
        testDataHref: "https://func-sphere-dev-etl.azurewebsites.net/admin/vfs/home/data/Functions/sampledata/data_validation.dat",
        href: "https://func-sphere-dev-etl.azurewebsites.net/admin/functions/data_validation",
        scriptRootPathHref: "https://func-spherea-dev-etl.azurewebsites.net/admin/vfs/home/site/wwwroot/data_validation/",
        language: "python",
        config: {
            scriptFile: "__init__.py",
            bindings: [
                {
                    name: "blob",
                    type: "blobTrigger",
                    direction: "in",
                    path: "uploaded-zone/{name}.json",
                    connection: "AzureWebJobsStorage"
                }
            ]
        },

**Comment by mikhailshilkov** [comment] 2023-02-15 12:57
@zeenmc You need to create a `web.WebApp` resource, and then pass its name to `web.WebAppFunction`, e.g.

```
const app = new web.WebApp("myapp", { ... });

const etlFunctionApp = new web.WebAppFunction("fa-sphere-etl-dev-functionapp", {
  name: app.name,
  functionName: "data_validation",
...
```

Since @bizmonger confirmed it worked for them, I'll close the issue.

**Closed by mikhailshilkov** 2023-02-15 12:57 UTC
Labels: kind/bug, resolution/by-design

**Comment by squaremo** [comment] 2023-02-15 13:01
> Since @bizmonger confirmed it worked for them

I do not see that; what I see is that I questioned whether it was the same problem, and the response confirmed it was not the same problem.

**Comment by mikhailshilkov** [comment] 2023-02-15 13:17
Ah, I read it differently.

Anyway, based on the originally posted error and code, I'm fairly convinced the `WebApp` resource is missing and causing the error.
