### ISSUE TITLE
Creating PrivateDnsZoneGroup is failing with "Cannot create more than one private dns zone groups in the private endpoint"

### ISSUE THREAD

**Issue by tap1992** [pulumi/pulumi-azure-native#2179] opened 2023-01-18 10:32 UTC
### What happened?

Using C# with Azure Native package 1.86.0 we are getting the below error when trying to create a PrivateDnsZoneGroup on an existing PrivateEndpoint (also created by Pulumi).

I can also create the PrivateDnsZoneGroup manually via the azure portal successfully with no issues.

As shown from screenshot below, there is no existing PrivateDnsZoneGroup:

![image](https://user-images.githubusercontent.com/75792610/213149164-8cdb7653-fc17-42ff-854c-74d00a3d6827.png)

### Steps to reproduce

Attempt to create a PrivateDnsZoneGroup via Pulumi Azure Native 1.86.0 with C#. The code snippet we are using is as below:

```
_ = new Network.PrivateDnsZoneGroup($"{endpointName}-zone-group", new Network.PrivateDnsZoneGroupArgs
        {
            ResourceGroupName = $"{stackName}-rg",
            PrivateEndpointName = privateEndpoint.Name,
            Name= $"{endpointName}-zone-group",
            PrivateDnsZoneGroupName = "privatelink.postgres.database.azure.com",
            PrivateDnsZoneConfigs = new Network.Inputs.PrivateDnsZoneConfigArgs
            {
                Name = "privatelink.postgres.database.azure.com",
                PrivateDnsZoneId = $"************"
            }
        },
            new CustomResourceOptions
            {
                DependsOn = privateEndpoint,
            });
```

### Expected Behavior

It would add a PrivateDnsZoneGroup to the existing privateendpoint linked to an existing Private DNS zone.

### Actual Behavior

fails to create with the below error:

error: Code="MoreThanOnePrivateDnsZoneGroupPerPrivateEndpointNotAllowed" Message="Cannot create more than one private dns zone groups in the private endpoint ****. Current private dns zone group count: 2." Details=[]

### Output of `pulumi about`

'dotnet build -nologo OW2.Network.csproj' completed successfully
CLI
Version      3.51.1
Go Version   go1.19.4
Go Compiler  gc

Plugins
NAME          VERSION
azure         5.24.0
azure-native  1.86.0
dotnet        unknown

Host
OS       Microsoft Windows 11 Enterprise
Version  10.0.22621 Build 22621
Arch     x86_64

This project is written in dotnet: executable='C:\Program Files\dotnet\dotnet.exe' version='7.0.102'

Current Stack: uk-shared

TYPE                                               URN
pulumi:pulumi:Stack                                urn:pulumi:uk-shared::OW2.Network::pulumi:pulumi:Stack::OW2.Network-uk-shared
pulumi:providers:azure-native                      urn:pulumi:uk-shared::OW2.Network::pulumi:providers:azure-native::globalSub
pulumi:providers:azure-native                      urn:pulumi:uk-shared::OW2.Network::pulumi:providers:azure-native::default_1_86_0
azure-native:network:PublicIPAddress               urn:pulumi:uk-shared::OW2.Network::azure-native:network:PublicIPAddress::publicIPAddress
azure-native:resources:ResourceGroup               urn:pulumi:uk-shared::OW2.Network::azure-native:resources:ResourceGroup::uk-shared-ourworld-rg
azure-native:managedidentity:UserAssignedIdentity  urn:pulumi:uk-shared::OW2.Network::azure-native:managedidentity:UserAssignedIdentity::uk-shared-ourworld-mi
azure-native:appconfiguration:ConfigurationStore   urn:pulumi:uk-shared::OW2.Network::azure-native:appconfiguration:ConfigurationStore::configurationStore
azure-native:dbforpostgresql:Server                urn:pulumi:uk-shared::OW2.Network::azure-native:dbforpostgresql:Server::gresServer
azure-native:storage:StorageAccount                urn:pulumi:uk-shared::OW2.Network::azure-native:storage:StorageAccount::storageAccount
azure-native:network:PublicIPAddress               urn:pulumi:uk-shared::OW2.Network::azure-native:network:PublicIPAddress::AppGatewayPublicIPAddress
azure-native:keyvault:Vault                        urn:pulumi:uk-shared::OW2.Network::azure-native:keyvault:Vault::uk-shared-ourworld-kv
azure-native:network:WebApplicationFirewallPolicy  urn:pulumi:uk-shared::OW2.Network::azure-native:network:WebApplicationFirewallPolicy::webApplicationFirewallPolicy
azure-native:network:NatGateway                    urn:pulumi:uk-shared::OW2.Network::azure-native:network:NatGateway::natGateway
azure-native:storage:BlobServiceProperties         urn:pulumi:uk-shared::OW2.Network::azure-native:storage:BlobServiceProperties::blobServiceProperties
azure-native:storage:ManagementPolicy              urn:pulumi:uk-shared::OW2.Network::azure-native:storage:ManagementPolicy::storageAccountManagementPolicies
azure-native:network:VirtualNetwork                urn:pulumi:uk-shared::OW2.Network::azure-native:network:VirtualNetwork::uk-shared-ourworld-vnet
azure-native:network:ApplicationGateway            urn:pulumi:uk-shared::OW2.Network::azure-native:network:ApplicationGateway::applicationGateway
azure-native:network:PrivateEndpoint               urn:pulumi:uk-shared::OW2.Network::azure-native:network:PrivateEndpoint::privateEndpointpgsql
pulumi:providers:azure                             urn:pulumi:uk-shared::OW2.Network::pulumi:providers:azure::default_5_24_0
azure-native:network:VirtualNetworkLink            urn:pulumi:uk-shared::OW2.Network::azure-native:network:VirtualNetworkLink::kv-zone-link
azure-native:network:VirtualNetworkPeering         urn:pulumi:uk-shared::OW2.Network::azure-native:network:VirtualNetworkPeering::go-to-uk-shared-peer
azure-native:network:VirtualNetworkLink            urn:pulumi:uk-shared::OW2.Network::azure-native:network:VirtualNetworkLink::acr-zone-link
azure-native:network:VirtualNetworkLink            urn:pulumi:uk-shared::OW2.Network::azure-native:network:VirtualNetworkLink::sql-zone-link
azure-native:network:VirtualNetworkLink            urn:pulumi:uk-shared::OW2.Network::azure-native:network:VirtualNetworkLink::rd-zone-link
azure-native:network:VirtualNetworkLink            urn:pulumi:uk-shared::OW2.Network::azure-native:network:VirtualNetworkLink::pg-zone-link
azure-native:network:VirtualNetworkLink            urn:pulumi:uk-shared::OW2.Network::azure-native:network:VirtualNetworkLink::blb-zone-link
azure-native:network:VirtualNetworkLink            urn:pulumi:uk-shared::OW2.Network::azure-native:network:VirtualNetworkLink::ac-zone-link
azure-native:network:VirtualNetworkLink            urn:pulumi:uk-shared::OW2.Network::azure-native:network:VirtualNetworkLink::as-zone-link
azure-native:network:VirtualNetworkLink            urn:pulumi:uk-shared::OW2.Network::azure-native:network:VirtualNetworkLink::fl-zone-link
azure-native:network:VirtualNetworkLink            urn:pulumi:uk-shared::OW2.Network::azure-native:network:VirtualNetworkLink::es-zone-link
azure-native:network:VirtualNetworkLink            urn:pulumi:uk-shared::OW2.Network::azure-native:network:VirtualNetworkLink::rmq2-zone-link
azure-native:network:VirtualNetworkLink            urn:pulumi:uk-shared::OW2.Network::azure-native:network:VirtualNetworkLink::rmq-zone-link
azure-native:network:VirtualNetworkLink            urn:pulumi:uk-shared::OW2.Network::azure-native:network:VirtualNetworkLink::aks-zone-link
azure-native:network:VirtualNetworkLink            urn:pulumi:uk-shared::OW2.Network::azure-native:network:VirtualNetworkLink::sigr-zone-link
azure-native:network:VirtualNetworkLink            urn:pulumi:uk-shared::OW2.Network::azure-native:network:VirtualNetworkLink::tbl-zone-link
azure-native:network:PrivateEndpoint               urn:pulumi:uk-shared::OW2.Network::azure-native:network:PrivateEndpoint::privateEndpointBlobStorage
azure:postgresql/flexibleServer:FlexibleServer     urn:pulumi:uk-shared::OW2.Network::azure:postgresql/flexibleServer:FlexibleServer::postGresFlexServer
azure-native:network:VirtualNetworkPeering         urn:pulumi:uk-shared::OW2.Network::azure-native:network:VirtualNetworkPeering::uk-shared-to-go-peer
azure-native:network:PrivateEndpoint               urn:pulumi:uk-shared::OW2.Network::azure-native:network:PrivateEndpoint::privateEndpointTableStorage
azure-native:network:PrivateEndpoint               urn:pulumi:uk-shared::OW2.Network::azure-native:network:PrivateEndpoint::privateEndpointKeyVault
pulumi:providers:azure-native                      urn:pulumi:uk-shared::OW2.Network::pulumi:providers:azure-native::default_1_85_0
pulumi:providers:azure-native                      urn:pulumi:uk-shared::OW2.Network::pulumi:providers:azure-native::default_1_64_0

Found no pending operations associated with uk-shared

Organizations

Dependencies:
NAME                VERSION
Newtonsoft.Json     13.0.1
Pulumi              3.46.1
Pulumi.Azure        5.24.0
Pulumi.AzureNative  1.86.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment] 2023-01-20 17:35
Thanks for the details @tap1992

The error details seem to indicate that this is being rejected by the Azure API - which thinks you've already got a private DNS zone. This will require more investigation to understand their API behaviour you're seeing.

A next step on this issue will be to create a complete, standalone reproduction of the issue ready for an engineer to investigate how to resolve the issue because it appears to depend on creating prerequisite resources first before the `PrivateDnsZoneGroup`.

**Comment by mikhailshilkov** [comment] 2023-07-13 12:22
Given no full repro is available, I don't think we can act on this issue. I'll go ahead and close it. Please open a new one with a full repro if the problem persists.

**Closed by mikhailshilkov** 2023-07-13 12:22 UTC
Labels: resolution/wont-fix, kind/bug, needs-repro, awaiting-feedback
