### ISSUE TITLE
PrivateDnsZoneGroup returns InvalidRequestFormat - Cannot parse the request

### ISSUE THREAD

**Issue by trylvis** [pulumi/pulumi-azure-native#2431] opened 2023-05-04 15:51 UTC
### What happened?

When trying to provision network.PrivateDnsZoneGroup, it returns the following:

```
 +   └─ azure-native:network/v20220701:PrivateDnsZoneGroup  myPrivateDnsZoneGroup                           **creating failed**     1 error

Diagnostics:
  azure-native:network/v20220701:PrivateDnsZoneGroup (myPrivateDnsZoneGroup):
    error: Code="InvalidRequestFormat" Message="Cannot parse the request." Details=[]`
```

### Expected Behavior

Would expect to provision the PrivateDnsZoneGroup, or get some more detailed info what is causing the error

### Steps to reproduce

```python
import pulumi
from pulumi_azure_native.network.v20220701 import PrivateDnsZoneGroup
from pulumi_azure_native.network.v20220701 import PrivateDnsZoneConfigArgs

private_dns_zone_group = PrivateDnsZoneGroup(
    "myPrivateDnsZoneGroup",
    name="myPrivateDnsZoneGroup",
    private_dns_zone_configs=[PrivateDnsZoneConfigArgs(
        private_dns_zone_id="/subscriptions/xxx/resourceGroups/yyy/providers/Microsoft.Network/privateDnsZones/privatelink.table.core.windows.net",
    )],
    private_dns_zone_group_name="myPrivateDnsZoneGroup",
    private_endpoint_name="pep_mystorageaccount_table",
    resource_group_name="my_rg_name",

    
    #opts=pulumi.ResourceOptions(depends_on=[private_endpoint])
)
```

### Output of `pulumi about`

```
Current Stack: xxx/storage-account/my_stack

TYPE                                            URN
xx

Found no pending operations associated with xx/my_stack

Backend        
x

Dependencies:
NAME                 VERSION
pip                  23.1.1
pulumi-azure-native  1.100.1
setuptools           67.7.2
wheel                0.40.0

Pulumi locates its logs in /tmp by default
```

### Additional context

The private endpoint is provisioned into a spoke subscription, while the Private DNS Zone is in a hub subscription.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment] 2023-05-04 20:32
Hi @trylvis, sorry you got such an unhelpful error message. On first glance, the only thing that could fail to parse on Azure's side is the `private_dns_zone_id`. Did you copy it from the Azure portal or similar?

You could try to run with [verbose logging](https://www.pulumi.com/docs/support/troubleshooting/#verbose-logging) and attach the output here. There might be additional clues in there.

**Comment by trylvis** [comment] 2023-05-05 10:48
Thanks for the quick response.

Yes, originally it was pulled from a stack-reference, but I also tried to copy it from the Portal to make sure it is correct.
I tried on purpose to use a incorrect private_dns_zone_id, and that resulted in a error message telling me that it was not found, the same for resource group name and private endpoint name.

After some more testing, I found that adding "name" under PrivateDnsZoneConfigArgs solves the issue.

```
import pulumi
from pulumi_azure_native.network.v20220701 import PrivateDnsZoneGroup
from pulumi_azure_native.network.v20220701 import PrivateDnsZoneConfigArgs

private_dns_zone_group = PrivateDnsZoneGroup(
"myPrivateDnsZoneGroup",
name="myPrivateDnsZoneGroup",
private_dns_zone_configs=[PrivateDnsZoneConfigArgs(
private_dns_zone_id="/subscriptions/xxx/resourceGroups/yyy/providers/Microsoft.Network/privateDnsZones/privatelink.table.core.windows.net",
name="privatelink_table_core_windows_net"
)],
private_dns_zone_group_name="myPrivateDnsZoneGroup",
private_endpoint_name="pep_mystorageaccount_table",
resource_group_name="my_rg_name",

#opts=pulumi.ResourceOptions(depends_on=[private_endpoint])
)
```

Not sure if this is something that should have been handled better in Pulumi or if this is something on the Azure end, if I understand the Pulumi doc on this correctly it is an optional parameter.

**Comment by mikhailshilkov** [comment] 2023-09-12 12:58
This is a duplicate of https://github.com/pulumi/pulumi-azure-native/issues/2017

**Closed by mikhailshilkov** 2023-09-12 12:58 UTC
Labels: impact/usability, kind/bug, resolution/duplicate, awaiting-upstream, area/providers
