### ISSUE TITLE
keyvault docs incorrectly use VaultPropertiesResponseArgs instead of VaultPropertiesArgs

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/pulumi-azure-native#2057] opened 2022-10-27 19:03 UTC
### What happened?

When using `properties=keyvault.VaultPropertiesResponseArgs(`
in keyvault, we get the following error:

```
    AttributeError: module 'pulumi_azure_native.keyvault' has no attribute 'VaultPropertiesResponseArgs'
```

### Steps to reproduce

`requirements.txt` contains the following code:
```
pulumi>=3.44.1,<4.0.0
pulumi-azure-native>=1.83.1,<2.0.0
```

`__main__.py` contains the following code:

```
"""An Azure RM Python Pulumi program"""

import pulumi
from pulumi_azure_native import resources,keyvault, authorization
from pulumi import export, Output
from pulumi_azure_native.web.v20210201 import AppServicePlan, SkuDescriptionArgs, WebApp

name = "demo"

# Create an Azure Resource Group
resource_group = resources.ResourceGroup(f'{name}-rg')
export('resource_group_name', resource_group.name)

config = authorization.get_client_config()
export('tenant_id', Output.secret(config.tenant_id))
export('subscription_id', Output.secret(config.subscription_id))


app_service_plan_1 = AppServicePlan(f'{name}-app_service_plan',
    resource_group_name=resource_group.name,
    sku=SkuDescriptionArgs(
        name="S1",
        tier="Standard",
    ),
    opts=pulumi.ResourceOptions(depends_on=[resource_group])
    )

export('app_service_plan_1_name', app_service_plan_1.name)

web_app_1 = WebApp(f'{name}-webapp',
    client_affinity_enabled=False,
    resource_group_name=resource_group.name,
    opts=pulumi.ResourceOptions(depends_on=[app_service_plan_1])
    )

export('web_app_1_name', web_app_1.name)

certificates_var = [
    "Get",
    "List",
    "Update",
    "Create",
    "Import",
    "Delete",
    "Recover",
    "Backup",
    "Restore",
    "ManageContacts",
    "ManageIssuers",
    "GetIssuers",
    "ListIssuers",
    "SetIssuers",
    "DeleteIssuers",
]
secrets_var = [
    "Get",
    "List",
    "Set",
    "Delete",
    "Recover",
    "Backup",
    "Restore",
]
keys_var = [
    "Get",
    "List",
    "Update",
    "Create",
    "Import",
    "Delete",
    "Recover",
    "Backup",
    "Restore",
    "UnwrapKey",
    "Verify",
    "Sign",
]


vault_1 = keyvault.Vault(f'{name}-keyvault',
    properties=keyvault.VaultPropertiesResponseArgs(
    #properties=keyvault.VaultPropertiesArgs(
        access_policies=[{
            "objectId": config.object_id,
            "permissions": keyvault.PermissionsArgs(
                certificates=certificates_var,
                keys=keys_var,
                secrets=secrets_var
            ),
            "tenantId": config.tenant_id,
        }],
        enabled_for_deployment=True,
        enabled_for_disk_encryption=True,
        enabled_for_template_deployment=True,
        sku=keyvault.SkuArgs(
            family="A",
            name=keyvault.SkuName.STANDARD,
        ),
        tenant_id=config.tenant_id,
    ),
    resource_group_name=resource_group.name,
    opts=pulumi.ResourceOptions(depends_on=[resource_group])
)

export('vault_1_name', vault_1.name)
```

Run `pulumi up` and it will error.

### Expected Behavior

The program works.

### Actual Behavior

`pulumi up` shows:

```
View Live: https://app.pulumi.com/shaht/azure-py-keyvault-appserviceplan-webservice/dev/previews/cece88f3-455d-45f7-9188-aa0227b38c65

     Type                                          Name                                             Plan       Info
 +   pulumi:pulumi:Stack                           azure-py-keyvault-appserviceplan-webservice-dev  create     1 error
 +   ├─ azure-native:resources:ResourceGroup       demo-rg                                          create     
 +   ├─ azure-native:web/v20210201:AppServicePlan  demo-app_service_plan                            create     
 +   └─ azure-native:web/v20210201:WebApp          demo-webapp                                      create     
 
Diagnostics:
  pulumi:pulumi:Stack (azure-py-keyvault-appserviceplan-webservice-dev):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/Users/tusharshah/projects/pulumi-home/azure-py-keyvault-appserviceplan-webservice/./__main__.py", line 81, in <module>
        properties=keyvault.VaultPropertiesResponseArgs(
    AttributeError: module 'pulumi_azure_native.keyvault' has no attribute 'VaultPropertiesResponseArgs'
 ```

### Output of `pulumi about`

CLI          
Version      3.44.1
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.83.1
python        unknown

Host     
OS       darwin
Version  11.6.8
Arch     x86_64

This project is written in python: executable='/Users/tusharshah/projects/pulumi-home/azure-py-keyvault-appserviceplan-webservice/venv/bin/python3' version='3.10.6
'

Current Stack: dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/shaht
User           shaht
Organizations  shaht,

Dependencies:
NAME                 VERSION
pip                  22.3.0
pulumi-azure-native  1.83.1
setuptools           65.5.0
wheel                0.37.1

### Additional context

The work around is to do the following with the `keyvault.Vault` resource
Uncomment the `VaultPropertiesArgs` and comment out: `VaultPropertiesResponseArgs` so that the two lines show the following:

```
    #properties=keyvault.VaultPropertiesResponseArgs(
    properties=keyvault.VaultPropertiesArgs(
```

The code will work fine.

The documentation in [keyvault](https://www.pulumi.com/registry/packages/azure-native/api-docs/keyvault/vault/)  for [create a new vault](https://www.pulumi.com/registry/packages/azure-native/api-docs/keyvault/vault/#create-a-new-vault-or-update-an-existing-vault) shows to use:
`keyvault.VaultPropertiesResponseArgs`

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by roothorp** [comment] 2022-10-28 12:47
Hi @tusharshahrs, thanks for the issue. I'm glad you've found a workaround and it does look like this is an error in the docs. I'll add this to our backlog to be prioritized in future iterations. Thanks!

**Comment by thomas11** [comment] 2022-10-31 18:01
similar to #2061

**Comment by mikhailshilkov** [comment] 2023-02-07 13:08
I'll close it as a dupe of [#11219](https://github.com/pulumi/pulumi/issues/11219), it can't be fixed on the Azure Native provider

**Closed by mikhailshilkov** 2023-02-07 13:08 UTC
Labels: impact/usability, kind/bug, resolution/duplicate, area/docs
