### ISSUE TITLE
[v2] Can't create `App.ManagedEnvironment`: "Must contain `properties`"

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi-azure-native#2578] opened 2023-07-14 12:03 UTC
### What happened?

While retrying #2577 with v2.0.0, I bumped into this error. Creating the same (minimal) `App.ManagedEnvironment`, which works in latest v1, I get this as output with v2:

<img width="1028" alt="Screenshot 2023-07-14 at 13 57 34" src="https://github.com/pulumi/pulumi-azure-native/assets/77923/3462fe12-ce15-4bba-8bea-e0ed4ca2b031">

### Expected Behavior

The `App.ManagedEnvironment` should be correctly created.

### Steps to reproduce

* Create a new Pulumi project including Azure Native provider v2.0.0
* Use this sample program:
```csharp
using System.Collections.Generic;
using Pulumi;
using Pulumi.AzureNative.App;
using Pulumi.AzureNative.App.Inputs;
using Pulumi.AzureNative.Network;
using Pulumi.AzureNative.Network.Inputs;
using Pulumi.AzureNative.Resources;

return await Pulumi.Deployment.RunAsync(() =>
{
    var resourceGroup = new ResourceGroup("managedenv");

    var managedEnvironment = new ManagedEnvironment("TestManagedEnv", new ManagedEnvironmentArgs
    {
        ResourceGroupName = resourceGroup.Name,
        EnvironmentName = "TestManagedEnv",
        Location = resourceGroup.Location,
        Tags =
                {
                    { "Environment", "Dev" },
                },
    });

    return new Dictionary<string, object?>
    {
        ["ManagedEnvironmentName"] = managedEnvironment.Name,
    };
});
```
* Run `pulumi up`

### Output of `pulumi about`

```
$ pulumi about
running 'dotnet build -nologo .'
  Determining projects to restore...

  All projects are up-to-date for restore.

  managedenvironment-vnet -> /Users/ringods/Projects/pulumi-customers/managedenvironment-vnet/bin/Debug/net6.0/managedenvironment-vnet.dll


Build succeeded.
    0 Warning(s)

    0 Error(s)

Time Elapsed 00:00:00.49

'dotnet build -nologo .' completed successfully
CLI          
Version      3.75.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  2.0.0
dotnet        unknown

Host     
OS       darwin
Version  13.4.1
Arch     arm64

This project is written in dotnet: executable='/usr/local/share/dotnet/dotnet' version='7.0.203'

Current Stack: team-ce/managedenvironment-vnet/ringo

TYPE                                  URN
pulumi:pulumi:Stack                   urn:pulumi:ringo::managedenvironment-vnet::pulumi:pulumi:Stack::managedenvironment-vnet-ringo
pulumi:providers:azure-native         urn:pulumi:ringo::managedenvironment-vnet::pulumi:providers:azure-native::default_2_0_0
azure-native:resources:ResourceGroup  urn:pulumi:ringo::managedenvironment-vnet::azure-native:resources:ResourceGroup::managedenv


Found no pending operations associated with team-ce/ringo

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/ringods
User           ringods
Organizations  ringods, team-ce, ediri, pulumiverse, demo

Dependencies:
NAME                VERSION
Pulumi              3.55.1
Pulumi.AzureNative  2.0.0

Pulumi locates its logs in /var/folders/yq/10j1hf8s1ks9f23yxrdbbbb40000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment] 2023-07-18 14:04
Thanks for the detailed report, @ringods. The issue looks similar to #2190.

The exact API version that v1.x used, 2022-03-01, is not available in v2 anymore because our schema-tools analysis determined that the new version 2022-10-01 is fully compatible with it. As such, the API version change is unlikely to be the cause of this issue, unless schema-tools is wrong here.

**Comment by thomas11** [comment] 2023-07-18 14:05
For reference, the specs are app/resource-manager/Microsoft.App/stable/2022-03-01/ManagedEnvironments.json and app/resource-manager/Microsoft.App/stable/2022-10-01/ManagedEnvironments.json.

**Comment by mikocot** [comment] 2023-07-21 15:58
@ringods if I understand correctly this is related to the problem we have originally reported (managed environemnt netowrking changes ignored). We've just switched to the Azure Native provider v2.0 today, but even though we specify multiple managed environment properties (among them appLogsConfiguration) the changes still don't seem to be applied -> Pulumi doesn't recognize that the vnet has been specified for the environment and performs no changes nor it reports any error.s

**Comment by thomas11** [comment] 2023-10-26 08:30
This issue is similar to #2190, except there `properties` is correctly marked as required. Since it has no input properties, though, it's elided.

Simply not eliding it is not enough, either, since when it's present and marked as required, our validation complains that it's required but empty. This is based on an attempt to manually edit metadata.json, I could have made a mistake there.

**Closed** 2023-10-27 10:24 UTC
Labels: kind/bug, upstream/open-api, area/providers
