### ISSUE TITLE
Azure v2 ServiceBus NamespaceAuthorizationRule Union issue on Rights block

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/pulumi-azure-native#2616] opened 2023-07-28 15:33 UTC
### What happened?

1.  When using the example for [namespaceauthorizationrule](https://www.pulumi.com/registry/packages/azure-native/api-docs/servicebus/namespaceauthorizationrule/#example-usage),  the following error happens:

```
Cannot implicitly convert type 'string[]' to 'Pulumi.InputList<Pulumi.Union<string, Pulumi.AzureNative.ServiceBus.AccessRights>>' [azure-cs-servicebus-namespaceauthorizationrule]
```
Screen Shot Below in the `Rights` block of code.
![azure-cs-servicebus-namespaceauthorizationrule_union_error](https://github.com/pulumi/pulumi-azure-native/assets/5281839/b07a335f-105e-4139-8554-1067223d6514)

We are passing in strings because that is what we did in azure `v1` for this.

Also note, if we use the example as is, we get the following error in
 in `pulumi about` also:
```
azure-cs-servicebus-namespaceauthorizationrule/Program.cs(35,18): error CS0029: Cannot implicitly convert type 'string[]' to 'Pulumi.InputList<Pulumi.Union<string, Pulumi.AzureNative.ServiceBus.AccessRights>>' [/Users/tusharshah/projects/pulumi-home/azure-cs-servicebus-namespaceauthorizationrule/azure-cs-servicebus-namespaceauthorizationrule.csproj]
```

### Expected Behavior

1. Expect the example code to compile without issues.

### Steps to reproduce

1.  start a new project 
    `mkdir azure-cs-servicebus-namespaceauthorizationrule`
2. `cd azure-cs-servicebus-namespaceauthorizationrule`
3. `pulumi new azure-csharp -y`
4. Replace with this code:
```
using Pulumi;
using Pulumi.AzureNative.Resources;
using Pulumi.AzureNative.Storage;
using Pulumi.AzureNative.Storage.Inputs;
using Pulumi.AzureNative.ServiceBus;
using System.Collections.Generic;

return await Pulumi.Deployment.RunAsync(() =>
{
    // Create an Azure Resource Group
    var resourceGroup = new ResourceGroup("resourceGroup");


    var mynamespace = new Pulumi.AzureNative.ServiceBus.Namespace("namespace", new()
    {
        //NamespaceName = "sdk-Namespace2924",
        ResourceGroupName = resourceGroup.Name,
        Sku = new Pulumi.AzureNative.ServiceBus.Inputs.SBSkuArgs
        {
            Name = "Standard",
            Tier = "Standard",
        },
        Tags = 
        {
            { "tag1", "value1" },
            { "tag2", "value2" },
        },
    });

    var namespaceAuthorizationRule = new Pulumi.AzureNative.ServiceBus.NamespaceAuthorizationRule("namespaceAuthorizationRule", new()
    {
        AuthorizationRuleName = "sdk-AuthRules-1788",
        NamespaceName = mynamespace.Name,
        ResourceGroupName = resourceGroup.Name,
        Rights = new[]
        {
            "Listen",
            "Send",
        },
    });

});
```

### Output of `pulumi about`

`pulumi about`

Results
```
running 'dotnet build -nologo .'
  Determining projects to restore...

  All projects are up-to-date for restore.

  azure-cs-servicebus-namespaceauthorizationrule -> /Users/tusharshah/projects/pulumi-home/azure-cs-servicebus-namespaceauthorizationrule/bin/Debug/net6.0/azure-cs-servicebus-namespaceauthorizationrule.dll


Build succeeded.

    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.03

'dotnet build -nologo .' completed successfully
CLI          
Version      3.76.0
Go Version   go1.20.6
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  2.1.1
dotnet        unknown

Host     
OS       darwin
Version  11.7.8
Arch     x86_64

This project is written in dotnet: executable='/usr/local/bin/dotnet' version='7.0.100'

Current Stack: team-ce/azure-cs-servicebus-namespaceauthorizationrule/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/tushar-pulumi-corp
User           tushar-pulumi-corp
Organizations  tushar-pulumi-corp, team-ce, demo, pulumi

Dependencies:
NAME                VERSION
Pulumi              3.55.1
Pulumi.AzureNative  2.1.1
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by tusharshahrs** [comment] 2023-07-28 16:02
When I replace line #5:
```
using Pulumi.AzureNative.ServiceBus;
```
with: 
```
using Pulumi.AzureNative.ServiceBus.V20221001Preview;
```
OR with
```
using Pulumi.AzureNative.ServiceBus.V20220101Preview;
```

I get the same issue.
```
Cannot implicitly convert type 'string[]' to 'Pulumi.InputList<Pulumi.Union<string, Pulumi.AzureNative.ServiceBus.AccessRights>>' [azure-cs-servicebus-namespaceauthorizationrule]
```

**Comment by tusharshahrs** [comment] 2023-07-28 16:32
My dotnet version:

```
dotnet --list-sdks
7.0.100 [/usr/local/Cellar/dotnet/7.0.100/libexec/sdk]
```

**Comment by danielrbradley** [comment] 2023-07-31 11:42
The example is incorrect due to this bug it dotnet programgen:
- https://github.com/pulumi/pulumi-dotnet/issues/41

The correct code is:

```csharp
        Rights = new[]
        {
            Pulumi.Union<string, AccessRights>.FromT0("Listen"),
            Pulumi.Union<string, AccessRights>.FromT0("Send"),
        },
```

**Comment by lukehoban** [comment] 2023-11-20 21:31
Closing as duplicate of https://github.com/pulumi/pulumi-dotnet/issues/41.

**Closed by lukehoban** 2023-11-20 21:31 UTC
Labels: kind/bug, resolution/duplicate, customer/feedback, area/api-docs
