### ISSUE TITLE
Adding ADB2C tenant fails with error for domain suffix

### ISSUE THREAD

**Issue by Zaragor** [pulumi/pulumi-azure-native#1629] opened 2022-04-06 16:16 UTC
## Hello!
- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
I'm attempting to create an Azure ADB2C tenant, but it doesn't seem to fully create.

I get back a fairly cryptic error messages (listed below). I tried running pulumi up with v=9, and couldn't find much (although I still have the log file if you want it). When I execute it using the [REST API](https://docs.microsoft.com/en-us/rest/api/activedirectory/b2c-tenants/create#properties) I get back a 202 response and querying the location returned I get a Failed status with a 400 status code the error message "The domain suffix specified '' and correct value is 'onmicrosoft.com'." I've also pasted the response from that below for completeness.

Complicating the matter further, it seems to create some sort of something, because when I try to create a resource with the same name in a different location, I get an error message saying I can't do that.

I imagine this is actually an issue with something upstream with the endpoint you hit, but I don't know where to file that bug - if you could point me in the right direction, that would be great.

`step create on urn:pulumi:temp-min::environment::azure-native:azureactivedirectory:B2CTenant::example-web-app-ADB2C failed with an error: resource partially created but read failed autorest/azure: Service returned an error. Status=404 Code="NotFound" Message="Resource with ID '33b84d52-5ab7-4975-80b4-35f034fcc35d/nm-test/bbotnmdevadb2c' does not exist." Target="resource": autorest/azure: Service returned an error. Status=404 Code="NotFound" Message="Resource with ID '33b84d52-5ab7-4975-80b4-35f034fcc35d/nm-test/bbotnmdevadb2c' does not exist." Target="resource"`

```{
    "subscriptionId": <REDACTED>,
    "id": "/subscriptions/<SUBID>/providers/microsoft.azureactivedirectory/operations/af68ac1c-3fc9-49f3-8ce7-8869b4983139",
    "name": "af68ac1c-3fc9-49f3-8ce7-8869b4983139",
    "status": "Failed",
    "startTime": "04/06/2022 15:47:39",
    "endTime": "04/06/2022 15:47:42",
    "error": {
        "code": "BadRequest",
        "message": "The domain suffix specified '' and correct value is 'onmicrosoft.com'.",
        "extendedDetails": {
            "affectsQos": false,
            "statusCode": 400
        }
    },
    "properties": {
        "billingConfig": null,
        "tenantId": null
    }
}```

### Steps to reproduce
<!-- Provide a link to a live example or an unambiguous set of steps to reproduce this bug. Tell us what you expected to happen, and what happened instead. Please include code to reproduce, if relevant. -->

1. Create a template stack that creates an azure ADB2C tenant. I've tried with different names, locations, SKUs and countryCodes, so I don't think the actual values matter - it looks like it affects them all
2. Run `pulumi up`

Expected: An azure tenant to be created, visible in the portal and added to the stack
Actual: An error with NotFound for the resource.

**Comment by jkodroff** [comment] 2022-04-11 20:54
@Zaragor Thanks for submitting this issue. Could you supply us with a minimal code sample that will reproduce the error?

**Comment by TechyTish** [comment] 2022-05-11 10:05
Hi im having the same issue, how did this get resolved?

**Comment by TechyTish** [comment] 2022-05-11 11:12
Managed to resolve it by ensuring the domain name had no uppercase, no special characters
We were using a variable in the domain name and the variable had a string replacement and it wasnt working.

Non Working Code:
``` csharp
string b2cStackName = stackName.Replace("uk-", "");
var AzureB2CTenant = B2CTenant.Create(stackName, b2cStackName);
```

Working Code:
``` csharp
**.stackFile**
string b2cStackName = stackName.Replace("uk-", "");
var AzureB2CTenant = B2CTenant.Create(stackName, b2cStackName);

**.configFile**
public static class B2CTenant
{
    public static AzureNative.AzureActiveDirectory.B2CTenant Create(string stackName, string b2cStackName) =>
            new("AzureB2CTenant", new AzureNative.AzureActiveDirectory.B2CTenantArgs
            {
                Location = "x",
                Properties = new AzureNative.AzureActiveDirectory.Inputs.CreateTenantRequestBodyPropertiesArgs
                {
                    CountryCode = "GB",
                    DisplayName = $"{stackName} B2C Tenant",
                },
                ResourceGroupName = $"{stackName}-ourworld-rg",
                ResourceName = $"xxx{b2cStackName}xxx.onmicrosoft.com",
                Sku = new AzureNative.AzureActiveDirectory.Inputs.B2CResourceSKUArgs
                {
                    Name = AzureNative.AzureActiveDirectory.B2CResourceSKUName.PremiumP1,
                    Tier = AzureNative.AzureActiveDirectory.B2CResourceSKUTier.A0,
                },
                Tags =
                    {
                         { "project", "xxx" },
                         { "deployment", "xxxx" },
                    },
            });
 }
```

**Comment by mikhailshilkov** [comment] 2022-12-22 14:22
This looks like a dupe of #1126

**Closed by mikhailshilkov** 2022-12-22 14:22 UTC
Labels: kind/bug, resolution/duplicate
