### ISSUE TITLE
Fails to create Batch Pool with custom VM image reference id

### ISSUE THREAD

**Issue by davidpg-bimone** [pulumi/pulumi-azure-native#3599] opened 2024-09-27 18:18 UTC
### What happened?

I'm trying to update pulumi-azure-native from 1.104.0 to 2.63.0.
The stack I'm trying to update contains a Batch Pool. The pool uses a custom VM image stored inside a Compute Gallery. The only way to define a custom VM image is to provide the image resource id.

When pulumi up is executed it fails with the following error
```
Error message: 400 Code="InvalidPropertyValue" Message="The value provided for one of the properties in the request body is invalid.
RequestId:38a292c4-0511-4e21-a1f2-306a153ca82b\nTime:2024-09-13T15:11:40.1140071Z" Target="BatchAccount"
Details=[{"code":"PropertyName","message":"version"},
{"code":"PropertyPath","message":"properties.deploymentConfiguration.virtualMachineConfiguration.imageReference.version"},
{"code":"Reason","message":"Specified property version can only have a value when publisher is set."}]
```

### Example

Here is a simplified version of the faulty batch pool.
```
import { batch } from "@pulumi/azure-native";
new batch.Pool(
        "poolname",
        {
            accountName: "accountname",
            resourceGroupName: "groupname",
            poolName: "poolname",
            deploymentConfiguration: {
                virtualMachineConfiguration: {
                    imageReference: {
                        id: "/subscriptions/subid/resourceGroups/networking-group/providers/Microsoft.Compute/galleries/testgallery/images/testimagedef/versions/0.0.1"
                    },
                    nodeAgentSkuId: "batch.node.windows amd64",
                },
            },
        },
    );
```

To create the batch pool a compute gallery with a image definition must be created before hand.

### Output of `pulumi about`

CLI
Version      3.89.0
Go Version   go1.21.1
Go Compiler  gc

Host     
OS       Microsoft Windows 11 Pro
Version  10.0.22631 Build 22631
Arch     x86_64

### Additional context

What we could find out after investigating that issue is that:
- V1 did not have this issue
- V2 always adds the property `version: "latest"` to the `imageReference` object when no version is provided
- The extra property is added by a function named `imageReferenceArgsProvideDefaults`
- Modifying locally the function `imageReferenceArgsProvideDefaults` by removing the default property `version: "latest"` **resolve the issue**
- The default property `version: "latest"` should not be added when the property `id` is present https://www.pulumi.com/registry/packages/azure-native/api-docs/batch/pool/#imagereferenceresponse

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment] 2024-09-30 14:45
Hi @davidpg-bimone, it seems that this is caused by an [erroneous `default` annotation in the upstream API spec](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/batch/resource-manager/Microsoft.Batch/stable/2023-05-01/BatchManagement.json#L4927) that the Pulumi SDK is generated from.

Fortunately, it was fixed in a later API version, from 2024-02-01. You can explicitly import this API version in your program, which should fix your issue:
```ts
import { v20240201 as batch } from "@pulumi/azure-native/batch";
```

**Comment by davidpg-bimone** [comment] 2024-09-30 15:56
Hi @thomas11, it did work perfectly! Thank you for sharing this solution.
As far as I'm concerned the issue is resolved. It can be closed if there is nothing else to do.

**Closed** 2024-10-01 07:04 UTC
Labels: kind/bug, upstream/open-api, resolution/by-design
