### ISSUE TITLE
`VnetConfiguration` on `App.ManagedEnvironment` not applied on actual resource

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi-azure-native#2577] opened 2023-07-14 11:53 UTC
### What happened?

When updating an existing `App.ManagedEnvironment` resource with a `VnetConfiguration` input, the vnet configuration is not applied on the managed environment resource.

### Expected Behavior

The managed environment resource to be updated with the given vnet configuration.

### Steps to reproduce

Code sample used to reproduce the issue:

```csharp
using System.Collections.Generic;
using Pulumi;
using Pulumi.AzureNative.App;
using Pulumi.AzureNative.App.Inputs;
using Pulumi.AzureNative.Network;
using Pulumi.AzureNative.Network.Inputs;
using Pulumi.AzureNative.Resources;

return await Pulumi.Deployment.RunAsync(() =>
{
    var resourceGroupName = "managedenv"; // Provide existing resource group name

    // Assuming the existing resource group is available under the given resourceGroupName
    var resourceGroup = new ResourceGroup(resourceGroupName);

    // Create a virtual network
    // var virtualNetwork = new VirtualNetwork("virtualNetwork", new VirtualNetworkArgs
    // {
    //     ResourceGroupName = resourceGroup.Name,
    //     Location = resourceGroup.Location,
    //     AddressSpace = new AddressSpaceArgs
    //     {
    //         AddressPrefixes =
    //                 {
    //                     "10.0.0.0/16",
    //                 },
    //     },
    // });

    // Create a subnet in the virtual network
    // var subnet = new Subnet("subnet", new Pulumi.AzureNative.Network.SubnetArgs
    // {
    //     ResourceGroupName = resourceGroup.Name,
    //     VirtualNetworkName = virtualNetwork.Name,
    //     AddressPrefix = "10.0.0.0/22",
    // });

    var managedEnvironment = new ManagedEnvironment("TestManagedEnv", new ManagedEnvironmentArgs
    {
        ResourceGroupName = resourceGroup.Name,
        EnvironmentName = "TestManagedEnv",
        Location = resourceGroup.Location,
        // VnetConfiguration = new Pulumi.AzureNative.App.Inputs.VnetConfigurationArgs
        // {
        //     InfrastructureSubnetId = subnet.Id,
        // },
        Tags =
                {
                    { "Environment", "Dev" },
                },
    });

    return new Dictionary<string, object?>
    {
        ["ManagedEnvironmentName"] = managedEnvironment.Name,
    };
});
```

* run `pulumi up` with the given example. The `ManagedEnvironment` is first set up without `VnetConfiguration`. Azure resource JSON view of the `ManagedEnvironment:
```json
{
    "id": "/subscriptions/<our test subscription>/resourceGroups/managedenv63f42613/providers/Microsoft.App/managedEnvironments/TestManagedEnv",
    "name": "TestManagedEnv",
    "type": "Microsoft.App/managedEnvironments",
    "location": "West Europe",
    "tags": {
        "Environment": "Dev"
    },
    "systemData": {
        "createdBy": "<my email>",
        "createdByType": "User",
        "createdAt": "2023-07-14T10:41:30.1672379",
        "lastModifiedBy": "<my email>",
        "lastModifiedByType": "User",
        "lastModifiedAt": "2023-07-14T10:41:30.1672379"
    },
    "properties": {
        "provisioningState": "Succeeded",
        "daprAIInstrumentationKey": null,
        "daprAIConnectionString": null,
        "vnetConfiguration": null,
        "defaultDomain": "kindflower-db285dbc.westeurope.azurecontainerapps.io",
        "staticIp": "52.137.58.63",
        "appLogsConfiguration": {
            "destination": null,
            "logAnalyticsConfiguration": null
        },
        "zoneRedundant": false,
        "kedaConfiguration": {
            "version": "2.10.0"
        },
        "daprConfiguration": {
            "version": "1.10.8"
        },
        "eventStreamEndpoint": "https://westeurope.azurecontainerapps.dev/subscriptions/<our test subscription>/resourceGroups/managedenv63f42613/managedEnvironments/TestManagedEnv/eventstream",
        "customDomainConfiguration": {
            "customDomainVerificationId": "A3C07EA0CA915FF776DB1D35222A030342D323D3C81A31711C8140114337F716",
            "dnsSuffix": null,
            "certificateValue": null,
            "certificatePassword": null,
            "thumbprint": null,
            "subjectName": null,
            "expirationDate": null
        },
        "workloadProfiles": null,
        "firstPartyConfiguration": null,
        "infrastructureResourceGroup": null
    }
}
```
* uncomment the `virtualNetwork`, `subnet` resource blocks
* uncomment the `VnetConfiguration` block in the `managedEnvironment` resource.
* run `pulumi up` again. Azure resource JSON view of `ManagedEnvironment` after the update:
```json
{
    "id": "/subscriptions/<our test subscription>/resourceGroups/managedenv63f42613/providers/Microsoft.App/managedEnvironments/TestManagedEnv",
    "name": "TestManagedEnv",
    "type": "Microsoft.App/managedEnvironments",
    "location": "West Europe",
    "tags": {
        "Environment": "Dev"
    },
    "systemData": {
        "createdBy": "<my email>",
        "createdByType": "User",
        "createdAt": "2023-07-14T10:41:30.1672379",
        "lastModifiedBy": "<my email>",
        "lastModifiedByType": "User",
        "lastModifiedAt": "2023-07-14T10:51:12.6913415"
    },
    "properties": {
        "provisioningState": "Succeeded",
        "daprAIInstrumentationKey": null,
        "daprAIConnectionString": null,
        "vnetConfiguration": null,
        "defaultDomain": "kindflower-db285dbc.westeurope.azurecontainerapps.io",
        "staticIp": "52.137.58.63",
        "appLogsConfiguration": {
            "destination": null,
            "logAnalyticsConfiguration": null
        },
        "zoneRedundant": false,
        "kedaConfiguration": {
            "version": "2.10.0"
        },
        "daprConfiguration": {
            "version": "1.10.8"
        },
        "eventStreamEndpoint": "https://westeurope.azurecontainerapps.dev/subscriptions/<our test subscription>/resourceGroups/managedenv63f42613/managedEnvironments/TestManagedEnv/eventstream",
        "customDomainConfiguration": {
            "customDomainVerificationId": "A3C07EA0CA915FF776DB1D35222A030342D323D3C81A31711C8140114337F716",
            "dnsSuffix": null,
            "certificateValue": null,
            "certificatePassword": null,
            "thumbprint": null,
            "subjectName": null,
            "expirationDate": null
        },
        "workloadProfiles": null,
        "firstPartyConfiguration": null,
        "infrastructureResourceGroup": null
    }
}
```

## Preview
<img width="1114" alt="vnetconfig-preview" src="https://github.com/pulumi/pulumi-azure-native/assets/77923/a142c9b3-8c66-4a15-8175-8e802d633bf3">

## Update
<img width="847" alt="vnetconfig-updated" src="https://github.com/pulumi/pulumi-azure-native/assets/77923/72f7feb1-0dd9-453b-b9ee-e443abb55a1b">

### Output of `pulumi about`

running 'dotnet build -nologo .'
  Determining projects to restore...

  All projects are up-to-date for restore.

  managedenvironment-vnet -> /Users/ringods/Projects/pulumi-customers/managedenvironment-vnet/bin/Debug/net6.0/managedenvironment-vnet.dll

Build succeeded.

    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.61

'dotnet build -nologo .' completed successfully
CLI          
Version      3.75.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.104.0
dotnet        unknown

Host     
OS       darwin
Version  13.4.1
Arch     arm64

This project is written in dotnet: executable='/usr/local/share/dotnet/dotnet' version='7.0.203'

Current Stack: team-ce/managedenvironment-vnet/ringo

Found no resources associated with team-ce/ringo

Found no pending operations associated with team-ce/ringo

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/ringods
User           ringods
Organizations  ringods, team-ce, ediri, pulumiverse, demo

Dependencies:
NAME                VERSION
Pulumi              3.55.1
Pulumi.AzureNative  1.104.0

Pulumi locates its logs in /var/folders/yq/10j1hf8s1ks9f23yxrdbbbb40000gn/T/ by default

### Additional context

Retried with Azure Native v2, but bumped into #2578

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment] 2023-07-20 15:22
With the workaround @danielrbradley provided in #2578, I was able to test this on azure native v2, but got the same result. Increasing the log verbosity, we see that the provider sends the `vnetConfiguration` to Azure.

```
{"location":"westus2","properties":{"appLogsConfiguration":{},"vnetConfiguration":{"infrastructureSubnetId":"/subscriptions/SUB/resourceGroups/managedenve5742eb2/providers/Microsoft.Network/virtualNetworks/virtualNetworkea8dc5e8/subnets/subnet"}},"tags":{"Environment":"Dev"}}
===================================================== HTTP Request End PUT https://management.azure.com/subscriptions/SUB/resourceGroups/managedenve5742eb2/providers/Microsoft.App/managedEnvironments/TestManagedEnv?api-version=2022-10-01
```

The immediately following GET then returns it as null.
```
{"id":"/subscriptions/SUB/resourceGroups/managedenve5742eb2/providers/Microsoft.App/managedEnvironments/TestManagedEnv","name":"TestManagedEnv","type":"Microsoft.App/managedEnvironments","location":"West US 2","tags":{"Environment":"Dev"},"systemData":{"createdBy":"tkappler@pulumi.com","createdByType":"User","createdAt":"2023-07-20T13:38:12.2119641","lastModifiedBy":"tkappler@pulumi.com","lastModifiedByType":"User","lastModifiedAt":"2023-07-20T15:16:04.8017208"},"properties":{"provisioningState":"Succeeded","daprAIInstrumentationKey":null,"daprAIConnectionString":null,"vnetConfiguration":null,"defaultDomain":"whitesky-e84fb46d.westus2.azurecontainerapps.io","staticIp":"40.64.72.24","appLogsConfiguration":{"destination":null,"logAnalyticsConfiguration":null},"zoneRedundant":false,"eventStreamEndpoint":"https://westus2.azurecontainerapps.dev/subscriptions/SUB/resourceGroups/managedenve5742eb2/managedEnvironments/TestManagedEnv/eventstream","customDomainConfiguration":{"customDomainVerificationId":"...","dnsSuffix":null,"certificateValue":null,"certificatePassword":null,"thumbprint":null,"subjectName":null,"expirationDate":null}}}
===================================================== HTTP Response End GET https://management.azure.com/subscriptions/SUB/resourceGroups/managedenve5742eb2/providers/Microsoft.App/managedEnvironments/TestManagedEnv?api-version=2022-10-01
```

Not sure why, but it seems like an issue on Azure's side. @ringods did you try provisioning an environment with the same configuration outside of Pulumi?

**Comment by mikocot** [comment] 2023-07-21 16:10
Indeed, I believe this issue was originally reported by us. We've just switched to the Azure Native provider v2.0 today, but even though we specify multiple managed environment properties, including appLogsConfiguration, which  have been mentioned as a workaround, the changes are still not applied -> Pulumi doesn't recognize that the vnet has been specified for the environment and performs no changes, nor it reports any errors.

We expect the vnetConfiguration to show up like in this environment, but even though we specify it in the code, this environment doesnt seem to notice it.
![image](https://github.com/pulumi/pulumi-azure-native/assets/9884950/2cc3db51-e819-4413-93e9-542e83a4c722)

**Comment by mikocot** [comment] 2023-07-21 19:09
One more thing, since that vnetConfiguration is also not visible on pulumi side I don't think we can blame Azure for it, right? It would be different if Pulumi indicated thst this vnetConfiguration is present for managed environment but Azure ignored it, but it's not the case.

**Comment by danielrbradley** [comment] 2023-08-02 13:06
Yes, I can confirm having run this with a debugger attached that we do send the vnetConfiguration correctly to the Azure API but it appears to be ignored by them on input as the response has the vnetConfiguration property, but it doesn't have a value.

We then don't indicate that another update is required because we compare the old and new inputs and find nothing has changed. The outputs show what Azure responded with - which which doesn't include the property. With most cloud providers the output can vary from the input for example because it might include additional properties such as an IP address. Therefore we assume if our inputs were accepted, then they should have been applied.

In addition I've also tried using the latest preview that Azure reference in the portal and we still get the same behaviour. This needs to be raised as a ticket with Azure.

**Comment by mikocot** [comment] 2023-08-03 08:41
I see, so the resource configuration in pulumi app is not really wha you're sending to azure, but what azure is returning? that's a bt unexpected.

Anyway, do can we count that you're going to creat this issue with azure and follow up on it?

**Comment by danielrbradley** [comment] 2023-08-03 13:21
What you pass into the constructor is sent to Azure. The properties on the class are the outputs returned _from_ Azure. This allows for filling in of default values etc. These are generally expected to align and is likely a bug if their service returns a different value to what you passed in.

I have already filed this ticket with Azure and will await their response.

**Comment by serpentfabric** [comment] 2023-09-08 13:56
would setting `replaceOnChanges` for `properties.vnetConfiguration` suffice as a workaround until there's a fix?

**Comment by danielrbradley** [comment] 2023-09-26 15:29
Following a call with Microsoft we've established that the `vnetConfiguration` is not updatable, once created. This behavious is [documented in their "learn" article on Networking in Azure Container Apps environment (in the menu as Networking, ingress, and network security / Architecture overview)](https://learn.microsoft.com/en-us/azure/container-apps/networking?tabs=azure-cli)  

The current Azure service behaviour is, when attempting to change the `vnetConfiguration` the change will just be ignored. As @serpentfabric suggested–the workaround it to just [set `replaceOnChanges`](https://www.pulumi.com/docs/concepts/options/replaceonchanges/) for `vnetConfiguration` to force recreation if the `vnetConfiguration` is updated.

Microsoft are working to fix:
1. The specification to indicate that the `vnetConfiguration` is available only on initial creation and when reading, but not on update.
1. The service to not accept requests where the `vnetConfiguration` is being updated.

On reviewing the specifications again after the call, this might be very challenging to implement correctly because both the create and update are done via the same REST API method (`PUT`) and therefore can't have differing permitted properties.

We will update this issue once we recieve further information.

**Comment by mikocot** [comment] 2023-10-09 08:37
Cool, does it need any changes on your side, or since MS has fixed it it will work out of box now?

**Comment by danielrbradley** [comment] 2023-10-09 15:02
With the current change on Microsoft's side, it should now fail with a meaningful error message rather than silently drop the updated values. We've got a couple of issues to address before we can accurately automatically mark these properties for automatic re-creation, so this will require setting `replaceOnChanges` for the time being.

**Comment by danielrbradley** [comment] 2023-11-14 15:06
I've just re-tested this again and it appears it's only partially fixed in Azure. We now get an error message if trying to update a ManagedEnvironment `vnetConfiguration` from one subnet to another subnet: `Infrastructure subnet Id can not be changed after environment creation`.
- We still get no error when adding a `vnetConfiguration` when it was initially created without one 😞 
- We get no error message when removing `vnetConfiguration`. This is somewhat expected because Azure often assume that a property not being present in a PUT request means "don't change" rather than remove.

Manually setting `replaceOnChanges` to include `vnetConfiguration` still results in the correct behaviour.

In order to automatically derrive the correct behavior without setting `replaceOnChanges`, we need to:
1. https://github.com/pulumi/pulumi-azure-native/issues/2782 however, this is blocked on:
2. https://github.com/pulumi/pulumi-azure-native/issues/2781

**Comment by mikocot** [comment] 2023-11-20 12:32
Thanks @danielrbradley, that makes sense, I think it's fair to require explicit replaceOnChange on a rather destructive change. But the error messages ideally would be there, and also I think it would be worth mentioning it in pulumi docs.

**Comment by danielrbradley** [comment] 2023-11-21 13:08
The previous ticket with Azure was closed out so I can't follow up. I expect Azure is not actively working on this again.

**Comment by thomas11** [comment] 2023-12-21 09:05
#2968 implements prerequisite #2781 which should bring us a lot closer to resolving this.

What's missing, as far as I can see so far, is propagating `ReplaceOnChanges` to the right place. If we simply relax the `!isType` condition [here](https://github.com/pulumi/pulumi-azure-native/blob/master/provider/pkg/gen/properties.go#L386), the properties of `app:VnetConfiguration` get annotated with `forceNew` but `app:ManagedEnvironment.vnetConfiguration` does not.

**Comment by thomas11** [comment] 2024-01-04 17:40
This is now implemented but needs to be explicitly enabled by setting the environment variable `PULUMI_FORCE_NEW_FROM_SUBTYPES` to `true`, as a soft rollout since unexpected resource replacements are very disruptive. We're planning to make this behavior the default in the future.

**Comment by thomas11** [comment] 2024-01-10 14:11
#3006 tracks enabling the new behavior by default.

**Closed by thomas11** 2024-01-10 14:11 UTC
Labels: kind/bug, resolution/fixed, area/providers

**Comment by mikocot** [comment] 2024-01-16 11:08
ok, thanks, that seems reasonable ;)
