### ISSUE TITLE
Folding multiple container properties isn't safe against name collisions 

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi-azure-native#126] opened 2020-08-21 00:10 UTC
For instance, see https://github.com/Azure/azure-rest-api-specs/blob/1038b0c60aa7f43eda8af28327d6c79980ce0409/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2018-01-01/apimapis.json#L660 where we end up with two `apiId` fields - one from `#/parameters/ApiIdParameter` and one from `"#/definitions/ApiReleaseContract"`

**Comment by mikhailshilkov** [comment] 2021-03-04 16:22
I'll close it as "by design" for now, let's wait until we hit a real-life limitation with it

**Closed by mikhailshilkov** 2021-03-04 16:22 UTC
Labels: resolution/wont-fix
