### ISSUE TITLE
Issue with vnet - nsg - subnet creation (race condition?)

### ISSUE THREAD

**Issue by headconnect** [pulumi/pulumi-azure-native#699] opened 2021-03-29 12:16 UTC
When provisioning a network with one vnet, four subnets and three nsg's, two (or sometimes one) of the subnets will fail to provision with the error code  "AnotherOperationInProgress" and a link to the status operation URI. 

This is resolved by simply running `pulumi up` again - as one simply has to wait for whatever operation is ongoing to finish (which it does, successfully). 

## Expected behavior

Pulumi should handle cases in provisioning has to wait due to ongoing processes so that it does not simply fail for want of waiting long enough.

## Current behavior

When provisioning a vnet + nsg's + subnet connected to both newly provisioned vnet AND nsg - some of the subnets fail to create the first time with the following error:
```
azure-native:network:Subnet (zone8-node1234):
    error: autorest/azure: Service returned an error. Status=<nil> Code="AnotherOperationInProgress" Message="Another operation on this or dependent resource is in progress. To retrieve status of the operation use uri: (management-status-uri)
```

Looking deeper with the command:
`pulumi up -y --suppress-outputs -v=9 --debug --logflow --logtostderr 1> pulumi-up-just-network-again.log 2>&1`
reveals that internally pulumi attempts the creation 3 times before finally giving up - each time receiving the same response as noted above.

Once pulumi has errored out, I can run `pulumi up` again and it will successfully provision those subnets, presumingly because a) the operations in progress have completed by that time and/or b) that the operations in progress will have completed by the time the third retry has been performed.

## Steps to reproduce

Link to branch for reproduction of issue:
https://github.com/headconnect/pulumi-bug-reproducer/tree/issue/azure-native-699-subnet-creation

## Context (Environment)

This issue prevents me from predictably creating new environments programmatically as it will dependably fail the first time I provision.  This in turn makes it difficult to allow new environment creation through CI/CD as it will fail unnecessarily.

**Comment by xMilotas** [comment] 2021-03-29 16:11
Hey, we ran into the same issue. This is actually a "intended" behaviour that also happens with the ARM templates. 
See this[ SO post](https://stackoverflow.com/questions/62424299/anotheroperationinprogress-when-deploying-multiple-azure-virtual-networks-and-su ) as a reference. 

We fixed it, by depending on the previously created subnet. 

This leads to them being created synchronously. 
You will also need to depend on the subnets in any of the resources that use them, as they cannot be provisioned as long as any operation on the subnets is still ongoing.

**Comment by headconnect** [comment] 2021-03-31 07:53
Yup, adding a dependency between subnets to the previously declared subnet resolved the issue for me - and the provisioning went really quickly as well even though the subnets were created in sequence.  

I would have thought that whatever issue was causing the "AnotherOperationInProgress" issue was a bit more long-running since it did seem to resolve on the next pass - but I'm guessing this illustrates that this is indeed a race condition on parallel updates to subnet resources.

I've now got a bit of a hacky code in place to handle it, see diff at: https://github.com/headconnect/pulumi-bug-reproducer/commit/47a3f6d288f3f6c7bb9a623a7d8b1349f987715d#diff-e1440d0974e6cb61ca627021e8bfaa4941c2af3ad8486602dd52c9212a3408d2

**Comment by mikhailshilkov** [comment] 2024-02-06 20:56
I think I'll close this one as a dupe of https://github.com/pulumi/pulumi-azure-native/issues/903 which has more comments and upvotes, let's track there

**Closed by mikhailshilkov** 2024-02-06 20:56 UTC
Labels: kind/bug, resolution/duplicate, upstream/service
