### ISSUE TITLE
Provision Feature Flags in Azure AppConfiguration

### ISSUE THREAD

**Issue by shahabganji** [pulumi/pulumi-azure-native#1377] opened 2021-12-19 08:54 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I am using `ConfigurationStore` to provision an Azure AppConfiguration, I used `KeyValueStore` for provisioning key/value pairs and also with the help of `ContentType` property described in [here](https://github.com/pulumi/pulumi-azure-native/issues/1034#issuecomment-890333787) to add a **Key Vault Reference**.

I was using `Pulumi.Azure` library first to provisions feature flags into the Azure AppConfiguration, but I was getting `403`, while my user has all the required permissions needed because `az appconfig` commands all running successfully. The error after running `pulumi up` was the following:

```bash
  azure:appconfiguration:ConfigurationFeature (MyFeatureFlag):
    error: 1 error occurred:
        * got http status code 403 while checking for key's ".appconfig.featureflag/MyFeatureFlag" existence: appconfiguration.BaseClient#GetKeyValue: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: error response cannot be parsed: "" error: EOF: got http status code 403 while checking for key's ".appconfig.featureflag/MyFeatureFlag" existence: appconfiguration.BaseClient#GetKeyValue: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: error response cannot be parsed: "" error: EOF
```

and the following code which was with `Pulumi.Azure@4.31.0` is the snippet for running it: 

```cs
            var appConfig = new ConfigurationStore("conf-sample", new ConfigurationStoreArgs
            {
                ResourceGroupName = resourceGroup.Name,
                Sku = "standard"
            });

            _ = new ConfigurationFeature("MyFeatureFlag", new ConfigurationFeatureArgs
            {
               Name = "MyFeatureFlag",
               ConfigurationStoreId = appConfig.Id,
               Enabled = false,
            });
```

then I changed it with `Pulumi.AzureNative@1.50.0` with the following code: 

```cs
          _ = new Pulumi.AzureNative.AppConfiguration.KeyValue("MyFeatureFlag",
                new Pulumi.AzureNative.AppConfiguration.KeyValueArgs
                {
                    ResourceGroupName = resourceGroup.Name,
                    ConfigStoreName = appConfig.Name,
                    KeyValueName = "MyFeatureFlag",
                    ContentType = "application/vnd.microsoft.appconfig.ff+json;charset=utf-8",
                    Value = "false",
                });
```

in this case it creates only a *KeyValue* pair and not a feature flag, see the image below:

![image](https://user-images.githubusercontent.com/4405518/146668489-cd9aa4df-48c7-4a46-a1a2-85d63044e073.png)

then I tried to use the special naming of feature flags in Azure AppConfiguration by prefixing the name with `.appconfig.featureflag/`

```cs
         _ = new Pulumi.AzureNative.AppConfiguration.KeyValue("MyFeatureFlag",
                new Pulumi.AzureNative.AppConfiguration.KeyValueArgs
                {
                    ResourceGroupName = resourceGroup.Name,
                    ConfigStoreName = appConfig.Name,
                    KeyValueName = ".appconfig.featureflag/MyFeatureFlag",
                    ContentType = "application/vnd.microsoft.appconfig.ff+json;charset=utf-8",
                    Value = "false",
                });
```

and then I got the following error:

```cs
 azure-native:appconfiguration:KeyValue (MyFeatureFlag):
    error: autorest/azure: error response cannot be parsed: "" error: EOF
```

### Steps to reproduce

You could find a sample repository in [here](https://github.com/shahabganji/SampleProvisionAzureAppConfiguration)

Expected: The feature flag to be provisioned.
Actual: Either getting an error or it is provisioned as normal key value pairs.

**Comment by mikhailshilkov** [comment] 2021-12-20 09:55
Duplicate of https://github.com/pulumi/pulumi-azure-native/issues/988 please see the comments there for a solution

**Closed by mikhailshilkov** 2021-12-20 09:55 UTC
Labels: kind/bug, resolution/duplicate
