### ISSUE TITLE
Azure Spring App - Unable to set `httpsOnly` and `public` properties to true

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi-azure-native#2093] opened 2022-11-23 16:12 UTC
### What happened?

When creating an Azure Spring App, Pulumi always applies a value of `false` for the `public` and `httpsOnly` properties no matter the input provide.

### Steps to reproduce

Execute the below code:
```typescript
import * as pulumi from "@pulumi/pulumi";
import { App, Service } from "@pulumi/azure-native/appplatform/v20220901preview"

export const app = (
    rgName: pulumi.Input<string>,
) => {
    const svc = new Service("svc", {
        resourceGroupName: rgName,
        serviceName: "azspa-test",
    });

    new App("test", {
        resourceGroupName: rgName,
        serviceName: svc.name,
        appName: "azspa-app",
        identity: { type: "SystemAssigned" },
        properties: {
            httpsOnly: true,
            public: true
        }
    });
};
```

execute `pulumi up`
execute `pulumi stack export --file export.json`

### Expected Behavior

`public` and `httpsOnly` properties should be set to true

### Actual Behavior

`public` and `httpsOnly` properties are set to false and a `pulumi up` does not change anything.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment] 2022-11-24 00:17
Hi @phillipedwards - thank you for filing this bug.

While we take a look, could you help us out by telling us the output of `pulumi about` in your project folder, if possible?

**Comment by phillipedwards** [comment] 2022-11-28 17:31
@guineveresaenger here you are.
```bash
CLI          
Version      3.46.0
Go Version   go1.19.3
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.86.0
nodejs        unknown

Host     
OS       darwin
Version  12.2.1
Arch     x86_64

This project is written in nodejs: executable='/usr/local/opt/nvm/versions/node/v14.17.5/bin/node' version='v14.17.5'

Current Stack: dev

TYPE                                               URN
pulumi:pulumi:Stack                                urn:pulumi:dev::vizient-azure-cameron::pulumi:pulumi:Stack::vizient-azure-cameron-dev
pulumi:providers:azure-native                      urn:pulumi:dev::vizient-azure-cameron::pulumi:providers:azure-native::default_1_86_0
azure-native:resources:ResourceGroup               urn:pulumi:dev::vizient-azure-cameron::azure-native:resources:ResourceGroup::rg
azure-native:network:VirtualNetwork                urn:pulumi:dev::vizient-azure-cameron::azure-native:network:VirtualNetwork::vnet
azure-native:appplatform/v20220901preview:Service  urn:pulumi:dev::vizient-azure-cameron::azure-native:appplatform/v20220901preview:Service::svc
azure-native:appplatform/v20220901preview:App      urn:pulumi:dev::vizient-azure-cameron::azure-native:appplatform/v20220901preview:App::test


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/phillipedwards
User           phillipedwards
Organizations  phillipedwards, team-ce, demo

Dependencies:
NAME                  VERSION
@pulumi/pulumi        3.47.1
@types/node           14.18.33
@pulumi/azure-native  1.86.0

Pulumi locates its logs in /var/folders/0q/s4m1_9yd1qqfng0_0jlxlvs00000gn/T/ by default
```

**Comment by danielrbradley** [comment] 2022-12-06 12:25
Thanks for coming back to us on this @phillipedwards - glad you were able to find a resolution.

I'll close this issue as it would appear that this was a bug in a specific version of the Azure API rather than a provider issue.

**Comment by mikhailshilkov** [comment] 2022-12-06 12:28
I ran a short debugging session and logged our requests and Azure responses. We seem to set the properties correctly:

```
{"identity":{"type":"SystemAssigned"},"location":"westeurope","properties":{"enableEndToEndTLS":false,"httpsOnly":true,"public":true}}
```

and even the first response comes with both true

```
{"properties":{"addonConfigs":{"applicationConfigurationService":{},"serviceRegistry":{}},"public":true,"provisioningState":"Creating","httpsOnly":true,"enableEndToEndTLS":false,"ingressSettings":{"readTimeoutInSeconds":300,"sendTimeoutInSeconds":60,"sessionCookieMaxAge":0,"sessionAffinity":"None","backendProtocol":"Default"}},"type":"Microsoft.AppPlatform/Spring/apps","identity":null,"location":"westeurope","id":"/subscriptions/redacted","name":"azspa-app","systemData":{"createdBy":"redacted","createdByType":"User","createdAt":"2022-12-06T12:18:16.762305Z","lastModifiedBy":"redacted","lastModifiedByType":"User","lastModifiedAt":"2022-12-06T12:18:16.762305Z"}}
```

but when the App is finally provisioned, they are suddenly false:

```
{"properties":{"addonConfigs":{"applicationConfigurationService":{},"serviceRegistry":{}},"public":false,"provisioningState":"Succeeded","fqdn":"azspa-test.azuremicroservices.io","httpsOnly":false,"temporaryDisk":{"sizeInGB":5,"mountPath":"/tmp"},"persistentDisk":{"sizeInGB":0,"mountPath":"/persistent"},"enableEndToEndTLS":false,"ingressSettings":{"readTimeoutInSeconds":300,"sendTimeoutInSeconds":60,"sessionCookieMaxAge":0,"sessionAffinity":"None","backendProtocol":"Default"}},"type":"Microsoft.AppPlatform/Spring/apps","identity":{"type":"SystemAssigned","principalId":"redacted","tenantId":"706143bc-e1d4-4593-aee2-c9dc60ab9be7"},"location":"westeurope","id":"/subscriptions/redacted/providers/Microsoft.AppPlatform/Spring/azspa-test/apps/azspa-app","name":"azspa-app","systemData":{"createdBy":"redacted","createdByType":"User","createdAt":"2022-12-06T12:18:16.762305Z","lastModifiedBy":"redacted","lastModifiedByType":"User","lastModifiedAt":"2022-12-06T12:18:16.762305Z"}}
```

It definitely looks like a service issue to me.

**Comment by MitchellGerdisch** [comment] 2022-12-08 17:50
It turns out that `v20221101preview` doesn't fix the problem after all.
I also tested with v20221201 by installing  @pulumi/azure-native@1.89.0-alpha.1670482436    and the problem exists there as well.

There are two scenarios at play here:

**Scenario 1 (works)**

- Set `httpsOnly` and `public` to false
- `pulumi up`
- Everything is in synch and correct
- Update `httpsOnly` and `public` to true
- `pulumi up`
- Everything is in synch and correct.

**Scenario 2 (doesn't work)**
- Start with an empty stack
- Set `httpsOnly` and `public` to true
- `pulumi up`
- Azure shows the settings are false; Pulumi state shows the output values are set to false (note the state file shows the inputs are true as per the code)
- `pulumi refresh` doesn't detect the differences or anything since the state file inputs are in synch with the code even though the outputs are showing false - which is in synch with Azure.
- You can get back to a happy place by setting the values to false in the code, doing a `pulumi up` and then setting the valus to `true` in the code and doing a `pulumi up`. Basically executing Scenario 1 as described above.

**Comment by mikhailshilkov** [comment] 2022-12-09 07:49
@danielrbradley Should we report this issue upstream?

**Comment by mikhailshilkov** [comment] 2022-12-09 07:49
I guess one last thing we could try is to use an ARM template and try to reproduce this problem. @MitchellGerdisch would you have time to do so?

**Comment by MitchellGerdisch** [comment] 2022-12-09 14:15
Yes - I will test with an ARM template.

**Comment by MitchellGerdisch** [comment] 2022-12-12 15:35
Yes - absolutely does.
Here is a variation of the original code provided that I've been testing with:

```
import * as pulumi from "@pulumi/pulumi";
import * as resources from "@pulumi/azure-native/resources";
// import { App, Service } from "@pulumi/azure-native/appplatform/v20221101preview"
import { App, Service } from "@pulumi/azure-native/appplatform/v20221201"

const resourceGroup = new resources.ResourceGroup("mitch-rg");

const boolSetting = true

const svc = new Service("mitch-svc", {
    resourceGroupName: resourceGroup.name
});

const app = new App("mitch-app", {
    resourceGroupName: resourceGroup.name,
    serviceName: svc.name,
    identity: { type: "SystemAssigned" },
    properties: {
        httpsOnly: boolSetting,
        public: boolSetting,
    }
});


export const checkSettingsCommand = pulumi.interpolate`az spring app show -g ${resourceGroup.name} -s ${svc.name} -n ${app.name}`
```

**Comment by kpitzen** [comment] 2023-02-07 22:05
@phillipedwards  - at some point in the recent past, the Azure Spring Apps team released a fix to the bug in their API which was causing this issue.  I copied your repro code and ran `pulumi up`, then saw the following:
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/4128006/217377150-3a1aeb6f-5c9a-40f5-975c-bba907217581.png">


For a little more clarity:
<img width="1089" alt="image (1)" src="https://user-images.githubusercontent.com/4128006/217377183-6ae3e155-f50b-4d3a-b35e-a061644fb986.png">


I'm going to go ahead and call this issue resolved for now, but please reopen if you have a repro which still contains this issue.

**Closed by kpitzen** 2023-02-07 22:05 UTC
Labels: kind/bug, resolution/fixed, upstream/service
