### ISSUE TITLE
dbforpostgresql/Go: ServerProperties does not implement pulumi.Input

### ISSUE THREAD

**Issue by sebnyberg** [pulumi/pulumi-azure-native#2407] opened 2023-04-26 17:32 UTC
### What happened?

The `dbforpostgresql.ServerArgs` struct's `.Properties` field expects a `pulumi.Input`, but the corresponding `ServerProperties` structs do not implement the interface.

[ServerArgs struct](https://github.com/pulumi/pulumi-azure-native-sdk/blob/750d1b5fa2560864f63f4b386bf0b96474b2fecd/dbforpostgresql/server.go#L140):

```go
type ServerArgs struct {
        // ...
	Properties pulumi.Input
}
```

The `ServerProperties` structs, found [here](https://github.com/pulumi/pulumi-azure-native-sdk/blob/750d1b5fa2560864f63f4b386bf0b96474b2fecd/dbforpostgresql/pulumiTypes.go#L882) do not implement this interface

Example error:

```txt
    ./main.go:12:16: cannot use dbforpostgresql.ServerPropertiesForDefaultCreate{…} (value of type dbforpostgresql.ServerPropertiesForDefaultCreate) as pulumi.Input value in struct literal: dbforpostgresql.ServerPropertiesForDefaultCreate does not implement pulumi.Input (missing method ElementType)
```

### Expected Behavior

I expect the [examples](https://www.pulumi.com/registry/packages/azure-native/api-docs/dbforpostgresql/server/) to work, and for `dbforpostgresql.ServerPropertiesForDefaultCreate` and friends to satisfy `pulumi.Input`. It seems that they used to satisfy the struct signature when the examples were written.

### Steps to reproduce

Run this example with `pulumi up`:

```go
package main

import (
	dbforpostgresql "github.com/pulumi/pulumi-azure-native/sdk/go/azure/dbforpostgresql"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		_, err := dbforpostgresql.NewServer(ctx, "server", &dbforpostgresql.ServerArgs{
			Properties: dbforpostgresql.ServerPropertiesForDefaultCreate{},
		})
		return nil
	})
}
```

### Output of `pulumi about`

```
CLI          
Version      3.64.0
Go Version   go1.20.3
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.93.0
go            unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in go: executable='/usr/local/go/bin/go' version='go version go1.20.2 linux/amd64'

Current Stack: <omitted>

Found no resources associated with <omitted>

Found no pending operations associated with <omitted>

Backend        
Name           pulumi.com
URL            <omitted>
User           <omitted>
Organizations  <omitted>

Dependencies:
NAME                                       VERSION
github.com/pulumi/pulumi-azure-native/sdk  1.93.0
github.com/pulumi/pulumi/sdk/v3            3.64.0
```

### Additional context

go.mod:
```txt
go 1.18

require (
	github.com/pulumi/pulumi-azure-native/sdk v1.93.0
	github.com/pulumi/pulumi/sdk/v3 v3.64.0
)
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by sebnyberg** [comment] 2023-04-26 18:18
Looking at the code in `pulumiTypes.go` ([here](https://github.com/pulumi/pulumi-azure-native-sdk/blob/master/dbforpostgresql/pulumiTypes.go)), theres another field on this struct, `.Sku`, that does implement `pulumi.Input` as part of its generated code.

The `ServerProperties` mentioned in this issue however, do not. My guess is that something is just not configured correctly in the generator config.

**Comment by rquitales** [comment] 2023-04-26 21:34
@sebnyberg Thanks for reporting this type mismatch issue and I apologize for the inconvenience caused.

I've identified that this is a regression introduced in v1.51.0 of this provider. From v1.51.0 onwards, we lose `dbforpostgresql.ServerPropertiesForRestoreArgs` and friends which generates a properties struct that satisfies `pulumi.Input`.

The change log for this release: https://github.com/pulumi/pulumi-azure-native/blob/v1.51.0/CHANGELOG.md indicates 2 potentially causes of this issue. Pulumi dependencies were updated to v3.20.0 and there were [codegen improvements made for the Go SDK](https://github.com/pulumi/pulumi/pull/7943) - which is suspect this PR is the root cause.

I will follow-up with a more detailed report was we can further identify the issue here.

**Comment by rquitales** [comment] 2023-04-26 22:59
It looks like we'd need to generate more input types for enums/oneOf inputs.

In the meantime as a workaround, you should be able to generate your own types until we cut a release that address this.

Example code:
```go
package main

import (
	"reflect"

	dbforpostgresql "github.com/pulumi/pulumi-azure-native/sdk/go/azure/dbforpostgresql"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		_, err := dbforpostgresql.NewServer(ctx, "server", &dbforpostgresql.ServerArgs{
			Location: pulumi.String("brazilsouth"),
			Properties: ServerPropertiesForRestoreArgs{
				CreateMode:         pulumi.String("PointInTimeRestore"),
				RestorePointInTime: pulumi.String("2020-10-20T20:20:20+00:00"),
				SourceServerId:     pulumi.String("/subscriptions/ffffffff-ffff-ffff-ffff-ffffffffffff/resourceGroups/SourceResourceGroup/providers/Microsoft.DBforPostgreSQL/servers/sourceserver"),
			},
			ResourceGroupName: pulumi.String("TargetResourceGroup"),
			ServerName:        pulumi.String("targetserver"),
			Tags: pulumi.StringMap{
				"ElasticServer": pulumi.String("1"),
			},
		})

		if err != nil {
			return err
		}
		return nil
	})

}

type ServerPropertiesForRestoreArgs struct {
	CreateMode               pulumi.StringInput                  `pulumi:"createMode"`
	InfrastructureEncryption pulumi.StringPtrInput               `pulumi:"infrastructureEncryption"`
	MinimalTlsVersion        pulumi.StringPtrInput               `pulumi:"minimalTlsVersion"`
	PublicNetworkAccess      pulumi.StringPtrInput               `pulumi:"publicNetworkAccess"`
	RestorePointInTime       pulumi.StringInput                  `pulumi:"restorePointInTime"`
	SourceServerId           pulumi.StringInput                  `pulumi:"sourceServerId"`
	SslEnforcement           *dbforpostgresql.SslEnforcementEnum `pulumi:"sslEnforcement"`
	StorageProfile           *dbforpostgresql.StorageProfile     `pulumi:"storageProfile"`
	Version                  pulumi.StringPtrInput               `pulumi:"version"`
}

func (ServerPropertiesForRestoreArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*dbforpostgresql.ServerPropertiesForRestore)(nil)).Elem()
}

```

**Comment by sebnyberg** [comment] 2023-04-27 07:11
@rquitales
Thanks for your investigation and workaround. The latest versioned package worked fine so I'll just use that for now.

**Comment by Zaid-Ajaj** [comment] 2024-05-23 11:26
I believe this is no longer an issue, fixed by https://github.com/pulumi/pulumi/pull/14679 and latest azure-native v2.x should have all `Args` variant type that acceptable for places where `pulumi.Input` is expected. That said, azure-native v2.x has changed the API such that you no longer a specific `Properties` field, instead all properties have been "flattened" into the `ServerArgs` top-level properties

**Closed by Zaid-Ajaj** 2024-05-23 11:26 UTC
Labels: kind/bug, resolution/fixed, impact/regression, awaiting-upstream
