### ISSUE TITLE
Error in the golang exmaple azure-native EventSubscription

### ISSUE THREAD

**Issue by caboog** [pulumi/pulumi-azure-native#3030] opened 2024-01-17 20:36 UTC
### What happened?

The example for `EventSubscriptions_CreateOrUpdateForCustomTopic_StorageQueueDestination` shows the `Destination` field taking `eventgrid.StorageQueueEventSubscriptionDestination` which it can. not do.

### Example

Emphasis mine: 

```go
package main

import (
	"github.com/pulumi/pulumi-azure-native-sdk/eventgrid/v2"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		_, err := eventgrid.NewEventSubscription(ctx, "eventSubscription", &eventgrid.EventSubscriptionArgs{
			DeadLetterDestination: &eventgrid.StorageBlobDeadLetterDestinationArgs{
				BlobContainerName: pulumi.String("contosocontainer"),
				EndpointType:      pulumi.String("StorageBlob"),
				ResourceId:        pulumi.String("/subscriptions/55f3dcd4-cac7-43b4-990b-a139d62a1eb2/resourceGroups/TestRG/providers/Microsoft.Storage/storageAccounts/contosostg"),
			},
			Destination: eventgrid.StorageQueueEventSubscriptionDestination{   // <----- HERE
				EndpointType: "StorageQueue",
				QueueName:    "queue1",
				ResourceId:   "/subscriptions/d33c5f7a-02ea-40f4-bf52-07f17e84d6a8/resourceGroups/TestRG/providers/Microsoft.Storage/storageAccounts/contosostg",
			},
			EventSubscriptionName: pulumi.String("examplesubscription1"),
			Filter: &eventgrid.EventSubscriptionFilterArgs{
				IsSubjectCaseSensitive: pulumi.Bool(false),
				SubjectBeginsWith:      pulumi.String("ExamplePrefix"),
				SubjectEndsWith:        pulumi.String("ExampleSuffix"),
			},
			Scope: pulumi.String("subscriptions/5b4b650e-28b9-4790-b3ab-ddbd88d727c4/resourceGroups/examplerg/providers/Microsoft.EventGrid/topics/exampletopic1"),
		})
		if err != nil {
			return err
		}
		return nil
	})
}```

### Output of `pulumi about`

CLI
Version      3.100.0
Go Version   go1.21.5
Go Compiler  gc

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment] 2024-03-20 23:58
hmm... yeah the type `StorageQueueEventSubscriptionDestination` doesn't seem to exist anywhere in the API, even though it's clearly referenced in the docs. It looks like this might be somehow specific to go codegen as the other SDKs seem to have generated types for this field correctly.

**Comment by mikhailshilkov** [comment] 2024-04-02 11:26
@mjeffryes The `StorageQueueEventSubscriptionDestination` type does exist, but the example should have used `eventgrid.StorageBlobDeadLetterDestinationArgs`

```go
_, err := eventgrid.NewEventSubscription(ctx, "eventSubscription", &eventgrid.EventSubscriptionArgs{
	DeadLetterDestination: &eventgrid.StorageBlobDeadLetterDestinationArgs{
		BlobContainerName: pulumi.String("contosocontainer"),
		EndpointType:      pulumi.String("StorageBlob"),
		ResourceId:        pulumi.String("/subscriptions/55f3dcd4-cac7-43b4-990b-a139d62a1eb2/resourceGroups/TestRG/providers/Microsoft.Storage/storageAccounts/contosostg"),
	},
	Destination: eventgrid.StorageQueueEventSubscriptionDestinationArgs{
		EndpointType: pulumi.String("StorageQueue"),
		QueueName:    pulumi.String("queue1"),
		ResourceId:   pulumi.String("/subscriptions/d33c5f7a-02ea-40f4-bf52-07f17e84d6a8/resourceGroups/TestRG/providers/Microsoft.Storage/storageAccounts/contosostg"),
	},
	EventSubscriptionName: pulumi.String("examplesubscription1"),
	Filter: &eventgrid.EventSubscriptionFilterArgs{
		IsSubjectCaseSensitive: pulumi.Bool(false),
		SubjectBeginsWith:      pulumi.String("ExamplePrefix"),
		SubjectEndsWith:        pulumi.String("ExampleSuffix"),
	},
	Scope: pulumi.String("subscriptions/5b4b650e-28b9-4790-b3ab-ddbd88d727c4/resourceGroups/examplerg/providers/Microsoft.EventGrid/topics/exampletopic1"),
})
```

This issue is actually a duplicate of https://github.com/pulumi/pulumi-azure-native/issues/1554

**Closed** 2024-04-02 11:29 UTC
Labels: kind/bug, resolution/duplicate, customer/feedback, bug/codegen, customer/lighthouse
