### ISSUE TITLE
Unable to get function keys in web app[Azure/python]

### ISSUE THREAD

**Issue by dongfrank** [pulumi/pulumi-azure-native#1704] opened 2022-05-13 05:15 UTC
### What happened?

While trying to use pulumi_azure_native.web.list_web_app_function_keys_output to get function keys, it returns:
AttributeError: 'NoneType' object has no attribute 'id'

### Steps to reproduce

```
from pulumi_azure_native import web
function_key=web.list_web_app_function_keys_output(function_name="environments",
name="bianca-dev-environment-data",resource_group_name=resource_group_name)
pulumi.export("function_keys",function_key)
```

### Expected Behavior

Function keys will output successfuly.

### Actual Behavior

error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/root/.pulumi/bin/pulumi-language-python-exec", line 107, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
        return future.result()
      File "/usr/lib64/python3.6/asyncio/tasks.py", line 180, in _step
        result = coro.send(None)
      File "/opt/test_script/test/venv/lib64/python3.6/site-packages/pulumi/runtime/stack.py", line 126, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/opt/test_script/test/venv/lib64/python3.6/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await wait_for_rpcs()
      File "/opt/test_script/test/venv/lib64/python3.6/site-packages/pulumi/runtime/stack.py", line 110, in wait_for_rpcs
        raise exception
      File "/usr/lib64/python3.6/asyncio/tasks.py", line 180, in _step
        result = coro.send(None)
      File "/opt/test_script/test/venv/lib64/python3.6/site-packages/pulumi/output.py", line 169, in run
        value = await self._future
      File "/usr/lib64/python3.6/asyncio/tasks.py", line 180, in _step
        result = coro.send(None)
      File "/opt/test_script/test/venv/lib64/python3.6/site-packages/pulumi/output.py", line 194, in run
        transformed: Input[U] = func(value)
      File "/opt/test_script/test/venv/lib64/python3.6/site-packages/pulumi_azure_native/_utilities.py", line 234, in <lambda>
        **resolved_args['kwargs']))
      File "/opt/test_script/test/venv/lib64/python3.6/site-packages/pulumi_azure_native/web/v20210301/list_web_app_function_keys.py", line 117, in list_web_app_function_keys
        id=__ret__.id,
    AttributeError: 'NoneType' object has no attribute 'id'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1

### Versions used

pulumi v3.32.1

Python 3.6.8

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment] 2023-02-15 12:45
It's a duplicate of #593, please try `ListWebAppHostKeys` as suggested in https://github.com/pulumi/pulumi-azure-native/issues/593#issuecomment-778129186

**Closed by mikhailshilkov** 2023-02-15 12:45 UTC
Labels: kind/bug, resolution/duplicate, area/providers
