### ISSUE TITLE
Allow setting of api-version from resource request (C#?)

### ISSUE THREAD

**Issue by sloncho** [pulumi/pulumi-azure-native#1877] opened 2022-08-08 11:33 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

ATM there is no way to use [azure custom resource providers](https://docs.microsoft.com/en-us/azure/azure-resource-manager/custom-providers/overview) in order to create custom azure resources. Not a "pulumi" custom resource.

Explanation: "azure custom resource provider" is in a preview, and the API version is "2018-09-01-preview". The creation/registration of the [custom provider resource](https://www.pulumi.com/registry/packages/azure-native/api-docs/customproviders/customresourceprovider/) works as expected.

The problem appears, when we try to use that custom provider. We are using "[azure resource](https://www.pulumi.com/registry/packages/azure-native/api-docs/resources/resource/)" in order to do that. It appears that the way pulumi works, it builds the azure rest call/url by [using the api-version of the "custom resource" class](https://github.com/pulumi/pulumi-azure-native/blob/8e25d4968214578347f3eb3eed726460e417c528/provider/pkg/provider/provider.go#L286) - and as such it produces the error:
```
azure-native:resources:Resource service-principal creating error: cannot check existence of resource '/subscriptions/xxxxxx/resourcegroups/xxxxxx/providers/Microsoft.CustomProviders%2Fresourceproviders/outCustomProvider/mycustomresourcetype/myresourcename': status code 400, {"error":{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'zzzz' and API version '2019-05-01' for type 'resourceProviders'. The supported api-versions are '2018-09-01-preview'.
```
Technically, the error is expected - as the "2019-05-01" is the azure api version of the "Resource" class, but the api call should carry the api-version of the "resource provider" - "2018-09-01-preview".

There is no "2018-09-01-preview" api schema for "Resource", so no way to use that specific implementation.

A possible solutions:
1. Add "2018-09-01-preview" as possible alias to "Resource" class - maybe the easiest?
2. Allow somehow to specify "api-version" on the resource
3. Allow somehow to specify "api-version" using the customoptions.Provider
4. Something else?

We are using C#, but maybe the problem exists with other languages too.

I'm willing to contribute, but I'll need guidance where to look for extension points.

### Affected area/feature

AzureNative

**Comment by guineveresaenger** [comment] 2022-08-10 18:01
Hi @sloncho - thank you for reporting this issue. I'll get back to you here on what we can do.

**Comment by guineveresaenger** [comment] 2022-08-12 17:50
Hi @sloncho - I unfortunately don't have a super exciting update here. We'll need some time to investigate, as there's unfortunately currently no quick fix for this. We're tracking this as an enhancement internally.

**Comment by mikhailshilkov** [comment] 2023-12-01 19:19
Duplicate of https://github.com/pulumi/pulumi-azure-native/issues/2467, we'll track there

**Closed by mikhailshilkov** 2023-12-01 19:19 UTC
Labels: kind/enhancement, resolution/duplicate
