### ISSUE TITLE
Installing pulumi-azure-native adds 1.05GB to docker image

### ISSUE THREAD

**Issue by wallflower762** [pulumi/pulumi-azure-native#2096] opened 2022-11-24 09:24 UTC
## Hello!
- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
I deploy my infrastructure using Bitbucket pipelines. To do this, I build a base image to run the deployment from which includes Az CLI and pulumi-azure-native using the python pulumi image as a base.

The image size after installing these tools and packages is 2.8GB, which is huge. I managed to trim 550MB off the Az CLI install, but the pulumi-azure-native install using pip is add a full 1.05GB to the image.

Is there any way to reduce this size? It significantly affects the pipeline startup times.

### Affected area/feature

Generally useful for people using automated pipelines.

**Comment by danielrbradley** [comment] 2022-11-28 12:29
Hi @wallflower762, there's not currently a way of reducing the size of the SDK as it stands. 

I'll close this as a duplicate of https://github.com/pulumi/pulumi-azure-native/issues/913

You could try experimenting with deleting the python modules you're not using within the `pulumi-azure-native` package. This won't work for type-checking, but should be fine for just running the Python code as modules are lazily loaded at runtime, so this likely won't cause an issue if files are missing that aren't referenced. This is certainly not a "supported" approach and may break in the future if the SDK shape changes but might give a temporary route forward as a workaround.

**Closed by danielrbradley** 2022-11-28 12:29 UTC
Labels: kind/enhancement, resolution/duplicate
