### ISSUE TITLE
Failed building wheel for pulumi-azure-native

### ISSUE THREAD

**Issue by VandanKotecha** [pulumi/pulumi-azure-native#1516] opened 2022-02-16 03:57 UTC
Hello Pulumi Team,

I am Facing an issue while creating New pulumi project. Error is cause during setup of Wheel for pulumi-azure-native

The Errror in CMD :-

```
copying build\lib\pulumi_azure_native\billing\v20191001preview\list_billing_account_invoice_sections_by_create_subscription_permission.py -> build\bdist.win-amd64\wheel\.\pulumi_azure_native\billing\v20191001preview
      error: could not create 'build\bdist.win-amd64\wheel\.\pulumi_azure_native\billing\v20191001preview\list_billing_account_invoice_sections_by_create_subscription_permission.py': No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pulumi-azure-native
```
Need Your Kind Support,

Kind Regards,
Vandan

**Comment by danielrbradley** [comment] 2022-02-17 15:41
Hi, this is likely an issue relating to path length limits in Windows. You can try creating your workspace in a less nested folder as a workaround.

Closing as a duplicate of https://github.com/pulumi/pulumi-azure-native/issues/774

**Comment by chughesvf** [comment] 2022-11-13 13:30
I have received the same error starting off only 2 directories deep on C:\ based on suggestion of this post ( C:\pulumi\project ).

I have spent all weekend trying to get a simple POC up with Pulum to demo a possible replacement for IaC to my team on Monday and it is proving quite difficult to get off the ground

**Comment by sandeshvora** [comment] 2022-12-06 11:36
> I have received the same error starting off only 2 directories deep on C:\ based on suggestion of this post ( C:\pulumi\project ).
> 
> I have spent all weekend trying to get a simple POC up with Pulum to demo a possible replacement for IaC to my team on Monday and it is proving quite difficult to get off the ground

Even i tried increasing win32 path length, but still same issue..

**Comment by sandeshvora** [comment] 2022-12-06 11:38
> Hi, this is likely an issue relating to path length limits in Windows. You can try creating your workspace in a less nested folder as a workaround.
> 
> Closing as a duplicate of #774

 I tried increasing win32 path length, but still same issue..

**Comment by kpitzen** [comment] 2023-03-31 13:09
As we have no consistent repro, and this issue has been sitting stale for a while, I'm going to close for now. Feel free to re-open with more details if they become available.  Thank you!

**Closed by kpitzen** 2023-03-31 13:09 UTC
Labels: resolution/no-repro, kind/bug, needs-repro, awaiting-feedback

**Comment by ronaldgeorgeno** [comment] 2023-10-07 13:56
Hi, I had the same error. I installed Azure CLI  and then tried pulumi newv in vs code. It then worked perfectly.
