### ISSUE TITLE
Pulumi.AzureNative version 2.63.0/2.64.0 struggles with resource groups

### ISSUE THREAD

**Issue by CRidge** [pulumi/pulumi-azure-native#3603] opened 2024-09-30 22:41 UTC
### What happened?

A working C# Pulumi project suddenly started hanging on preview. When it finally failed, it seems it was unable to find information about existing resource groups. 

I reduced my project down to just the creation of a single resource group. Now preview worked, but up never completed (gave up after 400 seconds of "creating"). 

Since my package reference was for version 2.*, I didn't intentionally update the package, but I see it updated to 2.63.0 earlier today, then to 2.64.0 a little later. Reverting back to 2.62.0 made it all work again.

### Example

This was all there was in the end, which still failed:

```
        var rg = new ResourceGroup(
            "rg",
            new() { ResourceGroupName = $"my-resource-group", Location = Context.Location });
```

Part of the output:

```
I0930 22:32:16.475277   64348 eventsink.go:62] eventSink::Debug(<{%reset%}>Fields to assign: ["tags","properties","type","urn","location","id","name","managedBy"]<{%reset%}>) 
I0930 22:32:16.475277   64348 eventsink.go:59] Registering resource monitor end: t=azure-native:resources/v20240701:ResourceGroup, name=[CREATED-RESOURCE-GROUP-NAME], custom=True, remote=False 
I0930 22:32:16.475277   64348 eventsink.go:62] eventSink::Debug(<{%reset%}>Registering resource monitor end: t=azure-native:resources/v20240701:ResourceGroup, name=[CREATED-RESOURCE-GROUP-NAME], cust     pulumi:pulumi:Stack  [PULUMI-APP-NAME]-[STACK-NAME]  running..   
I0930 22:32:16.465586   39804 rpc.go:292] Unmarshaling property for RPC[azure-native.Diff(urn:pulumi:[STACK-NAME]::[PULUMI-APP-NAME]: 
I0930 22:32:47.816822   64348 eventsink.go:78] eventSink::Infoerr(<{%reset%}>
I0930 22:32:47.816822   39804 client.go:445] HTTP Request Begin GET https://management.azure.com/subscriptions/[SUBSCRIPTION-ID]/resourcegroups/[RESOURCE-GROUP-2]?api-version=2024-07-01 =================================================== <{%reset%}>) 
I0930 22:32:47.816822   64348 eventsink.go:78] eventSink::Infoerr(<{%reset%}>Empty body <{%reset%}>) 
I0930 22:32:47.816822   64348 eventsink.go:78] eventSink::Infoerr(<{%reset%}>===================================================== HTTP Request End GET https://management.azure.com/subscriptions/[SUBSCRIPTION-ID]/resourcegroups/[RESOURCE-GROUP-2]?api-version=2024-07-01 <{%reset%}>) 
I0930 22:32:47.817493   64348 eventsink.go:78] eventSink::Infoerr(<{%reset%}>
I0930 22:32:47.816822   39804 client.go:445] HTTP Request Begin GET https://management.azure.com/subscriptions/[SUBSCRIPTION-ID]/resourcegroups/[RESOURCE-GROUP-1]?api-version=2024-07-01 =================================================== <{%reset%}>) 
I0930 22:32:47.817493   64348 eventsink.go:78] eventSink::Infoerr(<{%reset%}>Empty body <{%reset%}>) 
I0930 22:32:47.817493   64348 eventsink.go:78] eventSink::Infoerr(<{%reset%}>===================================================== HTTP Request End GET https://management.azure.com/subscriptions/[SUBSCRIPTION-ID]/resourcegroups/[RESOURCE-GROUP-1]?api-version=2024-07-01 pulumi:pulumi:Stack  [PULUMI-APP-NAME]-[STACK-NAME]  running...  ===================================================== HTTP Request End GET https://management.azure.com/subscriptions/ 
I0930 22:33:48.862160   64348 eventsink.go:78] eventSink::Infoerr(<{%reset%}>
I0930 22:33:48.862160   39804 client.go:445] HTTP Request Begin GET https://management.azure.com/subscriptions/[SUBSCRIPTION-ID]/resourcegroups/[RESOURCE-GROUP-2]?api-version=2024-07-01 =================================================== <{%reset%}>) 
I0930 22:33:48.862160   64348 eventsink.go:78] eventSink::Infoerr(<{%reset%}>Empty body <{%reset%}>) 
I0930 22:33:48.862160   64348 eventsink.go:78] eventSink::Infoerr(<{%reset%}>===================================================== HTTP Request End GET https://management.azure.com/subscriptions/[SUBSCRIPTION-ID]/resourcegroups/[RESOURCE-GROUP-2]?api-version=2024-07-01 pulumi:pulumi:Stack  [PULUMI-APP-NAME]-[STACK-NAME]  running...  ===================================================== HTTP Request End GET https://management.azure.com/subscriptions/ 
I0930 22:33:48.955535   64348 eventsink.go:78] eventSink::Infoerr(<{%reset%}>
I0930 22:33:48.955031   39804 client.go:445] HTTP Request Begin GET https://management.azure.com/subscriptions/[SUBSCRIPTION-ID]/resourcegroups/[RESOURCE-GROUP-1]?api-version=2024-07-01 =================================================== <{%reset%}>) 
I0930 22:33:48.955535   64348 eventsink.go:78] eventSink::Infoerr(<{%reset%}>Empty body <{%reset%}>) 
I0930 22:33:48.955535   64348 eventsink.go:78] eventSink::Infoerr(<{%reset%}>===================================================== HTTP Request End GET https://management.azure.com/subscriptions/[SUBSCRIPTION-ID]/resourcegroups/[RESOURCE-GROUP-1]?api-version=2024-07-01 pulumi:pulumi:Stack  [PULUMI-APP-NAME]-[STACK-NAME]  running     ===================================================== HTTP Request End GET https://management.azure.com/subscriptions/ 
I0930 22:35:50.146910   64348 eventsink.go:78] eventSink::Infoerr(<{%reset%}>
I0930 22:35:50.146910   39804 client.go:445] HTTP Request Begin GET https://management.azure.com/subscriptions/[SUBSCRIPTION-ID]/resourcegroups/[RESOURCE-GROUP-2]?api-version=2024-07-01 =================================================== <{%reset%}>) 
I0930 22:35:50.147517   64348 eventsink.go:78] eventSink::Infoerr(<{%reset%}>Empty body <{%reset%}>) 
I0930 22:35:50.147517   64348 eventsink.go:78] eventSink::Infoerr(<{%reset%}>===================================================== HTTP Request End GET https://management.azure.com/subscriptions/[SUBSCRIPTION-ID]/resourcegroups/[RESOURCE-GROUP-2]?api-version=2024-07-01 pulumi:pulumi:Stack  [PULUMI-APP-NAME]-[STACK-NAME]  running     ===================================================== HTTP Request End GET https://management.azure.com/subscriptions/ 
I0930 22:35:50.225131   64348 eventsink.go:78] eventSink::Infoerr(<{%reset%}>
I0930 22:35:50.225131   39804 client.go:445] HTTP Request Begin GET https://management.azure.com/subscriptions/[SUBSCRIPTION-ID]/resourcegroups/[RESOURCE-GROUP-1]?api-version=2024-07-01 =================================================== <{%reset%}>) 
I0930 22:35:50.225131   64348 eventsink.go:78] eventSink::Infoerr(<{%reset%}>Empty body <{%reset%}>) 
I0930 22:35:50.225131   64348 eventsink.go:78] eventSink::Infoerr(<{%reset%}>===================================================== HTTP Request End GET https://management.azure.com/subscriptions/[SUBSCRIPTION-ID]/resourcegroups/[RESOURCE-GROUP-1]?api-version=2024-07-01 pulumi:pulumi:Stack  [PULUMI-APP-NAME]-[STACK-NAME]  running     ===================================================== HTTP Request End GET https://management.azure.com/subscriptions/
```

### Output of `pulumi about`

```
CLI
Version      3.134.1
Go Version   go1.23.1
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  azure-native  2.62.0
language  dotnet        unknown

Host
OS       Microsoft Windows 11 Pro
Version  10.0.26120 Build 26120
Arch     x86_64

This project is written in dotnet: executable='C:\Program Files\dotnet\dotnet.exe' version='9.0.100-rc.1.24452.12'

Backend
Name           [MACHINENAME]
URL            azblob://[CONTAINER]?storage_account=[ACCOUNT]
User           [USERNAME]
Organizations
Token type     personal

Dependencies:
NAME                VERSION
Pulumi              3.67.1
Pulumi.AzureNative  2.64.0
```

### Additional context

I'm not sure if 2.63.0 has the problem, but it seems this version was created in my local NuGet cache around the time I started having trouble.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment] 2024-10-01 08:52
Hi @CRidge, thank you for reporting this. I could reproduce it. How do authenticate to Azure in your Pulumi program? I suspect it has something to do with the CLI auth since our CI tests are all green.

**Comment by robnotley** [comment] 2024-10-01 08:53
I am also experiencing the same issue as outlined here

**Comment by thomas11** [comment] 2024-10-01 10:14
Apologies for the trouble, everyone. A fix is merged and will be released shortly.

**Closed** 2024-10-01 10:14 UTC
Labels: kind/bug, p0, impact/regression

**Comment by robnotley** [comment] 2024-10-02 12:44
Updated to 2.64.2 and this still appears to be an issue

**Comment by thomas11** [comment] 2024-10-02 12:56
> Updated to 2.64.2 and this still appears to be an issue

Can you tell us more about your setup? How does your program authenticate with Azure (CLI, service principal, OIDC)? What language is it in, and how did you update to 2.64.2?

**Comment by robnotley** [comment] 2024-10-03 10:26
We authenticate using service principal and are using python 3.12.7. Update to 2.64.2 was done by use of poetry dependency file. Rollback to 2.62.0 has resolved the issue.
