### ISSUE TITLE
VirtualMachineRunCommandByVirtualMachine appears not to work

### ISSUE THREAD

**Issue by mattnewport** [pulumi/pulumi-azure-native#694] opened 2021-03-26 00:49 UTC
I'm trying to run a script on a VM using Pulumi's `VirtualMachineRunCommandByVirtualMachine` resource https://www.pulumi.com/docs/reference/pkg/azure-native/compute/virtualmachineruncommandbyvirtualmachine/

When I run `pulumi up` I get the following error from Azure: 

`error: autorest/azure: Service returned an error. Status=nil
Code='OperationNotAllowed' Message='The property 'runCommands' is not valid because the 'Microsoft.Compute/RunCommandPreview' feature is not enabled for this subscription.'`

I checked under 'Preview Features' for the subscription and I cannot find a 'RunCommandPreview' feature to enable. When I opened a ticket with Azure support to ask about this they responded with:

> This preview feature mentioned on the error does not seem to be inside the Suscription's Preview Features at all, is it possible the third party tool is looking for it with an old ID? (e.g Microsoft.Compute/RunCommandPreview, the Run Command feature is no longer in preview).

It seems like perhaps Pulumi's implementation of this hasn't been updated to reflect the feature coming out of preview?

## Expected behavior
`VirtualMachineRunCommandByVirtualMachine` should allow scripts to be run on a VM.

## Current behavior
`VirtualMachineRunCommandByVirtualMachine` fails with the error message:

`error: autorest/azure: Service returned an error. Status=nil
Code='OperationNotAllowed' Message='The property 'runCommands' is not valid because the 'Microsoft.Compute/RunCommandPreview' feature is not enabled for this subscription.'`

## Steps to reproduce

1. Set up a stack that creates an Azure `VirtualMachine` resource and required dependencies.
2. Create a `VirtualMachineRunCommandByVirtualMachine` resource that references the vm, e.g.:
```
            new VirtualMachineRunCommandByVirtualMachine($"runSetupScriptOnVm", new VirtualMachineRunCommandByVirtualMachineArgs
            {
                AsyncExecution = false,
                ResourceGroupName = resourceGroup.Name,
                RunAsUser = vm.OsProfile.Apply(y => y!.AdminUsername!),
                RunAsPassword = adminPassword,
                RunCommandName = "testCommand",
                Source = new VirtualMachineRunCommandScriptSourceArgs
                {
                    Script = "Set-Content -Path 'c:\\testCommand.txt' -Value 'this is a test'\necho 'Done!'\n"
                },
                TimeoutInSeconds = 7200,
                VmName = vm.Name
            })
```
3. Run `pulumi up`
4. Observe the error message above.

## Context (Environment)
I'm trying to run a PowerShell script on a VM after it is created to perform set up tasks. It's not very clear from the Pulumi docs what the best way to do this is. DynamicProviders are mentioned in this context but they don't seem to be supported from C# currently and seem like they are maybe overkill to just run a PowerShell script. The other way to do this on Azure seems to be to use the Custom Script extension but this is even less well documented for use in Pulumi than `VirtualMachineRunCommandByVirtualMachine`.

## Affected feature

`VirtualMachineRunCommandByVirtualMachine`

**Comment by mikhailshilkov** [comment] 2021-03-26 07:16
Hmm... We are definitely not checking any preview feature enablement, this error comes from the Azure API.

This [ARM Template](https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/virtualmachines/runcommands?tabs=json) suggests using the API version `2020-06-01`. Could you try using that version in your Pulumi program? (`using Pulumi.AzureNative.Compute.V20200601`)

If you still get the error, does the ARM template work for you?

**Comment by UnstoppableMango** [comment] 2021-09-12 21:03
I'm currently running into this as well using typescript. I've tried every api between `2020-06-01` and latest with no luck.

**Comment by mikhailshilkov** [comment] 2021-09-13 08:47
Does the linked ARM template work for you @UnstoppableMango ?

**Comment by UnstoppableMango** [comment] 2021-09-14 01:32
It does not. I apologize, I should have checked that first. It definitely appears to be on the Azure side, not Pulumi.

I wonder if it has to do with my subscription, I'm on a Pay-as-you-go plan. There isn't `Microsoft.Compute/RunCommandPreview` available as a feature to enable. I can run a script via the Azure CLI just fine.

**Comment by UnstoppableMango** [comment] 2021-11-01 03:16
It's probably worth adding here, I was able to get the functionality I desired using VM extensions rather than RunCommand. Specifically, there is a [CustomScript extension](https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/custom-script-linux) that allows running commands similar to what I was hoping RunCommand would do. Here's my implementation in Typescript.

```ts
const cloudInitWait = new compute.VirtualMachineExtension('cloud-init-wait', {
  vmExtensionName: 'your-name-here',
  resourceGroupName: resourceGroup.name,
  vmName: vm.name,
  publisher: 'Microsoft.Azure.Extensions',
  type: 'CustomScript',
  typeHandlerVersion: '2.1',
  autoUpgradeMinorVersion: true,
  settings: {
    skipDos2Unix: true,
    commandToExecute: 'cloud-init status --wait > /dev/null',
  },
});
```

**Comment by robertlyson** [comment] 2021-11-02 15:25
Looks like `Microsoft.Compute virtualMachines/runCommands` is still in preview https://github.com/Azure/azure-sdk-for-go/issues/14493#issuecomment-833821822 but thanks to @UnstoppableMango I was able to handle my case with `CustomScript`. Posting it here (runs PowerShell scripts on Windows VM) in case someone needs it

```
var extension = new Extension("ssrsvmscript", new Pulumi.Azure.Compute.ExtensionArgs
{
    Name = "ssrsvmscript",
    VirtualMachineId = ssrsVm.Id,
    Publisher = "Microsoft.Compute",
    Type = "CustomScriptExtension",
    TypeHandlerVersion = "1.10",
    Settings = deploymentFiles["ssrsvm.ps1"].Apply(script => @"	{
    ""commandToExecute"": ""powershell -ExecutionPolicy Unrestricted -File ssrsvm.ps1"",
    ""fileUris"": [" + "\"" + script + "\"" + "]}")
});
```

**Comment by mikhailshilkov** [comment] 2023-08-28 20:15
Dupe of https://github.com/pulumi/pulumi-azure-native/issues/893

**Closed by mikhailshilkov** 2023-08-28 20:15 UTC
Labels: kind/bug, resolution/duplicate
