### ISSUE TITLE
`az keyvault` commands fail due to `"MissingApiVersionParameter` error

### ISSUE THREAD

**Issue by PhilBroderickCrezco** [pulumi/pulumi-azure-native#2894] opened 2023-11-17 10:01 UTC
### What happened?

When attempting to use the local `Command` resource (https://github.com/pulumi/pulumi-command) in a Pulumi .NET CLI application with the `az keyvault list` command and a custom `AzureNative` provider, the deployment failed with `cannot check existence of resource '': status code 400, {"error":{"code":"MissingApiVersionParameter","message":"The api-version query parameter (?api-version=) is required for all requests."}}`.

Running the `az keyvault list` command locally through `cmd` returned the expected results.

### Example

```csharp
return await Pulumi.Deployment.RunAsync(() =>
{
    var secret = new Command("logicalName", new CommandArgs
    {
        Create = "az keyvault secret show -n %SECRET_NAME% --vault-name %VAULT_NAME%",

    }, new CustomResourceOptions
    {
        Provider = new Provider("provider", new ProviderArgs
        {
            SubscriptionId = "sub-id",
            TenantId = "tenant-id"
        }),
    });

    return new Dictionary<string, object?>
    {
        { "StdOut", secret.Stdout }
    };
});
```

### Output of `pulumi about`

CLI
Version      3.78.0
Go Version   go1.20.7
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  2.18.0
command       0.9.1
dotnet        unknown

Host
OS       Microsoft Windows 11 Pro
Version  10.0.22621 Build 22621
Arch     x86_64

This project is written in dotnet: executable='C:\Program Files\dotnet\dotnet.exe' version='7.0.203'

Backend
Name           pulumi.com
URL            https://app.pulumi.com

Dependencies:
NAME                VERSION
Pulumi              3.59.0
Pulumi.AzureNative  2.18.0
Pulumi.Command      0.9.1

### Additional context

It seems to work fine when the custom provider isn't provided and testing locally with a user that has access to all subscriptions in Azure. However this isn't feasible in a CI pipeline, as we use Service Principals scoped to a given subscription, so need to provide an override to the subscription Id in order to query the correct KeyVault.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment] 2023-11-17 14:59
@PhilBroderickCrezco It looks like you are passing a `Provider` instance from the Azure Native package to the Command resource from the Command package. This is not a supported scenario. This basically asks the Azure Native provider to deploy a command, which it cannot do.

You would have to set the subscription and tenant throw the command itself or through its environment variables. Let me know if that helps.

**Comment by PhilBroderickCrezco** [comment] 2023-11-17 15:06
@mikhailshilkov interesting as we use that exact scenario for some of our stacks and we've haven't come across this error. It's only been since spinning up a new stack that we're seeing the issue 🤔

**Comment by mikhailshilkov** [comment] 2023-11-21 16:56
@PhilBroderickCrezco And did the resource actually work? I can't think of a way that, even if the resource ended up running by the Command provider, it would successfully receive the context of Subscription and Tenant IDs. At best, they would be ignored.

Anyway, I would say this is not a supported scenario and I'm inclined to close the issue as by design. What do you think?

**Comment by PhilBroderickCrezco** [comment] 2023-11-23 09:48
@mikhailshilkov it has certainly worked in the past for us with a .NET 6 CLI driven Pulumi application 🤔 I'm happy enough for you to close this one if it's by design. I've been able to successfully use the `az keyvault` command **without** a custom provider.

**Closed** 2023-11-28 11:55 UTC
Labels: kind/bug, resolution/by-design
