### ISSUE TITLE
RoleDefinition and RoleAssignment - GUIDs required, auto-naming submits auto name

### ISSUE THREAD

**Issue by shawnjones253** [pulumi/pulumi-azure-native#625] opened 2021-03-04 05:09 UTC
Tested using Pulumi.AzureNative.Authorization.V20180101Preview and Pulumi.AzureNative 0.7.1

When trying to create a `RoleDefinition` or `RoleAssignment`, both resources expect a GUID for their identifiers but AzureNative tries to use it's auto-generated random name for these properties, causing Azure to reject the request with 400.

`RoleAssignment`:
```
var assignment = new RoleAssignment(roleAssignmentName,
                            new RoleAssignmentArgs
                            {
                                // commented line below was the fix, needed to use a pulumi random uuid
                                // RoleAssignmentName = roleAssignmentUuid.Result,
                                Scope = Output.Tuple(storageAccountName, queue, resourceGroupName).Apply(async t =>
                                {
                                    var (storageAccountName, queue, resourceGroupName) = t;
                                    return await GetQueue.InvokeAsync(new GetQueueArgs()
                                    {
                                        AccountName = storageAccountName!,
                                        QueueName = queue!,
                                        ResourceGroupName = resourceGroupName!
                                    });
                                }).Apply(v => v.Id),
                                RoleDefinitionId = definition.Id,
                                PrincipalId = group.ObjectId,
                            }
```

```
azure-native:authorization/v20180101preview:RoleAssignment (assign_alertQ_0_0):
    error: cannot check existence of resource '/%2Fsubscriptions%sub-id%2FresourceGroups%2Frg-name%2Fproviders%2FMicrosoft.Storage%2FstorageAccounts%2Fstorage-acct-name%2FqueueServices%2Fdefault%2Fqueues%2Fqueue-name/providers/Microsoft.Authorization/roleAssignments/assign_alertQ_0_07848abbb': status code 400, {"error":{"code":"InvalidRoleAssignmentId","message":"The role assignment ID 'assign_alertQ_0_07848abbb' is not valid. The role assignment ID must be a GUID."}}
```

`RoleDefinition`:
```
var role = new RoleDefinition(roleDefinitionName,
                    new RoleDefinitionArgs
                    {
                        // commented line below was the fix, needed to use a pulumi random uuid
                        // RoleDefinitionId = readerRoleUuid.Result,
                        // specifying RoleDefinitionId also forced me to manually specify RoleName as below
                        //RoleName = $"{roleDefinitionName}{stackName}",
                        Scope = args.PolicyScope,
                        Permissions =
                        {
                            new PermissionArgs
                            {
                                Actions =
                                {
                                    // actions here
                                },
                                DataActions =
                                {
                                    // data actions here 
                                }
                            },
                        },
                        AssignableScopes =
                        {
                            Output.Create(Pulumi.Azure.Core.GetSubscription.InvokeAsync()).Apply(primary => primary.Id),
                        }
                    })
```

```
azure-native:authorization/v20180101preview:RoleDefinition (myRoleDefinitionName):
    error: cannot check existence of resource '/%2Fsubscriptions%2Fsub-id/providers/Microsoft.Authorization/roleDefinitions/myRoleDefinitionName2de6b416': status code 400, {"error":{"code":"InvalidRoleDefinitionId","message":"The role definition ID 'myRoleDefinitionName2de6b416' is not valid."}}
```

**Comment by mikhailshilkov** [comment] 2021-03-04 06:57
Yes, good point. The problem is that there's nothing in the spec that would indicate it's a GUID (except in the description): https://github.com/Azure/azure-rest-api-specs/blob/80e4e1b77162711ca1123042f50db03ffbf1bb40/specification/authorization/resource-manager/Microsoft.Authorization/preview/2020-04-01-preview/authorization-RoleAssignmentsCalls.json#L229-L232

I guess we'll have to bite the bullet and hard-code this.

**Comment by mikhailshilkov** [comment] 2021-03-04 07:01
Found this issues upstream: https://github.com/Azure/azure-rest-api-specs/issues/1684

**Comment by florianrusch** [comment] 2021-03-04 15:17
Same problem on my side. I think this will be a real issue for a many people starting to work with azure-native 😕 If I understand the problem correctly, there is currently no way to create a role assignment or?

**Comment by mikhailshilkov** [comment] 2021-03-04 15:51
@florianrusch There is a way to create it, it's just that you have to assign the name explicitly: either hard-code a random Guid or assign it with the `random` provider as shown [here](https://github.com/pulumi/examples/blob/2e9e18b36a9720dd0e691f2bfe883bbfd46bd512/azure-cs-synapse/MyStack.cs#L77).

**Comment by florianrusch** [comment] 2021-03-05 05:17
@mikhailshilkov thank you! And again I learned something 😉 Works great!

**Closed** 2021-03-16 10:04 UTC
Labels: 1.0, kind/bug, upstream/open-api
