### ISSUE TITLE
Improve API docs so they don't just contain the latest API version when a major version is released

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi-azure-native#2244] opened 2023-02-14 09:53 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently, the docs on the website are locked at the latest API version of the module when the major version of the provider is released. Since we haven't done a major release since April 2021, the docs haven't updated since then, and the default version hasn't changed since then. New resource coming in means that those are (more) up to date, but any resource that we've had since day 1 hasn't been updated.

### Affected area/feature

Docs

**Comment by lukehoban** [comment] 2023-02-15 23:35
Closing as duplicate of https://github.com/pulumi/registry/issues/1810.

Also related:
* https://github.com/pulumi/pulumi-azure-native/issues/1392
* https://github.com/pulumi/pulumi-azure-native/issues/2194

**Closed** 2023-02-15 23:45 UTC
Labels: kind/enhancement, resolution/duplicate, area/docs
