### ISSUE TITLE
Immediate `pulumi refresh` after `pulumi up` causes unexpected diffs in BlobContainer

### ISSUE THREAD

**Issue by Zaid-Ajaj** [pulumi/pulumi-azure-native#2837] opened 2023-09-28 18:52 UTC
### What happened?

When running `pulumi refresh` straight after running `pulumi up` which deploys a `BlobContainer`, the CLI shows that there are changes to be imported from the cloud for that blob container

### Example

Run `pulumi up` for the following program in TypeScript:
```ts
import * as resources from "@pulumi/azure-native/resources";
import * as storage from "@pulumi/azure-native/storage";

// Create an Azure Resource Group
const resourceGroup = new resources.ResourceGroup("resourceGroup");
// Create an Azure resource (Storage Account)
const storageAccount = new storage.StorageAccount("sa", {
    resourceGroupName: resourceGroup.name,
    sku: {
        name: storage.SkuName.Standard_LRS,
    },
    kind: storage.Kind.StorageV2,
})
const blobContainer = new storage.BlobContainer("blobContainer", {
    accountName: storageAccount.name,
    resourceGroupName: resourceGroup.name,
    containerName: "assets",
    publicAccess: storage.PublicAccess.Blob,
})
```
Then `pulumi refresh`, you will see:
```
     Type                                     Name             Plan       Info
     pulumi:pulumi:Stack                      stringasset-dev             
     ├─ azure-native:resources:ResourceGroup  resourceGroup               
 ~   ├─ azure-native:storage:BlobContainer    blobContainer    update     [diff: +defaultEncryptionScope,denyEncryptionScopeOverride,etag,lastModifiedTime,leaseState,leaseStat
     └─ azure-native:storage:StorageAccount   sa                          


Resources:
    ~ 1 to update
    3 unchanged

Do you want to perform this refresh?
No resources will be modified as part of this refresh; just your stack's state will be.
 details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::stringasset::pulumi:pulumi:Stack::stringasset-dev]
    ~ azure-native:storage:BlobContainer: (update)
        [id=/subscriptions/0282681f-7a9e-424b-80b2-96babd57a8a1/resourceGroups/resourceGroupc6a425d2/providers/Microsoft.Storage/storageAccounts/sad1f1f401/blobServices/default/containers/assets]
        [urn=urn:pulumi:dev::stringasset::azure-native:storage:BlobContainer::blobContainer]
        [provider=urn:pulumi:dev::stringasset::pulumi:providers:azure-native::default_2_9_0::452ea3bf-9857-4a9f-800c-341052854430]
        --outputs:--
      + defaultEncryptionScope     : "$account-encryption-key"
      + denyEncryptionScopeOverride: false
      + etag                       : "\"0x8DBC045DF1C3320\""
      + lastModifiedTime           : "2023-09-28T17:10:53.0000000Z"
      + leaseState                 : "Available"
      + leaseStatus                : "Unlocked"
      + legalHold                  : {
          + hasLegalHold: false
          + tags        : []
        }
```

### Output of `pulumi about`

```
CLI          
Version      3.86.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  2.9.0
nodejs        unknown

Host     
OS       darwin
Version  13.2.1
Arch     arm64

This project is written in nodejs: executable='/usr/local/bin/node' version='v20.5.1'

Current Stack: zaid-pulumi-corp/stringasset/dev

TYPE                                  URN
pulumi:pulumi:Stack                   urn:pulumi:dev::stringasset::pulumi:pulumi:Stack::stringasset-dev
pulumi:providers:azure-native         urn:pulumi:dev::stringasset::pulumi:providers:azure-native::default_2_9_0
azure-native:resources:ResourceGroup  urn:pulumi:dev::stringasset::azure-native:resources:ResourceGroup::resourceGroup
azure-native:storage:StorageAccount   urn:pulumi:dev::stringasset::azure-native:storage:StorageAccount::sa
azure-native:storage:BlobContainer    urn:pulumi:dev::stringasset::azure-native:storage:BlobContainer::blobContainer


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/zaid-pulumi-corp
User           zaid-pulumi-corp
Organizations  zaid-pulumi-corp, pulumi
Token type     personal

Dependencies:
NAME                  VERSION
@pulumi/azure-native  2.9.0
@pulumi/pulumi        3.86.0
@types/node           16.18.54
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment] 2023-10-19 07:22
Duplicate of https://github.com/pulumi/pulumi-azure-native/issues/2833

**Closed by mikhailshilkov** 2023-10-19 07:22 UTC
Labels: kind/bug, resolution/duplicate
