### ISSUE TITLE
How to add WebApps own url in its own appsettings?

### ISSUE THREAD

**Issue by sturlath** [pulumi/pulumi-azure-native#1445] opened 2022-01-22 12:21 UTC
Currently I have a appSetting that is a url to it self (the abp.io framework demands this of me) and what ever I try I just can´t get it to work. It always comes to Azure portal config as empty but I can see the output in the Pulumi CLI

I have tried all variations with/without Output.Create etc. so this is just the current one.

```csharp
[Output] public Output<string> IdentityEndpoint { get; set; }

private void SetupService()
{
     var identityApp = Output.Create(new AzureNative.Web.WebApp("IdentityService", new AzureNative.Web.WebAppArgs
      {
          ResourceGroupName = ResourceGroup.Apply(t => t.Name),
          Location = ResourceGroup.Apply(t => t.Location),
          ServerFarmId = AppServicePlan.Id,
          SiteConfig = new AzureNative.Web.Inputs.SiteConfigArgs
          {
              AppSettings = {            
                  //Abp.io
                   new AzureNative.Web.Inputs.NameValuePairArgs{
                      Name = "App:SelfUrl",
                      Value = IdentityEndpoint.Apply(c=>c), //<-- always empty
                  },
            }
      }));

     // I thought Output should be a promise so this all would work fine... so the config would just be updated after this line..
      IdentityEndpoint = Output.Format($"https://{identityApp.Apply(c=>c.DefaultHostName)}");
}
```

Is this even possible today and if not then its a feature request if its even possible at all.

[Here is all my code](https://github.com/sturlath/MyTest/blob/68592cf1495d2c802e50dcb926682106dbc88251/AppStack.cs#L586) and how I´m trying to use this if you want to try it out.

**Comment by danielrbradley** [comment] 2022-01-25 16:22
Ah nice try with trying to delay the assignment of the output value, unfortunately this won't work due to the way Pulumi's desired state works internally.

What you've got here is a classic circular dependancy issue - and a very clean example of it too! Here's a recent [blog post on circular dependencies](https://www.pulumi.com/blog/exploring-circular-dependencies/) with a little more information and ideas.

If you can't predict what the URL is going to be from the WebApp, my recommendation would be to:
1. Create an output containing the `DefaultHostName`.
2. Use a StackReference to the current stack
3. Get the previously outputted value of the `DefaultHostName` from the stack reference to set the AppSettings value, or a default value if it's not yet been output.
4. You'll need to run `pulumi up` twice on the first time deploying to set the AppSettings correctly.

Closing as a duplicate of https://github.com/pulumi/pulumi/issues/3021 which is tracking the issue in the core Pulumi engine.

**Closed by danielrbradley** 2022-01-25 16:22 UTC
Labels: kind/bug, resolution/duplicate
