### ISSUE TITLE
Installation with pip in Windows 10 Anaconda environment fails

### ISSUE THREAD

**Issue by krishnadubba** [pulumi/pulumi-azure-native#774] opened 2021-04-20 16:12 UTC
I am trying to install pulumi-azure-native in Windows 10 using pip (in the Anaconda environment).

## Expected behavior
Installation using pip in Anaconda environment should have been smooth.

## Current behavior
I see the following error:

 error: could not create 'build\bdist.win-amd64\wheel\.\pulumi_azure_native\m365securityandcompliance\v20210325preview\getprivate_link_services_for_o365_management_activity_api.py': No such file or directory
  ----------------------------------------
  ERROR: Failed building wheel for pulumi-azure-native

## Context (Environment)
OS: Windows 10
Python env: Anaconda Python 3.8.8 environment
$ pip install pulumi_azure_native

**Comment by viveklak** [comment] 2021-04-30 03:55
I confirmed this on a windows instance. However, pip is falls back to install just fine through `setup.py install` instead so as such the installation does succeed. Is this the behavior you are seeing?

I was able to build the wheel myself by downloading https://files.pythonhosted.org/packages/69/2d/91f85bebf172dd118065214183aa56757c7cd204d51004c51af42ae2e8fe/pulumi_azure_native-1.2.0.tar.gz and running `python setup.py bdist_wheel`. Looks like it is just the wheel install within the anaconda shadow environment. 

I believe this has to do with the default filesystem path length. Seems like its the copying of the files which fails which also signals this. I set the `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\ LongPathsEnabled` registry entry to allow longer path lengths and re-did the pip install which resulted in a successful wheel build/install.

I am afraid I don't know what we can do about the longer file names. Its something that comes with the territory.  Given the setup fallback works and there is a workaround for the wheel build, I am going to close this issue.

Please reopen if I missed something.

**Closed by viveklak** 2021-04-30 03:55 UTC
Labels: kind/bug, resolution/invalid

**Comment by RyanS-J** [comment] 2023-04-28 07:11
Another possible issue is a limitation in the length of the path as windows does have a default limit of 256-characters. I fixed this by enabling win32 long paths.

From the [MS Doc](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=powershell) this can be done via group policy or the following powershell command:

```New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force```
