### ISSUE TITLE
Sku.Name is no longer a string

### ISSUE THREAD

**Issue by pete-lembke-relativity** [pulumi/pulumi-azure-native#1802] opened 2022-02-04 16:44 UTC
File: [themes/default/content/registry/packages/azure-native/api-docs/keyvault/vault/_index.md](https://www.pulumi.com/registry/packages/azure-native/api-docs/keyvault/vault/)

When i try to copy this code and i use Pulumi.AzureNative package 1.56.0, the Sku.Name is no longer a string it is a `Input<Pulumi.AzureNative.KeyVault.SkuName>` value, where as the Family is a `InputUnion<string, Pulumi.AzureNative.KeyVault.SkuFamily>` which accepts a string as a setting.

**Comment by mnlumi** [comment] 2023-07-25 21:20
Need to retest to see if its still an issue.

**Comment by mikhailshilkov** [comment] 2023-08-04 12:07
Whether an enum should accept a string or not is defined in Azure Open API specs. For SKU name in particular, here is the line that says it should not: https://github.com/Azure/azure-rest-api-specs/blob/14d24d17491d8c2bde24532cb8cc2d663c0ffd9f/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2023-02-01/keyvault.json#L1052

On the contrary, the SKU family is defined to allow strings: https://github.com/Azure/azure-rest-api-specs/blob/14d24d17491d8c2bde24532cb8cc2d663c0ffd9f/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2023-02-01/keyvault.json#L1040

Since Pulumi behaves truthfully to upstream API specs, I'll go ahead and close this issue as "by design".

**Closed by mikhailshilkov** 2023-08-04 12:07 UTC
Labels: kind/bug, resolution/by-design
