### ISSUE TITLE
Should SkuArgs.SkuName be InputUnion<string, SkuName>?

### ISSUE THREAD

**Issue by stokesy43** [pulumi/pulumi-azure-native#2238] opened 2023-02-09 17:22 UTC
### What happened?

On the SkuArgs input for a KeyVault found [here](https://github.com/pulumi/pulumi-azure-native/blob/master/sdk/dotnet/KeyVault/Inputs/SkuArgs.cs)

The `SkuFamily` is an `InputUnion<string, Pulumi.AzureNative.KeyVault.SkuFamily>`

Whereas the SkuName is just an `Input<Pulumi.AzureNative.KeyVault.SkuName>`

This makes it hard to pass config in as string.  I've then got do an if statement to convert it to the correct SkuName struct value.

Is this by design or just an oversight?

### Expected Behavior

The SkuName field accepts a string

### Steps to reproduce

```
    public class KeyVaultOptions
    {
        public string SkuName { get; set; } = null!;
        public string SkuFamily { get; set; } = null!;
    }

```

```
var config = new Pul.Config();
var moduleSettings = config.RequireObject<KeyVaultOptions>("kv-01");

```

```
Properties = new VaultPropertiesArgs
            {
                Sku = new SkuArgs
                {
                    Family = moduleSettings.SkuFamily,
                    Name = moduleSettings.SkuName == SkuName.Standard.ToString() ? SkuName.Standard : SkuName.Premium
                },
            }
```

### Output of `pulumi about`

N/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by squaremo** [comment] 2023-02-13 17:53
Related: https://github.com/pulumi/pulumi-azure-native/issues/1802

**Comment by mikhailshilkov** [comment] 2023-08-04 12:03
Closing as a dupe of #1802

**Closed by mikhailshilkov** 2023-08-04 12:03 UTC
Labels: kind/enhancement, resolution/duplicate
