### ISSUE TITLE
[sdk/go] Parts of the Go SDK don't compile

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-azure-native#1101] opened 2021-08-27 16:17 UTC
We had to revert to a previous version of the codegen to work around #1092. This change was made in #1094, but that put the SDK back into a partially broken state.

We need to figure out a way to reduce the size of the Go SDK before we can pull in the fix.

Related: https://github.com/pulumi/pulumi-azure-native/issues/1092#issuecomment-907153966

**Comment by giacomo-pati** [comment] 2021-09-01 07:02
Is there any rough timeline when the broken Go SDK will be fixed regarding #1092 as we are stuck in our upgrading process because of it?

**Comment by mikhailshilkov** [comment] 2021-09-01 08:52
> Even the last release 1.24.0 is broken

As far as I know, 1.24.0 is as broken as 1.22.0 (because we essentially rolled it back). Have you changed the strictness of your checks recently?

**Comment by giacomo-pati** [comment] 2021-09-01 12:12
Nope, why should I ;-)

**Comment by giacomo-pati** [comment] 2021-09-02 06:45
@mikhailshilkov can you explain how to "changed the strictness of your checks". Even with 1.25.0 I have the same issue as mentioned above and pulumi just stops with "error: an unhandled error occurred: program exited with non-zero exit code: 2".
I'm kinda stuck here not being able to use newest versions of azure-native

**Comment by giacomo-pati** [comment] 2021-09-09 13:42
I'm still stuck with latest (1.26.0) pulumi-azure-native Golang SDK and pulumi-cli (3.12.0) on Windows:

Diagnostics:
  pulumi:pulumi:Stack (base-infra-base-infra-dev-giacomo):
    # github.com/pulumi/pulumi-azure-native/sdk/go/azure/insights
    ..\..\..\..\..\go\pkg\mod\github.com\pulumi\pulumi-azure-native\sdk@v1.26.0\go\azure\insights\pulumiTypes.go:22991:62: undefined: WorkbookTemplateLocalizedGalleryArgsArrayInput
    ..\..\..\..\..\go\pkg\mod\github.com\pulumi\pulumi-azure-native\sdk@v1.26.0\go\azure\insights\pulumiTypes.go:22994:26: undefined: WorkbookTemplateLocalizedGalleryArgsArray
    ..\..\..\..\..\go\pkg\mod\github.com\pulumi\pulumi-azure-native\sdk@v1.26.0\go\azure\insights\pulumiTypes.go:23008:26: undefined: WorkbookTemplateLocalizedGalleryArgsArray
    ..\..\..\..\..\go\pkg\mod\github.com\pulumi\pulumi-azure-native\sdk@v1.26.0\go\azure\insights\pulumiTypes.go:23019:92: undefined: WorkbookTemplateLocalizedGalleryArgsArrayOutput
    ..\..\..\..\..\go\pkg\mod\github.com\pulumi\pulumi-azure-native\sdk@v1.26.0\go\azure\insights\pulumiTypes.go:23020:56: undefined: WorkbookTemplateLocalizedGalleryArgsArray
    ..\..\..\..\..\go\pkg\mod\github.com\pulumi\pulumi-azure-native\sdk@v1.26.0\go\azure\insights\pulumiTypes.go:23021:28: undefined: WorkbookTemplateLocalizedGalleryArgsArray
    ..\..\..\..\..\go\pkg\mod\github.com\pulumi\pulumi-azure-native\sdk@v1.26.0\go\azure\insights\pulumiTypes.go:23022:6: undefined: WorkbookTemplateLocalizedGalleryArgsArrayOutput
    ..\..\..\..\..\go\pkg\mod\github.com\pulumi\pulumi-azure-native\sdk@v1.26.0\go\azure\insights\workbookTemplate.go:132:12: undefined: WorkbookTemplateLocalizedGalleryArrayMapInput

    error: an unhandled error occurred: program exited with non-zero exit code: 2

How can I get over it?

**Closed** 2021-09-10 07:31 UTC
Labels: kind/bug, emergent

**Comment by mikhailshilkov** [comment] 2021-09-10 08:47
@giacomo-pati Could you please give 1.27.0 a try? It should have mitigated both problems (size and compilation).

**Comment by giacomo-pati** [comment] 2021-09-10 17:39
A quick test show it might work again! Will know more once our over-night pipeline has done some more in-depth testing. Will let you know.

**Comment by giacomo-pati** [comment] 2021-09-13 05:58
I can confirm that for now all seem to run smooth again with our upgrading automation reg. pulumi-azure-native SDK
