### ISSUE TITLE
Another operation on this or dependent resource is in progress

### ISSUE THREAD

**Issue by tksrc** [pulumi/pulumi-azure-native#1024] opened 2021-07-26 19:53 UTC
I am creating a VNET with multiple subnets which have service endpoints configured.

Here is an example of one such subnet. 

```python
Subnet(
    "dbw_analytics_hosts",
    subnet_name=(
        platform_config.generate_resource_name("subnet", "dbw-analytics-hosts")
    ),
    resource_group_name=rg.infra.name,
    virtual_network_name=vnet.name,
    address_prefix=subnets_config["dbw_analytics_hosts"]["address_prefix"],
    route_table=RouteTableArgs(id=main_route_table.id),
    network_security_group=NetworkSecurityGroupArgs(id=databricks_nsg.id),
    nat_gateway=nat_gateway_id,
    service_endpoints=[
        ServiceEndpointPropertiesFormatArgs(
            service="Microsoft.Storage",
        ),
        ServiceEndpointPropertiesFormatArgs(
            service="Microsoft.KeyVault",
        ),
    ],
    delegations=[
        DelegationArgs(
            name="databricks", service_name="Microsoft.Databricks/workspaces"
        )
    ],
)
```

Running `pulumi up` ends with errors like these for some of the subnets whilst other deploy fine.
```
  azure-native:network:Subnet (dbw_analytics_hosts):
    error: autorest/azure: Service returned an error. Status=<nil> Code="AnotherOperationInProgress" Message="Another operation on this or dependent resource is in progress. To retrieve status of the operation use uri: https://management.azure.com/subscriptions/xxxxx/providers/Microsoft.Network/locations/eastus/operations/550eeb71-1aee-47d2-99c2-328ee37c728f?api-version=2020-11-01." Details=[]
```

* If I run `pulumi up` multiple times, eventually all subnets deploy.
* If I run `pulumi up -p 1` all subnets deploy without issues.
* If I get rid of the `service_endpoints` all subnets deploy without issues with or without parallelism being limited to 1. 

Any ideas what's wrong?

**Comment by leezen** [comment] 2021-07-28 20:08
@tksrc One potential workaround you could do to get the equivalent of `pulumi up -p 1` but only for the subnets is to arbitrarily chain them with each other via `depends_on` -- this way, only one will deploy after the prior one has deployed.

**Comment by tksrc** [comment] 2021-07-29 05:00
Thanks @leezen This would work for now.

**Comment by mikhailshilkov** [comment] 2021-07-29 07:48
Looks like a dupe of https://github.com/pulumi/pulumi-azure-native/issues/903, so let's track there

**Closed** 2021-07-29 07:48 UTC
Labels: kind/bug, resolution/duplicate
