### ISSUE TITLE
Can't Actually construct an ApplicationGateway without shenanigans

### ISSUE THREAD

**Issue by jamie-at-arkifi** [pulumi/pulumi-azure-native#3143] opened 2024-03-11 21:02 UTC
### What happened?

See also: https://pulumi-community.slack.com/archives/CRVK66N5U/p1710189945704329

`ApplicationGateway` is full of sub-resources, and some of those sub-resources need to refer to each other. Which you can't do unless you have the `ApplicationGateway` ID. Which you don't get until the `ApplicationGateway` is instantiated or you construct an ID yourself (`pulumi_random.RandomPet` to `ResourceOptions.id`) .

### Example

```python
network.ApplicationGateway(
        f"{name}-ag",
        resource_group_name=resource_group.name,
        sku=network.ApplicationGatewaySkuArgs(name="Standard_v2", tier="Standard_v2"),
        autoscale_configuration=network.ApplicationGatewayAutoscaleConfigurationArgs(
            min_capacity=1,
            max_capacity=10,
        ),
        gateway_ip_configurations=[
            network.ApplicationGatewayIPConfigurationArgs(
                name="gateway",
                subnet=network.SubResourceArgs(id=sn_gateway.id)
            )
        ],
        frontend_ip_configurations=[
            fi4 := network.ApplicationGatewayFrontendIPConfigurationArgs(
                name="frontend-ip4",
                public_ip_address=network.SubResourceArgs(id=ip4.id),
            ),
            fi6 := network.ApplicationGatewayFrontendIPConfigurationArgs(
                name="frontend-ip6",
                public_ip_address=network.SubResourceArgs(id=ip6.id),
            ),
        ],
        frontend_ports=[
            fp80 := network.ApplicationGatewayFrontendPortArgs(
                name="port-80",
                port=80,
            ),
            # TODO: 443
        ],
        enable_http2=True,
        http_listeners=[
            network.ApplicationGatewayHttpListenerArgs(
                name="listener-80-IP4",
                protocol=network.ApplicationGatewayProtocol.HTTP,
                frontend_ip_configuration=network.SubResourceArgs(id=fi4.id),  # This doesn't work!
                frontend_port=network.SubResourceArgs(id=fp80.id),
            ),
            # TODO: 443/HTTPS
        ],
        request_routing_rules=[],
        backend_http_settings_collection=[
            network.ApplicationGatewayBackendHttpSettingsArgs(
                name="settings-80",
                port=80,
                protocol=network.ApplicationGatewayProtocol.HTTP,
                cookie_based_affinity="Disabled",
                request_timeout=20,  # XXX: How does this interact with WebSocket?
                connection_draining=network.ApplicationGatewayConnectionDrainingArgs(
                    enabled=True,
                    drain_timeout_in_sec=60,
                ),
            ),
            # TODO: 443/HTTPS
        ],
        backend_address_pools=[
            network.ApplicationGatewayBackendAddressPoolArgs(
                name="pool",
                backend_addresses=[],
            )
        ],
        **OPTS
    )
```

### Output of `pulumi about`

```
CLI
Version      3.107.0
Go Version   go1.22.0
Go Compiler  gc

Plugins
NAME          VERSION
azure         5.68.0
azure-native  2.30.0
azuread       5.47.2
postgresql    3.11.0
python        unknown
random        4.16.0
tailscale     0.15.0

Host
OS       darwin
Version  14.3.1
Arch     arm64

This project is written in python: executable='/Users/jamie/.local/share/virtualenvs/blount-z19IO5O9/bin/python3' version='3.12.1'

Current Stack: organization/deborah/dev

TYPE                                                          URN
[REDACTED]


Found no pending operations associated with dev

Backend
Name           Jamies-MacBook-Pro.local
URL            file://~
User           jamie
Organizations
Token type     personal

Dependencies:
NAME                 VERSION
Flask                3.0.2
gunicorn             21.2.0
httpx                0.27.0
jwcrypto             1.5.5
mypy-extensions      1.0.0
nodeenv              1.8.0
pip-tools            7.4.1
pulumi_azure         5.68.0
pulumi_azure_native  2.30.0
pulumi_azuread       5.47.2
pulumi_postgresql    3.11.0
pulumi_random        4.16.0
pulumi_tailscale     0.15.0
svcs                 24.1.0
xonsh                0.15.0

Pulumi locates its logs in /var/folders/wf/m1npswwj7013_hlxb2qx84j40000gn/T/ by default
```

### Additional context

Looking at the docs, I think `pulumi_azure.network.ApplicationGateway` doesn't need the full ID.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment] 2024-03-12 16:55
Thanks for reporting this @jamie-at-arkifi. Yes, it's unfortunate, but we've come across a few of these resources in the Azure API that have circular references. Your workaround of constructing the id explicitly so you can use it in the http_listeners block is probably the best option at the moment.

**Comment by mikhailshilkov** [comment] 2024-04-28 17:50
@jamie-at-arkifi You can use syntax for relative IDs to avoid constructing absolute IDs manually. They look like `$self/reference/id`, e.g. `$self/frontendIPConfigurations/frontend-ip4`. They will be resolved automatically. Note the camelCase (not kebab_case). 

@mjeffryes If that works for @jamie-at-arkifi, we can probably close this issue as a dupe of #631

**Comment by jamie-at-arkifi** [comment] 2024-04-30 15:21
idk, I rewrote it in azure classic and moved on. I'll take your word for it that it works.

**Comment by mikhailshilkov** [comment] 2024-04-30 23:47
Duplicate of https://github.com/pulumi/pulumi-azure-native/issues/631

**Closed by mikhailshilkov** 2024-04-30 23:47 UTC
Labels: impact/usability, kind/bug, resolution/duplicate
