### ISSUE TITLE
`vaultName not found in resource state` when trying to delete Keyvault Secret

### ISSUE THREAD

**Issue by tyler-ball** [pulumi/pulumi-azure-native#3357] opened 2024-06-17 20:02 UTC
### What happened?

Hey everyone, I recently started seeing an error trying to delete a KeyVault secret. I can successfully delete the keyvault and secrets in it if I use the browser, so I don't think it is a user permission issue. I also can reproduce this with either my personal Azure user and a service principal.

Running `pulumi up -y` works to successfully create my Keyvault and Secrets, but `pulumi destroy -y` throws the following error:

```
  azure-native:keyvault:Secret (test-secret):
    error: vaultName not found in resource state
```

The `inputs` section of my `pulumi export` for the associated resource looks like:

```
    "inputs": {
        "properties": {
            "value": "***"
        },
        "resourceGroupName": "tyler_poc77157078",
        "secretName": "my-sercret",
        "vaultName": "tyler-poc-kv"
    },
```

### Example

```
import pulumi
import pulumi_azure_native as azure_native
import pulumi_azuread as azuread

from pulumi_azure_native import (keyvault, resources)

config = pulumi.Config("env-builder")
nameOfEnv = config.require("name-of-env")[:10]
location = config.require("location")
nameOfResourceGroup = f"{nameOfEnv}"
nameOfKeyVault = f"{nameOfEnv}-kv".replace("_", "-")

pulumi_provider_client_info = azuread.get_client_config()

resource_group = resources.ResourceGroup(
    resource_name=nameOfResourceGroup,
    location=location,
    tags={
        "CreatedOn": "2024-06-15",
        "Owner": "Tyler Ball",
        "Project": "Deployement POC",
    },
)

key_vault = keyvault.Vault(nameOfKeyVault,
    vault_name= nameOfKeyVault,
    resource_group_name=resource_group.name,
    location=resource_group.location,
    properties={
        "sku": {
            "name": "standard",
            "family": "A"
        },
        "enable_rbac_authorization": True,
        "tenant_id": pulumi_provider_client_info.tenant_id,
        "create_mode": keyvault.CreateMode.DEFAULT,
        "enable_soft_delete": False,
    })

keyvault.Secret(
    "test-secret",
    properties=azure_native.keyvault.SecretPropertiesArgs(
        value= "foobar",
    ),
    vault_name= key_vault.name,
    resource_group_name= resource_group.name,
)
```

### Output of `pulumi about`

$ pulumi about
CLI
Version      3.120.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  azure-native  2.45.0
resource  azuread       5.51.0
resource  command       0.9.2
resource  kubernetes    4.13.1
language  python        unknown
resource  random        4.16.2
resource  tls           5.0.3

Host
OS       darwin
Version  14.5
Arch     arm64

This project is written in python: executable='/Users/tylerball/CZ/pj.venv/bin/python' version='3.12.3'

Current Stack: organization/environment-builder/tyler_poc

Found no resources associated with tyler_poc

Found no pending operations associated with tyler_poc

Backend
Name           Tylers-MacBook-Pro-5.local
URL            azblob://stacks
User           tylerball
Organizations
Token type     personal

Dependencies:
NAME                    VERSION
azure-identity          1.16.1
azure-keyvault-secrets  4.8.0
azure-mgmt-resource     23.1.1
debugpy                 1.8.1
pip                     24.0
pulumi_azure_native     2.45.0
pulumi_azuread          5.51.0
pulumi-command          0.9.2
pulumi_kubernetes       4.13.1
pulumi_random           4.16.2
pulumi_tls              5.0.3
setuptools              70.0.0
wheel                   0.43.0

Pulumi locates its logs in /var/folders/wt/zcjf29_17q19l_psqz21v33c0000gn/T/ by default

### Additional context

I'm currently using Azure blobs as the stack storage, but I can replicate this with local file storage as well. 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment] 2024-06-18 09:18
Hi @tyler-ball, sorry you're running into this issue. I was able to reproduce it. We'll look into it.

The erroring code is [here](https://github.com/pulumi/pulumi-azure-native/blob/6e1ec6cf98a0f81c57fb5a9213912ed344cc53c1/provider/pkg/resources/customresources/custom_keyvault.go#L23).

**Comment by thomas11** [comment] 2024-06-18 09:30
Exporting the KV secret stack state after creation, it looks like this:
```json
            {
                "urn": "urn:pulumi:dev::azn-3357-kv::azure-native:keyvault:Secret::test-secret",
                "custom": true,
                "id": "/subscriptions/S/resourceGroups/tkappler742f61bd/providers/Microsoft.KeyVault/vaults/tkappler-kv/secrets/test-secret",
                "type": "azure-native:keyvault:Secret",
                "inputs": {
                    "properties": {
                        "value": "foobar"
                    },
                    "resourceGroupName": "tkappler742f61bd",
                    "secretName": "test-secret",
                    "vaultName": "tkappler-kv"
                },
                "outputs": {
                    "__inputs": {
                        "4dabf18193072939515e22adb298388d": "1b47061264138c4ac30d75fd1eb44270",
                        "ciphertext": "..."
                    },
                    "id": "/subscriptions/S/resourceGroups/tkappler742f61bd/providers/Microsoft.KeyVault/vaults/tkappler-kv/secrets/test-secret",
                    "location": "westus2",
                    "name": "test-secret",
                    "properties": {
                        "attributes": {
                            "created": 1718702162,
                            "enabled": true,
                            "updated": 1718702162
                        },
                        "secretUri": "https://tkappler-kv.vault.azure.net/secrets/test-secret",
                        "secretUriWithVersion": "https://tkappler-kv.vault.azure.net/secrets/test-secret/463a8db4acea4f1bac36a7dbd0e7e496"
                    },
                    "type": "Microsoft.KeyVault/vaults/secrets"
                },
                "parent": "urn:pulumi:dev::azn-3357-kv::pulumi:pulumi:Stack::azn-3357-kv-dev",
                "dependencies": [
                    "urn:pulumi:dev::azn-3357-kv::azure-native:keyvault:Vault::tkappler-kv",
                    "urn:pulumi:dev::azn-3357-kv::azure-native:resources:ResourceGroup::tkappler"
                ],
                "provider": "urn:pulumi:dev::azn-3357-kv::pulumi:providers:azure-native::default_2_45_0::5e371f26-7b1b-4f8b-975b-a27c2cf583d8",
                "propertyDependencies": {
                    "properties": [],
                    "resourceGroupName": [
                        "urn:pulumi:dev::azn-3357-kv::azure-native:resources:ResourceGroup::tkappler"
                    ],
                    "vaultName": [
                        "urn:pulumi:dev::azn-3357-kv::azure-native:keyvault:Vault::tkappler-kv"
                    ]
                },
                "created": "2024-06-18T09:16:03.443574Z",
                "modified": "2024-06-18T09:16:03.443574Z",
                "sourcePosition": "project:///venv/lib/python3.12/site-packages/pulumi_azure_native/keyvault/secret.py#148"
            }
```

**Comment by AKSNewbie** [comment] 2024-06-21 10:18
Hi, yeah...i am seeing the same error when trying to remove a secret via ADO (decom pipeline), just started last couple of days.

**Comment by danielrbradley** [comment] 2024-06-21 12:53
It turns out this is a bug in the v3.120.0 version of the Pulumi CLI. Downgrading to v3.119.0 will work around the issue for now until a patch is released.

**Comment by AKSNewbie** [comment] 2024-06-21 13:51
@danielrbradley - i don't see anywhere in my code that i am specifying the version of pulumi CLI - we deploy using ADO/IaC in C# and only specify versions of the packages such as these:
![image](https://github.com/pulumi/pulumi-azure-native/assets/70979792/7eb94678-bfcc-4195-93d6-f0de99fda1aa)

**Comment by danielrbradley** [comment] 2024-06-21 14:05
@AKSNewbie it's not the C# package, it's the Pulumi CLI tool that needs to be specified. This is likely installed by your ADO task: https://github.com/pulumi/pulumi-az-pipelines-task - by setting the `versionSpec` property to `3.119.0`

**Comment by AKSNewbie** [comment] 2024-06-21 14:44
@danielrbradley - that fixed it, thanks!

**Comment by j-fulbright** [comment] 2024-06-21 19:58
Yay. I was beginning to think it was just me!

**Comment by danielrbradley** [comment] 2024-06-27 07:50
This is now fixed. This was only broken in `v3.120.0` of the CLI. This is not cause by specific language SDK versions. Upgrade to `v3.121.0` or greater of the `pulumi` CLI.

- This was a bug introduced by https://github.com/pulumi/pulumi/pull/16302
- Tracking issue in the core pulumi project: https://github.com/pulumi/pulumi/issues/16440
- This was fixed by https://github.com/pulumi/pulumi/pull/16441
- Fixed release: https://github.com/pulumi/pulumi/releases/tag/v3.121.0

**Closed by danielrbradley** 2024-06-27 07:50 UTC
Labels: kind/bug, resolution/fixed, area/providers, kv
