### ISSUE TITLE
On WebApp, unable to remove default documents.

### ISSUE THREAD

**Issue by thecodetinker** [pulumi/pulumi-azure-native#1151] opened 2021-09-17 13:54 UTC
Trying to remove all the default documents from a Web Application (it's an API).

## Steps to reproduce

Create a `Pulumi.AzureNative.Web.WebApp` with `DefaultDocuments` set to an empty list (or `null`)

``` 
var args = new WebAppArgs
{
    SiteConfig = new SiteConfigArgs
    {
        DefaultDocuments = new InputList<string>()
    },
};

var webApp = new WebApp("WebApp", args);
```
Expected: The default documents list should be empty in the Azure Portal.
Actual: The default HTML document is still listed.

If I set a _different_ document, that works. But there doesn't appear to be any way of setting zero default documents.

**Comment by mikhailshilkov** [comment] 2021-09-17 15:23
I believe that's how Azure API behaves. I used your code and logged what we send to Azure:

```
{"location":"centralus",
"properties":{
"hyperV":false,
"isXenon":false,
"reserved":false,
\"scmSiteAlsoStopped":false,
"serverFarmId":"/subscriptions/0282681f-7a9e-424b-80b2-96babd57a8a1/resourceGroups/appservice-rg0efee660/providers/Microsoft.Web/serverfarms/aspc97b92b8",
"siteConfig":{
  "defaultDocuments":[],
  "http20Enabled":true,
  "localMySqlEnabled":false,
  "netFrameworkVersion":"v4.6"
}}}
````

Note that `defaultDocuments` are empty and yet I get a default document in the portal.

**Comment by thomas11** [comment] 2024-07-30 06:18
I think this can be closed as "by design" (on Azure's side). Feel free to re-open if that's not the case.

**Closed by thomas11** 2024-07-30 06:18 UTC
Labels: kind/bug, upstream/service, resolution/by-design
