### ISSUE TITLE
[azure-native] Create subnet with a delegation: example incomplete

### ISSUE THREAD

**Issue by PLsergent** [pulumi/pulumi-azure-native#2404] opened 2023-04-25 09:55 UTC
File: [themes/default/content/registry/packages/azure-native/api-docs/network/subnet/_index.md](https://www.pulumi.com/registry/packages/azure-native/api-docs/network/subnet/#create-subnet-with-a-delegation)

No parameter `delegations` in the example.

If I understood correctly the documentation is based on the [API specification defined here](https://github.com/Azure/azure-rest-api-specs/blob/5eb162ac81b3e30e30b5326a5380fc93a6040b07/specification/network/resource-manager/Microsoft.Network/stable/2020-11-01/examples/SubnetCreateWithDelegation.json), and there is indeed the parameter for this example. So maybe it has to do with the automation process on your side?

No big deal I was just curious to know how it works under the hood 😄 Thanks!

**Comment by rquitales** [comment] 2023-04-25 18:58
@PLsergent Thanks for reporting this docs issue. We are indeed automating the docs generation., and it looks like this might be related to an upstream example issue.

In the [example you linked for creating a subnet with a delegation](https://github.com/Azure/azure-rest-api-specs/blob/5eb162ac81b3e30e30b5326a5380fc93a6040b07/specification/network/resource-manager/Microsoft.Network/stable/2020-11-01/examples/SubnetCreateWithDelegation.json), the request is identical to the [one without](https://github.com/Azure/azure-rest-api-specs/blob/5eb162ac81b3e30e30b5326a5380fc93a6040b07/specification/network/resource-manager/Microsoft.Network/stable/2020-11-01/examples/SubnetCreate.json).

The example with subnet delegation has the `delegations` parameter in the response body, which will not show in the Pulumi examples since our example only showcases the request, not the response.

This looks like something that can be address upstream!

**Comment by mikhailshilkov** [comment] 2023-08-06 10:22
Closing as a dupe of https://github.com/pulumi/pulumi-azure-native/issues/2332

**Closed by mikhailshilkov** 2023-08-06 10:22 UTC
Labels: kind/enhancement, resolution/duplicate, awaiting-upstream, area/docs
