### ISSUE TITLE
RAM problem when import pulumi-azure-native lib in Flask process

### ISSUE THREAD

**Issue by Zviger** [pulumi/pulumi-azure-native#2335] opened 2023-03-27 15:14 UTC
### What happened?

In my company's project we run the infra creating in Flask with gunicorn. Before using Azure Native, we used Azure Classic and it works well, but when we rewrote code to Azure Native we saw, that our Ubuntu VM was dead. After some investigation we found, that importing Azure Native library in Flask process start to take all RAM. Looks like dead loop or something happens. I don't know is it only problem with Flask, or also Django, for example, doesn't work well in this case too, idk. Also we r using python3.8, but to test this problem we updated all libs to the latest ones and switched to the python3.11, but it didn't help.

### Expected Behavior

Importing Azure Native in flask doesn't take all RAM of VM.

### Steps to reproduce

Create simple Flask project in Ubuntu and import pulumi_azure_native. U will see, that RAM is going off. (Monitor RAM usage to do not allow ur system to stuck)

### Output of `pulumi about`

CLI          
Version      3.59.0
Go Version   go1.20.2
Go Compiler  gc

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

### Additional context

Feel free to ask any questions u need to allow me to help u ^^

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment] 2023-03-27 21:22
Hi @Zviger and thanks for reporting this. It's unfortunate to hear that importing this library causes memory issues for you.

To confirm can you confirm that this issue is isolated to using Flask and Azure Native within your VM? For example, can you try running a Python program that imports the Azure Native library only, and not Flask on your Ubuntu VM to see if you run into memory issues as well?

It would also be helpful for us if you could provide some minimal code and system specifications for your VM for us to try and reproduce this issue.

It is known that our Azure Native library is larger than our Azure Classic library. So it would be expected to have increased memory usage when trying to import Azure Native since it is larger.

**Comment by Zviger** [comment] 2023-03-27 21:31
Hi @rquitales

Thank u for ur response.
We already using Azure Native in another case with just python process and it works well. And it looks like not a problem of VM itself or not a problem of low memory size in VM, cause I run the API just with Flask dev server (without gunicorn) on my local laptop with 16GB of RAM, and python process works the same - it just grub all the RAM very fast. I'm using Ubuntu 20.04, VM has 22.04.

**Comment by Zviger** [comment] 2023-03-27 21:36
I also tried to understand where the process is stack in a loop or something with PDB, but I didn't. From the first view looks like Flask can't find the lib in the right way, cause I saw with PDB that the process does a lot of the same steps of importing, but mb I didn't understand it correctly, idl.

**Comment by rquitales** [comment] 2023-03-27 21:49
Do you face memory issues when you run your program with gunicorn on your local laptop as well? I suspect that this might be a gunicorn configuration issue. Perhaps the number of workers is too high currently, in that every worker spun up is importing the Azure Native library and is causing the VM to run out of memory since multiple processes are now importing it.

**Comment by Zviger** [comment] 2023-03-27 21:51
I thought same, that's why I wrote, that I've run app WITHOUT gunicorn just with Flask dev server. The result the same.

**Comment by mikhailshilkov** [comment] 2023-09-12 12:33
V2 of the provider is now released and it's quite a bit lighter (although still pretty large). Do you want to give it a try @Zviger?

**Comment by mikhailshilkov** [comment] 2023-09-29 10:36
I think I'll go ahead and mark it as resolved in v2.0 which should have much lower RAM footprint. If folks still have issue after upgrading, please open a new issue to track further progress.

**Closed by mikhailshilkov** 2023-09-29 10:36 UTC
Labels: impact/usability, kind/bug, impact/performance, resolution/fixed

**Comment by Zviger** [comment] 2023-09-29 11:14
@mikhailshilkov, thank u. Sorry for no responses so long, our project was closed and I don't have access to the code that faced this bug. Mb I'll try to replicate it later. Thank for ur work!
