### ISSUE TITLE
Unable to specify CustomHttpsParameters when creating Pulumi.AzureNative.Cdn.CustomDomain

### ISSUE THREAD

**Issue by mdhomer** [pulumi/pulumi-azure-native#1875] opened 2022-08-05 15:37 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

### Affected area/feature

Pulumi.AzureNative.Cdn.CustomDomain Docs -
There is no input parameter to allow enabling this feature via IAC. However the subsequent setting is available as an output variable AFAIK:
https://www.pulumi.com/registry/packages/azure-native/api-docs/cdn/customdomain/#customhttpsparameters_csharp

Via the UI this is a boolean flag to enable this feature. However I can't find any way this is captured via the CustomDomain/Profile json & subsequently the Pulumi AzureNative API's
![Screenshot 2022-08-05 at 16 35 11](https://user-images.githubusercontent.com/9245830/183111630-d8c9fb42-4cd3-44d8-9fe0-4f1361348a89.png)

**Comment by guineveresaenger** [comment] 2022-08-10 00:13
Hi @mdhomer - thank you for filing this issue.

It looks like this should be an input parameter as well - although perhaps it would be called `CustomDomainHttpsParameters` but I'll be following up with the reason this doesn't exist yet.

**Comment by guineveresaenger** [comment] 2022-08-10 17:11
Hi @mdhomer - I asked and it turns out the reason this doesn't exist yet is that there's currently no ARM template support for this.

As this is a duplicate of https://github.com/pulumi/pulumi-azure-native/issues/569, I'll close out this issue, but feel free to follow along on any development on #569!

**Closed by guineveresaenger** 2022-08-10 17:11 UTC
Labels: kind/enhancement, resolution/duplicate
