### ISSUE TITLE
Problem with FirewallPolicyRuleCollectionGroup

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi-azure-native#2671] opened 2023-08-22 14:54 UTC
### What happened?

When migrating to v2, customer reports this error on the [`FirewallPolicyRuleCollectionGroup`](https://www.pulumi.com/registry/packages/azure-native/api-docs/network/firewallpolicyrulecollectiongroup/) resource:

```sh
Diagnostics:
  pulumi:pulumi:Stack (azure-native-v2-migration-ringo):
    error: update failed

  azure-native:network:FirewallPolicyRuleCollectionGroup (customer-test-network):
    error: Code="Failed" Message="The async operation failed." AdditionalInfo=[{"Message":"The request is invalid.","ModelState":{"resource.properties.ruleCollections[0]":["An error has occurred."]}}]
```

### Expected Behavior

The attached code worked for the customer on v1.

### Steps to reproduce

Minimal reproducable program:

```go
package main

import (
	"github.com/pulumi/pulumi-azure-native-sdk/network/v2"
	"github.com/pulumi/pulumi-azure-native-sdk/resources/v2"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		// Resource group
		rg, err := resources.NewResourceGroup(ctx, "customer-test-rg", &resources.ResourceGroupArgs{
			Location:          pulumi.String("WestEurope"),
			ResourceGroupName: pulumi.String("customer-test-resource-group"),
		})
		if err != nil {
			return err
		}

		// IP Group
		ipgnp, err := network.NewIpGroup(ctx, "ipGroup", &network.IpGroupArgs{
			IpAddresses: pulumi.StringArray{
				pulumi.String("13.64.39.16/32"),
				pulumi.String("40.74.146.80/31"),
				pulumi.String("40.74.147.32/28"),
			},
			IpGroupsName:      pulumi.String("ipGroups1"),
			Location:          pulumi.String("West Europe"),
			ResourceGroupName: rg.Name,
			Tags: pulumi.StringMap{
				"key1": pulumi.String("value1"),
			},
		})
		if err != nil {
			return err
		}

		// FirewallPolicy
		fwPolicy, err := network.NewFirewallPolicy(ctx, "customer-test-fw-policy", &network.FirewallPolicyArgs{
			ResourceGroupName: rg.Name,
		})
		if err != nil {
			return err
		}

		// PolicyRuleCollectionGroup
		_, err = network.NewFirewallPolicyRuleCollectionGroup(ctx, "customer-test-network", &network.FirewallPolicyRuleCollectionGroupArgs{
			FirewallPolicyName: fwPolicy.Name,
			Priority:           pulumi.Int(100),
			ResourceGroupName:  rg.Name,
			RuleCollections: pulumi.Array{
				network.AzureFirewallApplicationRuleCollectionArgs{
					Name:     pulumi.String("cloudflared-edge-requirements"),
					Priority: pulumi.IntPtr(110),
					Action: network.AzureFirewallRCActionArgs{
						Type: pulumi.String("Allow"),
					},
					Rules: network.AzureFirewallApplicationRuleArray{
						network.AzureFirewallApplicationRuleArgs{
							Description: pulumi.String("cloudflared to edge for h2mux, http2, and quic"),
							Name:        pulumi.String("cloudflared-to-edge"),
							SourceIpGroups: pulumi.StringArray{
								ipgnp.ID().ToStringOutput(),
							},
							Protocols: network.AzureFirewallApplicationRuleProtocolArray{
								network.AzureFirewallApplicationRuleProtocolArgs{
									ProtocolType: pulumi.String("tcp"),
									Port:         pulumi.Int(7844),
								},
								network.AzureFirewallApplicationRuleProtocolArgs{
									ProtocolType: pulumi.String("udp"),
									Port:         pulumi.Int(7844),
								},
							},
							TargetFqdns: pulumi.StringArray{
								pulumi.String("region1.v2.argotunnel.com"),
								pulumi.String("region2.v2.argotunnel.com"),
							},
						},
					},
				},
			},
		})

		if err != nil {
			return err
		}
		return nil
	})
}
```

### Output of `pulumi about`

```
CLI          
Version      3.78.1
Go Version   go1.20.7
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  2.3.0
azure-native  2.3.0
azure-native  2.1.1
azure-native  2.1.1
go            unknown

Host     
OS       darwin
Version  13.5
Arch     arm64

This project is written in go: executable='/opt/homebrew/bin/go' version='go version go1.21.0 darwin/arm64'

Current Stack: team-ce/azure-native-v2-migration/ringo

TYPE                                  URN
pulumi:pulumi:Stack                   urn:pulumi:ringo::azure-native-v2-migration::pulumi:pulumi:Stack::azure-native-v2-migration-ringo
pulumi:providers:azure-native         urn:pulumi:ringo::azure-native-v2-migration::pulumi:providers:azure-native::default
azure-native:resources:ResourceGroup  urn:pulumi:ringo::azure-native-v2-migration::azure-native:resources:ResourceGroup::customer-test-rg
azure-native:network:FirewallPolicy   urn:pulumi:ringo::azure-native-v2-migration::azure-native:network:FirewallPolicy::customer-test-fw-policy
azure-native:network:IpGroup          urn:pulumi:ringo::azure-native-v2-migration::azure-native:network:IpGroup::ipGroup


Found no pending operations associated with team-ce/ringo

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/ringods
User           ringods
Organizations  ringods, team-ce, pulumiverse, demo

Dependencies:
NAME                                                    VERSION
github.com/pulumi/pulumi-azure-native-sdk/resources/v2  2.1.1
github.com/pulumi/pulumi-azure-native-sdk/storage/v2    2.1.1
github.com/pulumi/pulumi/sdk/v3                         3.74.0

Pulumi locates its logs in /var/folders/yq/10j1hf8s1ks9f23yxrdbbbb40000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment] 2023-08-23 13:56
The root cause of the issue appears to be the way our Go language represents discriminated unions.

In the `2023-02-01` version of `FirewallPolicyRuleCollectionGroup` the "rule collections" property and "rules" property within it are both discriminated unions.

```yaml
  ruleCollections:
    type: array
    items:
      oneOf:
        - type: object
          $ref: "#/types/azure-native:network:FirewallPolicyFilterRuleCollection"
        - type: object
          $ref: "#/types/azure-native:network:FirewallPolicyNatRuleCollection"
      discriminator:
        propertyName: ruleCollectionType
        mapping:
          FirewallPolicyFilterRuleCollection: "#/types/azure-native:network:FirewallPolicyFilterRuleCollection"
          FirewallPolicyNatRuleCollection: "#/types/azure-native:network:FirewallPolicyNatRuleCollection"
    description: Group of Firewall Policy rule collections.
```
```yaml
  rules:
    type: array
    items:
      oneOf:
        - type: object
          $ref: "#/types/azure-native:network:ApplicationRule"
        - type: object
          $ref: "#/types/azure-native:network:NatRule"
        - type: object
          $ref: "#/types/azure-native:network:NetworkRule"
      discriminator:
        propertyName: ruleType
        mapping:
          ApplicationRule: "#/types/azure-native:network:ApplicationRule"
          NatRule: "#/types/azure-native:network:NatRule"
          NetworkRule: "#/types/azure-native:network:NetworkRule"
    description: List of rules included in a rule collection.
```

In Typescript your code would have surfaced the errors `Property 'ruleType' is missing` and `Property 'ruleCollectionType' is missing`. 

It appears that the generated Go SDK has the following issues:
- Missing property `ruleCollectionType` on `RuleCollections`.
- The type for `FirewallPolicyFilterRuleCollection`
- The type for `FirewallPolicyNatRuleCollection`
- The ApplicationRule, NatRule and NetworkRule types  are lacking the `ruleType` field

Downgrading to v1.104.0 still has the same issue so we need to confirm the previous working version.

## Revisiting investigation after a break

Ok, found a solution ... it turns out that the type inside the `RuleCollections` `pulumi.Array` is the wrong type. The correct type is `FirewallPolicyFilterRuleCollection` but this doesn't implenent the `Input` interface so needs wrapping. This is also a "plain" type which doesn't support inputs being passed in for its fields so we have to wrap the whole thing in an `Apply` function off the ipgnp ID property.

Because you were using the wrong type for the collection, the rules property was also of the wrong type.

Here's the working code:

```go
package main

import (
	"github.com/pulumi/pulumi-azure-native-sdk/network/v2"
	"github.com/pulumi/pulumi-azure-native-sdk/resources/v2"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		// Resource group
		rg, err := resources.NewResourceGroup(ctx, "customer-test-rg", &resources.ResourceGroupArgs{
			Location:          pulumi.String("WestEurope"),
			ResourceGroupName: pulumi.String("customer-test-resource-group"),
		})
		if err != nil {
			return err
		}

		// IP Group
		ipgnp, err := network.NewIpGroup(ctx, "ipGroup", &network.IpGroupArgs{
			IpAddresses: pulumi.StringArray{
				pulumi.String("13.64.39.16/32"),
				pulumi.String("40.74.146.80/31"),
				pulumi.String("40.74.147.32/28"),
			},
			IpGroupsName:      pulumi.String("ipGroups1"),
			Location:          pulumi.String("West Europe"),
			ResourceGroupName: rg.Name,
			Tags: pulumi.StringMap{
				"key1": pulumi.String("value1"),
			},
		})
		if err != nil {
			return err
		}

		// FirewallPolicy
		fwPolicy, err := network.NewFirewallPolicy(ctx, "customer-test-fw-policy", &network.FirewallPolicyArgs{
			ResourceGroupName: rg.Name,
		})
		if err != nil {
			return err
		}

		// PolicyRuleCollectionGroup
		_, err = network.NewFirewallPolicyRuleCollectionGroup(ctx, "customer-test-network", &network.FirewallPolicyRuleCollectionGroupArgs{
			FirewallPolicyName: fwPolicy.Name,
			Priority:           pulumi.Int(100),
			ResourceGroupName:  rg.Name,
			RuleCollections: pulumi.Array{
				ipgnp.ID().ApplyT(func(id string) network.FirewallPolicyFilterRuleCollection {
					return network.FirewallPolicyFilterRuleCollection{
						Name:     pulumi.StringRef("cloudflared-edge-requirements"),
						Priority: pulumi.IntRef(110),
						Action: &network.FirewallPolicyFilterRuleCollectionAction{
							Type: pulumi.StringRef("Allow"),
						},
						RuleCollectionType: "FirewallPolicyFilterRuleCollection",
						Rules: []interface{}{
							network.ApplicationRule{
								Description: pulumi.StringRef("cloudflared to edge for h2mux, http2, and quic"),
								Name:        pulumi.StringRef("cloudflared-to-edge"),
								RuleType:    "ApplicationRule",
								SourceIpGroups: []string{
									id,
								},
								Protocols: []network.FirewallPolicyRuleApplicationProtocol{
									{
										ProtocolType: pulumi.StringRef("http"),
										Port:         pulumi.IntRef(7844),
									},
									{
										ProtocolType: pulumi.StringRef("https"),
										Port:         pulumi.IntRef(7845),
									},
								},
								TargetFqdns: []string{
									"region1.v2.argotunnel.com",
									"region2.v2.argotunnel.com",
								},
							},
						},
					}
				}),
			},
		})

		if err != nil {
			return err
		}
		return nil
	})
}
```

**Comment by danielrbradley** [comment] 2023-08-23 13:59
Closing as works correctly once the correct types are used

**Closed by danielrbradley** 2023-08-23 13:59 UTC
Labels: kind/bug, resolution/fixed, customer/feedback

**Comment by stefanhenseler** [comment] 2023-08-28 20:42
@danielrbradley Okay, it seems wrapping the types works.  Thanks for proposing this solution.

**Comment by danielrbradley** [comment] 2023-08-29 08:24
That's great to hear @stefanhenseler 

I've also filed this ticket to try and improve the usability of these types:
- https://github.com/pulumi/pulumi/issues/13775
