### ISSUE TITLE
Please add All certificate operations - create/update/delete in Az Key Vault

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi-azure-native#1905] opened 2022-08-12 17:27 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Please add support for all of the certificate CRUD operations for Azure Key Vault. 

### Affected area/feature
Azure Native Provider

**Comment by lblackstone** [comment] 2022-08-16 20:40
As far as I can tell, this feature [isn't currently supported](https://stackoverflow.com/questions/49789360/create-key-vault-certificate-using-arm-template) by the ARM API that unpins the azure-native provider.

I'll put this on the backlog for now in case I'm missing something.

**Comment by mikhailshilkov** [comment] 2023-02-07 13:30
Dupe of https://github.com/pulumi/pulumi-azure-native/issues/742

**Closed by mikhailshilkov** 2023-02-07 13:30 UTC
Labels: kind/enhancement, resolution/duplicate, dataplane
