### ISSUE TITLE
Pre-release breaks plugin installation

### ISSUE THREAD

**Issue by abhinav** [pulumi/pulumi-azure-native#2239] opened 2023-02-10 00:27 UTC
Discussed this with @danielrbradley on Slack, creating an issue to track.

The pre-release https://github.com/pulumi/pulumi-azure-native/releases/tag/v1.94.1-alpha.1675974957%2B9883672c breaks plugin downloads at least in tests with:

```
+ pulumi:pulumi:Stack: (create)
    [urn=urn:pulumi:p-it-fv-az437-9-azure-java-7d2d1b10::azure-java-appservice-sql::pulumi:pulumi:Stack::azure-java-appservice-sql-p-it-fv-az437-9-azure-java-7d2d1b10]
error: Could not automatically download and install resource plugin 'pulumi-resource-azure-native' at version v1.94.1-alpha.1675974957+9883672c, install the plugin using `pulumi plugin install resource azure-native v1.94.1-alpha.1675974957+9883672c`.
Underlying error: error downloading plugin azure-native to file: failed to download plugin: azure-native-1.94.1-alpha.1675974957+9883672c: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-azure-native-v1.94.1-alpha.1675974957%2B9883672c-linux-amd64.tar.gz
```

The URL at which it expects the plugin doesn't exist because it expects the version number to be part of the URL.
Example failure in https://github.com/pulumi/pulumi-java/actions/runs/4138595684/jobs/7157363810.

**Comment by Frassle** [comment] 2023-02-10 08:36
So I think there's two problems here:
1) https://github.com/pulumi/pulumi-azure-native/releases/tag/v1.94.1-alpha.1675974957%2B9883672c <- That is not the format of a pulumi release. The .tar.gz file names should match the version of the release, these ones don't they're all just called  "1.0.0-alpha.0+dev"

2) Java is pulling alpha releases for a version range of [\(1.0,2.0\]](https://github.com/pulumi/examples/blob/master/azure-java-static-website/pom.xml#L29). Pretty sure the intention for that example is to pull the latest production release of the library.

While it would be good to fix 1, 2 seems more important as it means users trying that example may end up on snapshot versions of the library!

A quick search suggests that Maven _might just not support this_ https://stackoverflow.com/a/14434887.
In which case we should fix up the examples to never use version ranges. But I'll let someone else double check that investigation, I don't have much Java experience.

**Comment by danielrbradley** [comment] 2023-02-10 09:04
Yeah I think the core problem here is that prerelease came from a PR with a bug causing the filename version to be wrong. Will push a new prerelease and see if it handles that better.

**Comment by danielrbradley** [comment] 2023-02-10 10:48
Hopefully by switching prereleases to also be drafts with no tag and not pushing the assets to S3 this will resolve the issue.

Specific change: https://github.com/pulumi/pulumi-azure-native/pull/2222/commits/923a7a551b419769ab02d76779df3f2f49cb5fa1

**Comment by danielrbradley** [comment] 2023-02-10 11:20
There seems to be a few intersecting issues here which I'm still trying to pull apart.
- The previous prerelease had the assets incorrectly marked as 1.0 so when any SDK requested them the package name didn't match what the SDK expected.
- Creating tags for every prerelease was not desired behaviour, so switching to only drafting releases makes more sense. However, this was unlikely the cause of the issue. If I've now understood what the java test is doing, it's using Gradle to resolve the "latest" version. This might actually be fine to allow gradle to use the prerelease version for testing, but it's not clear if publishing prerelease versions to gradle might break customers if they also use version ranges.
- Maven doesn't have lock files, so in combination with Frassle's SO question, there's no way of specifying version ranges and not accidentally getting prerelease versions. So I think we should disable Java SDK prereleases.

Next steps:
1. Re-enable S3 upload of prerelease provider assets.
2. Disable publishing prerelease java SDKs or disable if it will negatively affect customers using version ranges.
3. Cut the next major release to unbreak any customers pulling the current prerelease version.

**Comment by abhinav** [comment] 2023-02-10 16:43
> Hopefully by switching prereleases to also be drafts with no tag and not pushing the assets to S3 this will resolve the issue.
> 
> Specific change: [923a7a5](https://github.com/pulumi/pulumi-azure-native/commit/923a7a551b419769ab02d76779df3f2f49cb5fa1)

That seems to have fixed it. Thanks!

From @Frassle's linked comment:

> Unless the artifact version ends with -SNAPSHOT, Maven is going to consider it a valid release build. As far as I know, -alpha1 has no special meaning to Maven. It's just another random qualifier.

Could we add `-SNAPSHOT` to the pre-release Java SDKs? That'll prevent it from picking pre-releases.

**Comment by danielrbradley** [comment] 2023-02-10 20:29
I'm happy the tests are fixed, but I'm confused _why_ they're fixed ... I've not yet published a new version 🤔 Unfortunately, when it doesn't fail, it doesn't seem to print the version being installed either.

The latest commit on Maven is still timestamped:
https://mvnrepository.com/artifact/com.pulumi/azure-native/1.94.1-alpha.1675974957+9883672c
Timestamp: Thu Feb 09 2023 20:35:57 GMT+0000 (last night's build).

Interestingly, I don't see the broken release in Maven any more: azure-native-1.94.1-alpha.1676022955+923a7a55 - perhaps someone's gone and deleted this manually? cc: @t0yv0 maybe?

**Comment by t0yv0** [comment] 2023-02-10 20:51
Didn't take any action here... Strange..

**Comment by abhinav** [comment] 2023-02-10 20:58
Could be because the latest pre-release puts version numbers in the file names again? https://github.com/pulumi/pulumi-azure-native/releases/tag/untagged-10ca26f7247767f7a887

**Closed** 2023-02-28 10:22 UTC
Labels: kind/engineering
